-- Core schema: profiles, students, payments, attendance.
-- Idempotent: safe to re-run against an already-provisioned project.

do $$ begin
  create type public.user_role as enum ('administrator', 'teacher', 'student');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id),
  email text not null,
  full_name text,
  role public.user_role not null default 'student',
  created_at timestamptz not null default now()
);

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  profile_id uuid references public.profiles (id),
  real_name text not null,
  english_name text,
  level text not null check (level in ('A', 'B', 'C')),
  phone text,
  parent_phone text,
  join_date date not null default current_date,
  payment_deadline integer not null check (payment_deadline between 1 and 31),
  monthly_fee numeric not null default 0,
  status text not null default 'Active' check (status in ('Active', 'Inactive')),
  notes text,
  created_at timestamptz not null default now()
);

-- Pre-existing UI field not yet present on the live table (additive, nullable).
alter table public.students add column if not exists group_name text;

create table if not exists public.payments (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students (id) on delete cascade,
  year integer not null,
  month integer not null check (month between 1 and 12),
  paid boolean not null default false,
  paid_date date
);

create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students (id) on delete cascade,
  date date not null,
  status text not null check (status in ('Present', 'Late', 'Absent'))
);

-- storageBridge.js relies on upsert-by-period semantics (one record per
-- student+period; re-toggling the same value clears it). Both tables are
-- currently empty, so these are zero-risk to add.
do $$ begin
  alter table public.payments
    add constraint payments_student_period_unique unique (student_id, year, month);
exception
  when duplicate_table then null;
  when duplicate_object then null;
end $$;

do $$ begin
  alter table public.attendance
    add constraint attendance_student_date_unique unique (student_id, date);
exception
  when duplicate_table then null;
  when duplicate_object then null;
end $$;
