-- Lessons (scheduled sessions), exams, homework, and certificates.
-- Points are computed client-side from these tables (see
-- src/utils/points.js) rather than stored, so there's nothing here that
-- can drift out of sync with its own inputs.

create table if not exists public.lessons (
  id bigint generated by default as identity primary key,
  group_name text,
  level text check (level in ('A', 'B', 'C')),
  topic text not null,
  scheduled_at timestamptz not null,
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

create table if not exists public.lesson_attendance (
  id bigint generated by default as identity primary key,
  lesson_id bigint not null references public.lessons (id) on delete cascade,
  student_id bigint not null references public.students (id) on delete cascade,
  status text not null check (status in ('Present', 'Late', 'Absent')),
  unique (lesson_id, student_id)
);

create table if not exists public.exams (
  id bigint generated by default as identity primary key,
  title text not null,
  level text check (level in ('A', 'B', 'C')),
  exam_date date not null default current_date,
  max_score numeric not null default 100,
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

create table if not exists public.exam_scores (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references public.exams (id) on delete cascade,
  student_id bigint not null references public.students (id) on delete cascade,
  score numeric not null,
  unique (exam_id, student_id)
);

create table if not exists public.homework (
  id bigint generated by default as identity primary key,
  title text not null,
  level text check (level in ('A', 'B', 'C')),
  due_date date not null default current_date,
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

create table if not exists public.homework_status (
  id bigint generated by default as identity primary key,
  homework_id bigint not null references public.homework (id) on delete cascade,
  student_id bigint not null references public.students (id) on delete cascade,
  status text not null default 'Assigned' check (status in ('Assigned', 'Submitted', 'Graded')),
  score numeric,
  unique (homework_id, student_id)
);

create table if not exists public.certificates (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students (id) on delete cascade,
  title text not null,
  issued_date date not null default current_date,
  issued_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

create index if not exists lesson_attendance_student_id_idx on public.lesson_attendance (student_id);
create index if not exists exam_scores_student_id_idx on public.exam_scores (student_id);
create index if not exists homework_status_student_id_idx on public.homework_status (student_id);
create index if not exists certificates_student_id_idx on public.certificates (student_id);
create index if not exists lesson_attendance_lesson_id_idx on public.lesson_attendance (lesson_id);
create index if not exists exam_scores_exam_id_idx on public.exam_scores (exam_id);
create index if not exists homework_status_homework_id_idx on public.homework_status (homework_id);

alter table public.lessons enable row level security;
alter table public.lesson_attendance enable row level security;
alter table public.exams enable row level security;
alter table public.exam_scores enable row level security;
alter table public.homework enable row level security;
alter table public.homework_status enable row level security;
alter table public.certificates enable row level security;

-- lessons / exams / homework: content metadata, not sensitive - every
-- signed-in role can read it (students need this for "Upcoming Lessons"
-- etc.), only admin/teacher can write.
drop policy if exists lessons_read_all on public.lessons;
create policy lessons_read_all on public.lessons for select using (auth.uid() is not null);
drop policy if exists lessons_admin_all on public.lessons;
create policy lessons_admin_all on public.lessons for all using (is_admin()) with check (is_admin());
drop policy if exists lessons_teacher_all on public.lessons;
create policy lessons_teacher_all on public.lessons for all using (is_teacher()) with check (is_teacher());

drop policy if exists exams_read_all on public.exams;
create policy exams_read_all on public.exams for select using (auth.uid() is not null);
drop policy if exists exams_admin_all on public.exams;
create policy exams_admin_all on public.exams for all using (is_admin()) with check (is_admin());
drop policy if exists exams_teacher_all on public.exams;
create policy exams_teacher_all on public.exams for all using (is_teacher()) with check (is_teacher());

drop policy if exists homework_read_all on public.homework;
create policy homework_read_all on public.homework for select using (auth.uid() is not null);
drop policy if exists homework_admin_all on public.homework;
create policy homework_admin_all on public.homework for all using (is_admin()) with check (is_admin());
drop policy if exists homework_teacher_all on public.homework;
create policy homework_teacher_all on public.homework for all using (is_teacher()) with check (is_teacher());

-- Per-student results: admin/teacher full access, student can only read
-- their own (via students.profile_id = auth.uid()).
drop policy if exists lesson_attendance_admin_all on public.lesson_attendance;
create policy lesson_attendance_admin_all on public.lesson_attendance for all using (is_admin()) with check (is_admin());
drop policy if exists lesson_attendance_teacher_all on public.lesson_attendance;
create policy lesson_attendance_teacher_all on public.lesson_attendance for all using (is_teacher()) with check (is_teacher());
drop policy if exists lesson_attendance_self_read on public.lesson_attendance;
create policy lesson_attendance_self_read on public.lesson_attendance for select
  using (exists (select 1 from public.students s where s.id = lesson_attendance.student_id and s.profile_id = auth.uid()));

drop policy if exists exam_scores_admin_all on public.exam_scores;
create policy exam_scores_admin_all on public.exam_scores for all using (is_admin()) with check (is_admin());
drop policy if exists exam_scores_teacher_all on public.exam_scores;
create policy exam_scores_teacher_all on public.exam_scores for all using (is_teacher()) with check (is_teacher());
drop policy if exists exam_scores_self_read on public.exam_scores;
create policy exam_scores_self_read on public.exam_scores for select
  using (exists (select 1 from public.students s where s.id = exam_scores.student_id and s.profile_id = auth.uid()));

drop policy if exists homework_status_admin_all on public.homework_status;
create policy homework_status_admin_all on public.homework_status for all using (is_admin()) with check (is_admin());
drop policy if exists homework_status_teacher_all on public.homework_status;
create policy homework_status_teacher_all on public.homework_status for all using (is_teacher()) with check (is_teacher());
drop policy if exists homework_status_self_read on public.homework_status;
create policy homework_status_self_read on public.homework_status for select
  using (exists (select 1 from public.students s where s.id = homework_status.student_id and s.profile_id = auth.uid()));

drop policy if exists certificates_admin_all on public.certificates;
create policy certificates_admin_all on public.certificates for all using (is_admin()) with check (is_admin());
drop policy if exists certificates_teacher_all on public.certificates;
create policy certificates_teacher_all on public.certificates for all using (is_teacher()) with check (is_teacher());
drop policy if exists certificates_self_read on public.certificates;
create policy certificates_self_read on public.certificates for select
  using (exists (select 1 from public.students s where s.id = certificates.student_id and s.profile_id = auth.uid()));
