-- Adds: a messaging/chat system, file uploads for exams and homework (with
-- student self-submission), a lesson "discussion enabled" toggle, and an
-- admin-managed certificate template. Idempotent like the existing
-- migrations (create/alter ... if not exists, drop policy if exists before
-- create policy).
--
-- Nothing here touches or removes existing rows in students, payments,
-- attendance, profiles, or certificates - every change below is either a
-- new table, a new nullable/defaulted column on an existing table, or a
-- new RLS policy that adds capability without removing any existing one
-- (RLS policies are additive/OR'd together in Postgres).

-- ============================================================
-- Storage: one shared, private bucket for every attachment type
-- (chat images/PDFs, exam files, homework files, exam/homework answers,
-- the certificate template). Keeping one bucket instead of five is the
-- minimal option and matches how this schema already shares tables across
-- features rather than fragmenting them.
--
-- Simplification, documented rather than hidden: access control on this
-- bucket is "any authenticated user can upload/read", not scoped per
-- message/recipient - Postgres storage RLS can't easily see "am I one of
-- the two people this chat message was sent to" without duplicating the
-- messages table's own logic into every storage policy. A determined,
-- signed-in user could therefore guess another file's path. That's a
-- known, accepted simplification for a small single-school deployment,
-- not an oversight - flagged here and in the PR description.
-- ============================================================

insert into storage.buckets (id, name, public)
values ('attachments', 'attachments', false)
on conflict (id) do nothing;

drop policy if exists attachments_read on storage.objects;
create policy attachments_read on storage.objects for select
  using (bucket_id = 'attachments' and auth.uid() is not null);

drop policy if exists attachments_insert on storage.objects;
create policy attachments_insert on storage.objects for insert
  with check (bucket_id = 'attachments' and auth.uid() is not null);

drop policy if exists attachments_update on storage.objects;
create policy attachments_update on storage.objects for update
  using (bucket_id = 'attachments' and auth.uid() is not null);

-- Delete is admin-only (nobody else needs to delete a stored file - a
-- "replace" just points the file_url at a newly uploaded object).
drop policy if exists attachments_delete_admin on storage.objects;
create policy attachments_delete_admin on storage.objects for delete
  using (bucket_id = 'attachments' and is_admin());

-- ============================================================
-- Messaging
-- ============================================================

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles (id),
  -- Denormalized display name, set by the client at send time. Needed
  -- because two students can share a context discussion (e.g. the same
  -- homework) without ever being allowed to look each other up in
  -- profiles - RLS intentionally never grants a student visibility into
  -- another student's profile row, only into teachers'/admins'. This is
  -- a display convenience only, not an authorization signal.
  sender_name text,
  scope text not null check (scope in ('direct', 'level', 'announcement', 'context')),
  recipient_id uuid references public.profiles (id),
  level text check (level in ('A', 'B', 'C')),
  context_type text check (context_type in ('lesson', 'homework', 'exam', 'certificate')),
  context_id bigint,
  body text,
  attachment_url text,
  attachment_name text,
  attachment_type text,
  created_at timestamptz not null default now(),
  constraint messages_body_or_attachment check (coalesce(trim(body), '') <> '' or attachment_url is not null)
);

create table if not exists public.message_reads (
  message_id bigint not null references public.messages (id) on delete cascade,
  profile_id uuid not null references public.profiles (id),
  read_at timestamptz not null default now(),
  primary key (message_id, profile_id)
);

create index if not exists messages_scope_idx on public.messages (scope);
create index if not exists messages_context_idx on public.messages (context_type, context_id);
create index if not exists messages_recipient_idx on public.messages (recipient_id);

-- Encapsulates "who is allowed to send a message shaped like this" so the
-- same rule can be reused by the INSERT policy without duplicating logic.
-- Mirrors the requirements: admin -> anyone/announcements; teacher ->
-- students or a whole level; student -> teachers only, never another
-- student, plus opt-in context discussions (lesson/homework/exam/
-- certificate) they actually have access to.
create or replace function public.can_send_message(
  p_scope text, p_recipient_id uuid, p_level text, p_context_type text, p_context_id bigint
) returns boolean
language plpgsql
stable security definer
set search_path = 'public'
as $$
declare
  my_role public.user_role;
  recipient_role public.user_role;
begin
  select role into my_role from public.profiles where id = auth.uid();
  if my_role is null then
    return false;
  end if;

  if p_scope = 'announcement' then
    return my_role = 'administrator';
  end if;

  if p_scope = 'level' then
    return my_role in ('administrator', 'teacher') and p_level is not null;
  end if;

  if p_scope = 'direct' then
    if p_recipient_id is null or p_recipient_id = auth.uid() then
      return false;
    end if;
    select role into recipient_role from public.profiles where id = p_recipient_id;
    if my_role = 'administrator' then
      return recipient_role is not null;
    elsif my_role = 'teacher' then
      return recipient_role = 'student';
    elsif my_role = 'student' then
      return recipient_role = 'teacher';
    end if;
    return false;
  end if;

  if p_scope = 'context' then
    if my_role in ('administrator', 'teacher') then
      return p_context_type is not null and p_context_id is not null;
    end if;
    -- student: only lessons explicitly opened for discussion, or
    -- homework/exams assigned to their level, or their own certificates.
    if p_context_type = 'lesson' then
      return exists (
        select 1 from public.lessons l join public.students s on s.profile_id = auth.uid()
        where l.id = p_context_id and l.discussion_enabled and (l.level is null or l.level = s.level)
      );
    elsif p_context_type = 'homework' then
      return exists (
        select 1 from public.homework h join public.students s on s.profile_id = auth.uid()
        where h.id = p_context_id and (h.level is null or h.level = s.level)
      );
    elsif p_context_type = 'exam' then
      return exists (
        select 1 from public.exams e join public.students s on s.profile_id = auth.uid()
        where e.id = p_context_id and (e.level is null or e.level = s.level)
      );
    elsif p_context_type = 'certificate' then
      return exists (
        select 1 from public.certificates c join public.students s on s.profile_id = auth.uid()
        where c.id = p_context_id and c.student_id = s.id
      );
    end if;
    return false;
  end if;

  return false;
end;
$$;

-- Read visibility. Broader than send-eligibility where it needs to be -
-- e.g. once a direct message exists, both sender and recipient can always
-- read it regardless of role, and teachers can see every context
-- discussion (to help answer questions) even though only some of those
-- are ones a teacher could have started.
create or replace function public.can_read_message(
  p_sender_id uuid, p_scope text, p_recipient_id uuid, p_level text, p_context_type text, p_context_id bigint
) returns boolean
language plpgsql
stable security definer
set search_path = 'public'
as $$
declare
  my_role public.user_role;
begin
  select role into my_role from public.profiles where id = auth.uid();
  if my_role is null then
    return false;
  end if;
  if my_role = 'administrator' then
    return true;
  end if;

  if p_scope = 'announcement' then
    return true;
  end if;

  if p_scope = 'direct' then
    return auth.uid() = p_sender_id or auth.uid() = p_recipient_id;
  end if;

  if p_scope = 'level' then
    if my_role = 'teacher' then
      return true;
    end if;
    return exists (select 1 from public.students s where s.profile_id = auth.uid() and s.level = p_level);
  end if;

  if p_scope = 'context' then
    if my_role = 'teacher' then
      return true;
    end if;
    return public.can_send_message(p_scope, p_recipient_id, p_level, p_context_type, p_context_id);
  end if;

  return false;
end;
$$;

-- Left at the default PUBLIC execute grant, same as is_admin()/is_teacher()
-- elsewhere in this schema - both functions already return false/deny for
-- anon (my_role is null when auth.uid() is null), so this matches existing
-- convention rather than introducing a new one.

alter table public.messages enable row level security;
alter table public.message_reads enable row level security;

drop policy if exists messages_select on public.messages;
create policy messages_select on public.messages for select
  using (public.can_read_message(sender_id, scope, recipient_id, level, context_type, context_id));

drop policy if exists messages_insert on public.messages;
create policy messages_insert on public.messages for insert
  with check (
    sender_id = auth.uid()
    and public.can_send_message(scope, recipient_id, level, context_type, context_id)
  );

-- Only administrators delete messages (moderation), matching "Administrator:
-- can delete inappropriate messages" - no self-delete for other roles.
drop policy if exists messages_delete_admin on public.messages;
create policy messages_delete_admin on public.messages for delete using (is_admin());

drop policy if exists message_reads_own on public.message_reads;
create policy message_reads_own on public.message_reads for all
  using (profile_id = auth.uid())
  with check (
    profile_id = auth.uid()
    and exists (
      select 1 from public.messages m
      where m.id = message_id
        and public.can_read_message(m.sender_id, m.scope, m.recipient_id, m.level, m.context_type, m.context_id)
    )
  );

-- Students need to see teacher profiles to pick who to message; teachers/
-- admin already see every profile via existing policies. Only role/name/
-- email are exposed by this, same fields already visible via the existing
-- profiles_select_admin_all / profiles_select_teacher_all policies.
drop policy if exists profiles_select_teachers on public.profiles;
create policy profiles_select_teachers on public.profiles for select
  using (role = 'teacher');

-- ============================================================
-- Lesson discussion opt-in
-- ============================================================

alter table public.lessons add column if not exists discussion_enabled boolean not null default false;

-- ============================================================
-- Exam files, deadlines, and student answer submission
-- ============================================================

alter table public.exams add column if not exists deadline timestamptz;
alter table public.exams add column if not exists file_url text;
alter table public.exams add column if not exists file_name text;
alter table public.exams add column if not exists file_type text;

alter table public.exam_scores alter column score drop not null;
alter table public.exam_scores add column if not exists answer_file_url text;
alter table public.exam_scores add column if not exists answer_file_name text;
alter table public.exam_scores add column if not exists submitted_at timestamptz;

-- A student may create/update their own exam_scores row to attach an
-- answer file, but only while it's still ungraded (score is null) - and
-- can never set a score themselves (with check also requires score is
-- null on the row they're writing). Once a teacher/admin grades it,
-- these policies stop matching and only the existing admin/teacher "for
-- all" policies apply.
drop policy if exists exam_scores_student_submit on public.exam_scores;
create policy exam_scores_student_submit on public.exam_scores for insert
  with check (
    exists (select 1 from public.students s where s.id = exam_scores.student_id and s.profile_id = auth.uid())
    and score is null
  );

drop policy if exists exam_scores_student_update_own on public.exam_scores;
create policy exam_scores_student_update_own on public.exam_scores for update
  using (
    exists (select 1 from public.students s where s.id = exam_scores.student_id and s.profile_id = auth.uid())
    and score is null
  )
  with check (
    exists (select 1 from public.students s where s.id = exam_scores.student_id and s.profile_id = auth.uid())
    and score is null
  );

-- ============================================================
-- Homework files, student submission, and teacher feedback
-- ============================================================

alter table public.homework add column if not exists file_url text;
alter table public.homework add column if not exists file_name text;
alter table public.homework add column if not exists file_type text;

alter table public.homework_status add column if not exists answer_file_url text;
alter table public.homework_status add column if not exists answer_file_name text;
alter table public.homework_status add column if not exists feedback text;
alter table public.homework_status add column if not exists submitted_at timestamptz;

-- Same shape as the exam_scores policies above: a student can insert/
-- update their own row while it isn't graded yet, can only move it to
-- 'Assigned' or 'Submitted' (never 'Graded'), and can never write a score
-- or feedback themselves.
drop policy if exists homework_status_student_submit on public.homework_status;
create policy homework_status_student_submit on public.homework_status for insert
  with check (
    exists (select 1 from public.students s where s.id = homework_status.student_id and s.profile_id = auth.uid())
    and status in ('Assigned', 'Submitted')
    and score is null
    and feedback is null
  );

drop policy if exists homework_status_student_update_own on public.homework_status;
create policy homework_status_student_update_own on public.homework_status for update
  using (
    exists (select 1 from public.students s where s.id = homework_status.student_id and s.profile_id = auth.uid())
    and status <> 'Graded'
  )
  with check (
    exists (select 1 from public.students s where s.id = homework_status.student_id and s.profile_id = auth.uid())
    and status in ('Assigned', 'Submitted')
    and score is null
    and feedback is null
  );

-- ============================================================
-- Certificate template (admin-uploaded, used by every generated
-- certificate PDF instead of the built-in design once set)
-- ============================================================

create table if not exists public.certificate_template (
  id boolean primary key default true check (id),
  file_url text,
  file_name text,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles (id)
);

insert into public.certificate_template (id) values (true) on conflict (id) do nothing;

alter table public.certificate_template enable row level security;

drop policy if exists certificate_template_read on public.certificate_template;
create policy certificate_template_read on public.certificate_template for select
  using (auth.uid() is not null);

drop policy if exists certificate_template_admin_write on public.certificate_template;
create policy certificate_template_admin_write on public.certificate_template for all
  using (is_admin())
  with check (is_admin());
