-- Phase 10: a centralized file manager. One catalog table for files that
-- aren't already tied to a specific record via their own upload flow
-- (exams/homework already have their own file_url columns from migration
-- 0009 and keep working exactly as before) - this fills the gap for
-- lesson materials (PDFs/PowerPoints), certificate template assets, and
-- general images/videos that aren't naturally "owned" by one row
-- elsewhere.
--
-- Reuses the private 'attachments' Storage bucket and its policies from
-- migration 0009 as-is - no new storage policy needed, uploads just use a
-- 'library/' path prefix within the same bucket.
--
-- RLS mirrors the exact pattern already used for lessons/exams/homework
-- in migration 0005 (admin_all / teacher_all via the existing is_admin()/
-- is_teacher() helpers) rather than inventing new logic - kept
-- deliberately simple and low-risk since Supabase tooling was unavailable
-- to dry-run this migration live before opening the PR (see PR
-- description). Read access is admin/teacher only for now, since no
-- student-facing page reads this table in this PR - broadening it later
-- is a one-line policy change if a student view is ever added.

create table if not exists public.files (
  id bigint generated by default as identity primary key,
  category text not null check (category in ('lesson', 'homework', 'exam', 'certificate_template', 'image', 'video', 'other')),
  file_path text not null,
  file_name text not null,
  file_type text,
  file_size bigint,
  description text,
  uploaded_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

create index if not exists files_category_idx on public.files (category);

alter table public.files enable row level security;

drop policy if exists files_admin_all on public.files;
create policy files_admin_all on public.files for all using (is_admin()) with check (is_admin());

drop policy if exists files_teacher_all on public.files;
create policy files_teacher_all on public.files for all using (is_teacher()) with check (is_teacher());
