-- H4: optional lesson link on homework, and a proper multi-file
-- submission table (up to 5 images per submission) instead of hacking
-- multiple URLs into homework_status.answer_file_url.
--
-- lesson_id is nullable and ON DELETE SET NULL: deleting an old lesson
-- must never delete or block-delete the homework that referenced it,
-- only unlink it. The one existing homework row (id 17) and every future
-- standalone (no-lesson) assignment stay valid with lesson_id null.
--
-- homework_status.answer_file_url/answer_file_name are left exactly as
-- they are - legacy columns for any pre-H4 single-file submission, never
-- written to by the new flow. There are 0 existing homework_status rows
-- in production, so there is nothing to backfill or migrate.

alter table public.homework add column if not exists lesson_id bigint references public.lessons(id) on delete set null;

create table if not exists public.homework_submission_files (
  id bigint generated by default as identity primary key,
  homework_id bigint not null references public.homework(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  file_url text not null,
  file_name text,
  file_type text,
  position smallint not null default 0,
  created_at timestamptz not null default now(),
  unique (homework_id, student_id, file_url)
);

create index if not exists homework_submission_files_hw_student_idx
  on public.homework_submission_files (homework_id, student_id);

alter table public.homework_submission_files enable row level security;

-- Server-side 5-file cap, not just a UI limit: a student may add a file
-- only to their own homework_status row, only while it's ungraded (same
-- gate as every other student write in this schema), and only while
-- fewer than 5 rows already exist for that (homework_id, student_id)
-- pair. "No row yet" counts as ungraded (a student submitting for the
-- first time has no homework_status row at all until this same request
-- also upserts one).
create or replace function public.can_add_homework_submission_file(p_homework_id bigint, p_student_id bigint)
returns boolean
language sql
stable
security definer
set search_path = 'public'
as $$
  select
    public.is_own_student(p_student_id)
    and not exists (
      select 1 from public.homework_status hs
      where hs.homework_id = p_homework_id
        and hs.student_id = p_student_id
        and hs.score is not null
    )
    and (
      select count(*) from public.homework_submission_files f
      where f.homework_id = p_homework_id
        and f.student_id = p_student_id
    ) < 5
$$;

revoke execute on function public.can_add_homework_submission_file(bigint, bigint) from public;
grant execute on function public.can_add_homework_submission_file(bigint, bigint) to authenticated;

drop policy if exists homework_submission_files_admin_all on public.homework_submission_files;
create policy homework_submission_files_admin_all on public.homework_submission_files for all
  using (is_admin()) with check (is_admin());

drop policy if exists homework_submission_files_teacher_all on public.homework_submission_files;
create policy homework_submission_files_teacher_all on public.homework_submission_files for all
  using (is_teacher()) with check (is_teacher());

drop policy if exists homework_submission_files_self_read on public.homework_submission_files;
create policy homework_submission_files_self_read on public.homework_submission_files for select
  using (is_own_student(student_id));

drop policy if exists homework_submission_files_student_insert on public.homework_submission_files;
create policy homework_submission_files_student_insert on public.homework_submission_files for insert
  with check (public.can_add_homework_submission_file(homework_id, student_id));

-- A student may remove one of their own already-uploaded images (e.g.
-- to replace it) only while still ungraded - same "cannot touch a graded
-- submission" rule as everything else. No update policy: an image is
-- either present or removed, never edited in place.
drop policy if exists homework_submission_files_student_delete on public.homework_submission_files;
create policy homework_submission_files_student_delete on public.homework_submission_files for delete
  using (
    is_own_student(student_id)
    and not exists (
      select 1 from public.homework_status hs
      where hs.homework_id = homework_submission_files.homework_id
        and hs.student_id = homework_submission_files.student_id
        and hs.score is not null
    )
  );

-- Storage read: is_own_homework_answer (0039) already gates the
-- 'homework-answers' folder in attachments_read and only matched
-- homework_status.answer_file_url. Extending its body (rather than
-- adding a new function + a new policy branch) means attachments_read
-- itself needs no changes at all - it already calls this function.
create or replace function public.is_own_homework_answer(p_answer_file_url text)
returns boolean
language sql
stable
security definer
set search_path = 'public'
as $$
  select exists (
    select 1
    from public.homework_status hs
    where public.is_own_student(hs.student_id)
      and hs.answer_file_url = p_answer_file_url
  )
  or exists (
    select 1
    from public.homework_submission_files f
    where public.is_own_student(f.student_id)
      and f.file_url = p_answer_file_url
  );
$$;

-- Insert/update of 'homework-answers/*' objects is already scoped by
-- can_write_homework_answer (0039) to the uploader's own
-- {student_id} path prefix, independent of which DB table eventually
-- records the upload - no storage policy change needed for writes.
