-- Payment system redesign, step 1 of N: the ledger table only. No frontend,
-- no derivation function, and no changes to public.payments in this
-- migration - that table is left fully intact as the compatibility layer
-- until every consumer (Payments.jsx, Reports.jsx, Dashboard.jsx) has been
-- migrated over, per the agreed plan.
--
-- Source of truth going forward: append-only transaction rows, not a
-- mutable per-month boolean. Nothing here stores a value that a later
-- function can derive (balance, status, next_due_date) - see the design
-- notes for the rolling-balance model this ledger is meant to support.
--
-- transaction_type/payment_method use check constraints, not native enums,
-- so adding a value later (e.g. 'discount', 'scholarship', 'refund') is a
-- single `alter table ... drop constraint / add constraint` migration, not
-- an enum-type alter. 'discount' is deliberately not in the list yet -
-- postponed per plan, not forgotten.
--
-- amount is constrained positive for now: every supported transaction_type
-- (first_partial, monthly, advance, extra) is money coming in. A future
-- discount/refund type will need signed amounts or a separate sign column -
-- that's a deliberate decision for whenever that type is actually added,
-- not something to guess at here.
--
-- covers_period_start/end are nullable: advance and extra payments aren't
-- always attributable to one specific billing period at the time they're
-- recorded.
--
-- created_by is nullable only to accommodate the historical backfill from
-- public.payments (a future migration) - that table never recorded who
-- toggled the flag. Every transaction recorded through the new UI will
-- have it populated at the application layer.

create table if not exists public.payment_transactions (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students (id) on delete cascade,
  amount numeric not null check (amount > 0),
  transaction_type text not null check (transaction_type in ('first_partial', 'monthly', 'advance', 'extra')),
  payment_method text check (payment_method in ('cash', 'bank_transfer', 'click', 'payme', 'other')),
  covers_period_start date,
  covers_period_end date,
  paid_at timestamptz not null default now(),
  reference_number text,
  notes text,
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

create index if not exists payment_transactions_student_paid_at_idx
  on public.payment_transactions (student_id, paid_at);

create index if not exists payment_transactions_student_period_idx
  on public.payment_transactions (student_id, covers_period_start);

alter table public.payment_transactions enable row level security;

-- Mirrors payments_admin_all / payments_self_read exactly (0003, hardened
-- in 0028 to route self-read through is_own_student() rather than a raw
-- students subquery - see that migration's comment for why the raw form
-- breaks with "permission denied for table students"). Same shape, same
-- callers, nothing weakened or widened relative to the table this replaces.
drop policy if exists payment_transactions_admin_all on public.payment_transactions;
create policy payment_transactions_admin_all on public.payment_transactions
  for all using (is_admin()) with check (is_admin());

drop policy if exists payment_transactions_self_read on public.payment_transactions;
create policy payment_transactions_self_read on public.payment_transactions
  for select using (public.is_own_student(payment_transactions.student_id));
