-- Payment reminders, phase 1: infrastructure only - no sending. Adds the
-- pieces the "Send" button (still disabled) will need once Telegram
-- delivery is built: somewhere to link a student to a Telegram account,
-- and a log so a reminder can never be double-sent. Does not touch
-- get_student_payment_status() or any billing/period math - reminder
-- cadence is layered on top of that function's output, never reimplemented.

alter table public.students
  add column if not exists telegram_chat_id text;

create table if not exists public.payment_reminders (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students (id) on delete cascade,
  reminder_type text not null check (reminder_type in ('due_soon', 'overdue')),
  deadline_date date not null,
  message_text text not null,
  sent_at timestamptz not null default now(),
  sent_by uuid references public.profiles (id)
);

-- One due_soon reminder and one overdue reminder per student per deadline -
-- matches the confirmed rule (single overdue notice, no repeats) and makes
-- "already sent" a unique-constraint check rather than app-level logic that
-- could be gotten wrong or skipped by a future caller.
create unique index if not exists payment_reminders_dedupe
  on public.payment_reminders (student_id, reminder_type, deadline_date);

alter table public.payment_reminders enable row level security;

create policy "admins manage payment_reminders" on public.payment_reminders
  for all
  using (is_admin())
  with check (is_admin());

-- Return type changed from the 0067 version (added telegram_chat_id,
-- already_sent), so the old function has to be dropped first - CREATE OR
-- REPLACE cannot change OUT-parameter row shape.
drop function if exists public.get_payment_reminder_candidates();

-- due_soon window tightened from get_student_payment_status()'s 5-day
-- internal threshold to the confirmed 3-day reminder lead time, and each
-- candidate is now cross-checked against payment_reminders so an already
-- notified student/deadline pair is excluded rather than re-shown.
create or replace function public.get_payment_reminder_candidates()
returns table(
  student_id bigint,
  student_name text,
  status text,
  next_due_date date,
  next_amount_due numeric,
  days integer,
  telegram_chat_id text,
  already_sent boolean
)
language plpgsql
stable
as $$
declare
  v_today date := (now() at time zone 'Asia/Tashkent')::date;
  v_due_soon_lead_days constant integer := 3;
  rec record;
  st record;
  v_reminder_type text;
begin
  if not is_admin() then
    raise exception 'Unauthorized';
  end if;

  for rec in select s.id, s.real_name, s.telegram_chat_id from public.students s where s.status = 'Active'
  loop
    select * into st from public.get_student_payment_status(rec.id);

    if st.status = 'overdue' then
      v_reminder_type := 'overdue';
    elsif st.status = 'due_soon' and (st.next_due_date - v_today) <= v_due_soon_lead_days then
      v_reminder_type := 'due_soon';
    else
      v_reminder_type := null;
    end if;

    if v_reminder_type is not null then
      student_id := rec.id;
      student_name := rec.real_name;
      status := st.status;
      next_due_date := st.next_due_date;
      next_amount_due := st.next_amount_due;
      days := abs(st.next_due_date - v_today);
      telegram_chat_id := rec.telegram_chat_id;
      already_sent := exists(
        select 1 from public.payment_reminders pr
        where pr.student_id = rec.id
          and pr.reminder_type = v_reminder_type
          and pr.deadline_date = st.next_due_date
      );
      return next;
    end if;
  end loop;
end;
$$;

revoke execute on function public.get_payment_reminder_candidates() from public;
grant execute on function public.get_payment_reminder_candidates() to authenticated;

-- Column list changed (telegram_chat_id inserted), so recreate rather than
-- replace - CREATE OR REPLACE VIEW cannot rename/reorder existing columns.
drop view if exists public.students_view;

create or replace view public.students_view
with (security_invoker = true) as
select
  id,
  profile_id,
  real_name,
  english_name,
  level,
  phone,
  parent_phone,
  telegram_chat_id,
  join_date,
  payment_deadline,
  case when is_admin() then monthly_fee else null end as monthly_fee,
  status,
  notes,
  group_name,
  points,
  created_at
from public.students;

grant select on public.students_view to authenticated;
