-- Telegram auto-connect, foundation only - no webhook function yet.
-- Payment reminders, billing, and get_student_payment_status are
-- untouched by this migration.

-- Test Student (id 44) was holding the admin's own chat ID for the
-- payment-reminder delivery test; clearing it so the unique constraint
-- below can be added cleanly and the fixture stays reusable.
update public.students set telegram_chat_id = null where id = 44;

-- One Telegram account can only ever be linked to one student. Nullable
-- columns allow unlimited nulls under a unique constraint in Postgres, so
-- every still-unlinked student is unaffected.
alter table public.students
  add constraint students_telegram_chat_id_unique unique (telegram_chat_id);

-- Holds webhook conversation state across serverless invocations (no
-- in-memory session is possible) and doubles as the security audit log
-- for every link attempt - matched, rejected, or rate-limited.
create table public.telegram_link_requests (
  id bigint generated by default as identity primary key,
  chat_id text not null,
  searched_name text not null,
  matched_student_id bigint references public.students (id),
  status text not null check (status in ('pending', 'confirmed', 'rejected', 'blocked', 'already_linked')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index telegram_link_requests_chat_id_idx on public.telegram_link_requests (chat_id, created_at);

alter table public.telegram_link_requests enable row level security;

-- Admin-only read for auditing. No insert/update policy for
-- authenticated/anon - only the webhook (service role, bypasses RLS)
-- writes here; this is deliberate, not an oversight.
create policy "admins read telegram_link_requests" on public.telegram_link_requests
  for select using (is_admin());
