-- Reconstructed historical migration. The achievement-engine layer
-- (achievement_definitions/student_achievements/student_metric_snapshots
-- tables, bump_student_metric, evaluate_achievements/_evaluate_achievements_internal
-- functions) was created directly in production and never committed as a
-- migration file - discovered during Gaming Release Validation (2026-08-16)
-- when a fresh local database could not complete any game round, since
-- submit_game_round (first introduced in 0111) has called
-- bump_student_metric since day one. Rebuilt verbatim from the live
-- production schema via read-only introspection (pg_get_functiondef,
-- information_schema), not invented. Placed at 0105 (the first unused
-- local slot before 0111) because it is a dependency of every game
-- migration from 0111 onward, not merely of the achievement UI.
--
-- Table shapes and RLS policies for achievement_definitions/
-- student_achievements/student_metric_snapshots match the untracked
-- reconciliation file supabase/migrations/PROD_RECONCILED_achievement_engine_schema.sql
-- (written by an earlier session, 2026-08-16) - that file's tables are
-- duplicated here with `if not exists`/`drop policy if exists` guards so
-- either file applying first is safe; both remain in the repo since
-- filenames are independent.
--
-- evaluate_achievements below is deliberately the already-hardened C1/H1
-- version (caller-authorization check, matching what
-- 0126b_secure_achievement_evaluator.sql intends later in the chain) so a
-- fresh database is never exposed to the earlier vulnerable variant even
-- momentarily. No point-awarding behavior is introduced:
-- _evaluate_achievements_internal still only unlocks badges, matching the
-- owner-paused automatic-point-award state (see migration 0135).

create table if not exists public.achievement_definitions (
  id bigint generated by default as identity primary key,
  key text not null unique,
  name text not null,
  description text,
  icon text,
  category text not null default 'achievement'
    check (category in ('achievement','badge','streak','milestone','mission','seasonal')),
  trigger_type text not null
    check (trigger_type in ('immediate_event','threshold','scheduled','streak','manual')),
  rule_config jsonb not null default '{}'::jsonb,
  bonus_points numeric not null default 0,
  rarity text not null default 'common' check (rarity in ('common','rare','epic')),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.achievement_definitions enable row level security;

drop policy if exists achievement_definitions_admin_all on public.achievement_definitions;
create policy achievement_definitions_admin_all on public.achievement_definitions for all
  using (is_admin()) with check (is_admin());

drop policy if exists achievement_definitions_read_active on public.achievement_definitions;
create policy achievement_definitions_read_active on public.achievement_definitions for select
  using (active);

create table if not exists public.student_achievements (
  student_id bigint not null references public.students(id) on delete cascade,
  achievement_id bigint not null references public.achievement_definitions(id) on delete cascade,
  earned_at timestamptz not null default now(),
  awarded_by uuid references public.profiles(id),
  point_transaction_id bigint references public.point_transactions(id),
  primary key (student_id, achievement_id)
);

alter table public.student_achievements enable row level security;

drop policy if exists student_achievements_admin_all on public.student_achievements;
create policy student_achievements_admin_all on public.student_achievements for all
  using (is_admin()) with check (is_admin());

drop policy if exists student_achievements_self_select on public.student_achievements;
create policy student_achievements_self_select on public.student_achievements for select
  using (public.is_own_student(student_id));

drop policy if exists student_achievements_teacher_select on public.student_achievements;
create policy student_achievements_teacher_select on public.student_achievements for select
  using (
    is_teacher() and exists (
      select 1 from public.students s
      join public.teacher_group_assignments tga
        on tga.teacher_id = auth.uid() and tga.level = s.level
      where s.id = student_achievements.student_id
    )
  );

drop policy if exists student_achievements_teacher_insert on public.student_achievements;
create policy student_achievements_teacher_insert on public.student_achievements for insert
  with check (
    is_teacher() and exists (
      select 1 from public.students s
      join public.teacher_group_assignments tga
        on tga.teacher_id = auth.uid() and tga.level = s.level
      where s.id = student_achievements.student_id
    )
  );

create table if not exists public.student_metric_snapshots (
  student_id bigint not null references public.students(id) on delete cascade,
  metric_key text not null,
  value numeric not null default 0,
  updated_at timestamptz not null default now(),
  primary key (student_id, metric_key)
);

alter table public.student_metric_snapshots enable row level security;

drop policy if exists student_metric_snapshots_self_select on public.student_metric_snapshots;
create policy student_metric_snapshots_self_select on public.student_metric_snapshots for select
  using (public.is_own_student(student_id));

drop policy if exists student_metric_snapshots_admin_teacher_select on public.student_metric_snapshots;
create policy student_metric_snapshots_admin_teacher_select on public.student_metric_snapshots for select
  using (is_admin() or is_teacher());

insert into public.achievement_definitions
  (id, key, name, description, icon, category, trigger_type, rule_config, bonus_points, rarity, active, sort_order)
values
  (1, 'first_lesson', 'First Lesson', 'Completed your first lesson', '📘', 'achievement', 'immediate_event', '{"op": ">=", "value": 1, "metric": "lessons_completed"}', 5, 'common', true, 10),
  (2, 'first_practice', 'First Practice', 'Submitted your first lesson practice', '✏️', 'achievement', 'immediate_event', '{"op": ">=", "value": 1, "metric": "practice_submitted"}', 5, 'common', true, 20),
  (3, 'first_attendance', 'Present and Accounted For', 'Marked present for the first time', '✅', 'achievement', 'immediate_event', '{"op": ">=", "value": 1, "metric": "attendance_present"}', 5, 'common', true, 30),
  (4, 'ten_lessons', 'Lesson Regular', 'Completed 10 lessons', '📗', 'milestone', 'threshold', '{"op": ">=", "value": 10, "metric": "lessons_completed"}', 20, 'rare', true, 40),
  (5, 'twenty_five_lessons', 'Lesson Veteran', 'Completed 25 lessons', '📚', 'milestone', 'threshold', '{"op": ">=", "value": 25, "metric": "lessons_completed"}', 50, 'epic', true, 50),
  (6, 'ten_practices', 'Practice Habit', 'Submitted 10 lesson practices', '📝', 'milestone', 'threshold', '{"op": ">=", "value": 10, "metric": "practice_submitted"}', 20, 'rare', true, 60),
  (7, 'twenty_five_attendance', 'Reliable Attendee', 'Marked present 25 times', '🗓️', 'milestone', 'threshold', '{"op": ">=", "value": 25, "metric": "attendance_present"}', 20, 'rare', true, 70),
  (8, 'hundred_points', 'Century Club', 'Reached 100 points', '💯', 'milestone', 'threshold', '{"op": ">=", "value": 100, "metric": "total_points"}', 15, 'rare', true, 80),
  (9, 'five_hundred_points', 'High Achiever', 'Reached 500 points', '🏅', 'milestone', 'threshold', '{"op": ">=", "value": 500, "metric": "total_points"}', 40, 'epic', true, 90),
  (10, 'teacher_recognition', 'Teacher''s Star', 'Recognized by a teacher for outstanding effort', '⭐', 'badge', 'manual', '{}', 0, 'epic', true, 100)
on conflict (id) do nothing;

select setval('public.achievement_definitions_id_seq', 10, true);

create or replace function public.bump_student_metric(p_student_id bigint, p_metric_key text, p_delta numeric)
returns void
language plpgsql
security definer
set search_path to 'public'
as $function$
begin
  insert into public.student_metric_snapshots (student_id, metric_key, value, updated_at)
  values (p_student_id, p_metric_key, p_delta, now())
  on conflict (student_id, metric_key)
  do update set value = public.student_metric_snapshots.value + excluded.value, updated_at = now();
end;
$function$;

revoke execute on function public.bump_student_metric(bigint, text, numeric) from public;
grant execute on function public.bump_student_metric(bigint, text, numeric) to authenticated;

create or replace function public._evaluate_achievements_internal(p_student_id bigint)
returns void
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_level text;
  v_points numeric;
  r record;
  v_qualifies boolean;
  v_inserted integer;
begin
  select level, points into v_level, v_points from public.students where id = p_student_id;
  if v_level is null then
    return;
  end if;

  for r in
    select d.* from public.achievement_definitions d
    where d.active
      and d.trigger_type in ('immediate_event', 'threshold')
      and not exists (
        select 1 from public.student_achievements sa
        where sa.student_id = p_student_id and sa.achievement_id = d.id
      )
  loop
    if r.rule_config->>'metric' = 'total_points' then
      v_qualifies := v_points >= (r.rule_config->>'value')::numeric;
    else
      v_qualifies := exists (
        select 1 from public.student_metric_snapshots m
        where m.student_id = p_student_id
          and m.metric_key = r.rule_config->>'metric'
          and m.value >= (r.rule_config->>'value')::numeric
      );
    end if;

    if not v_qualifies then
      continue;
    end if;

    insert into public.student_achievements (student_id, achievement_id)
    values (p_student_id, r.id)
    on conflict (student_id, achievement_id) do nothing;
    get diagnostics v_inserted = row_count;

    -- Point-award block intentionally removed (owner request, 2026-08-15):
    -- badges still unlock above, but no point_transactions row is
    -- created for them while automatic point awards are paused.
  end loop;
end;
$function$;

create or replace function public.evaluate_achievements(p_student_id bigint)
returns void
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_level text;
  v_authorized_caller boolean;
begin
  select level into v_level from public.students where id = p_student_id;
  if v_level is null then
    return;
  end if;

  v_authorized_caller := public.is_own_student(p_student_id)
    or is_admin()
    or (is_teacher() and exists (
      select 1 from public.teacher_group_assignments tga
      where tga.teacher_id = auth.uid() and tga.level = v_level
    ));

  if not v_authorized_caller then
    return;
  end if;

  perform public._evaluate_achievements_internal(p_student_id);
end;
$function$;

revoke execute on function public.evaluate_achievements(bigint) from public;
grant execute on function public.evaluate_achievements(bigint) to authenticated;
