-- Ranking V2 Phase 5/6: class_group + class_session schema.
--
-- Design: docs/ranking-v2-class-session-design.md (approved 2026-08-15).
-- Session identity is the teaching GROUP, not the awarding teacher —
-- awarded_by on point_transactions stays metadata about who awarded
-- points, never part of what identifies the class.
--
-- Seed data (approved 2026-08-15, based on real-world confirmation from
-- Dave, not inferred from point_transactions — the audit found no
-- reliable group signal anywhere in the existing data): exactly one
-- class_group per current level (A, A1, B, C). The schema places no
-- constraint capping groups-per-level at one; splitting a level later
-- is a plain INSERT + student reassignment, not a migration.
--
-- This migration creates the two new tables, RLS mirroring the
-- 0131-0136 teacher-level-scope pattern, and the four seed rows only.
-- It does NOT touch point_transactions.class_session_id (separate
-- migration, since backfill policy needs its own review), does NOT
-- add class_session_id anywhere yet, and does NOT change any existing
-- ranking RPC. NOT applied — for review only.

create table public.class_group (
  id bigint generated by default as identity primary key,
  level text not null check (level in ('A','A1','B','C')),
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

comment on table public.class_group is
  'A real teaching group within a level. Session identity is keyed on '
  'this, not on the teacher who happens to award points into it.';

create table public.class_session (
  id bigint generated by default as identity primary key,
  class_group_id bigint not null references public.class_group(id),
  session_date date not null,
  opened_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  unique (class_group_id, session_date)
);

comment on table public.class_session is
  'One meeting of a class_group on a specific date. Created only by an '
  'explicit open action -- never inferred from a point award.';

create index class_session_group_date_idx
  on public.class_session (class_group_id, session_date);

alter table public.class_group enable row level security;
alter table public.class_session enable row level security;

-- Admin: full access, mirrors existing pt_admin_* pattern.
create policy class_group_admin_all on public.class_group
  for all using (is_admin()) with check (is_admin());

create policy class_session_admin_all on public.class_session
  for all using (is_admin()) with check (is_admin());

-- Teacher: scoped to levels they're assigned via teacher_group_assignments,
-- mirroring 0131-0136 exactly.
create policy class_group_teacher_all on public.class_group
  for all
  using (
    is_teacher()
    and exists (
      select 1 from teacher_group_assignments tga
      where tga.level = class_group.level
        and tga.teacher_id = auth.uid()
    )
  )
  with check (
    is_teacher()
    and exists (
      select 1 from teacher_group_assignments tga
      where tga.level = class_group.level
        and tga.teacher_id = auth.uid()
    )
  );

create policy class_session_teacher_all on public.class_session
  for all
  using (
    is_teacher()
    and exists (
      select 1
      from class_group cg
      join teacher_group_assignments tga
        on tga.level = cg.level
       and tga.teacher_id = auth.uid()
      where cg.id = class_session.class_group_id
    )
  )
  with check (
    is_teacher()
    and exists (
      select 1
      from class_group cg
      join teacher_group_assignments tga
        on tga.level = cg.level
       and tga.teacher_id = auth.uid()
      where cg.id = class_session.class_group_id
    )
  );

-- Student: read-only, scoped to their own current level -- so they can
-- see which group/sessions their Class Points view is drawing from.
create policy class_group_student_select on public.class_group
  for select
  using (
    exists (
      select 1 from students s
      where s.profile_id = auth.uid()
        and s.level = class_group.level
    )
  );

create policy class_session_student_select on public.class_session
  for select
  using (
    exists (
      select 1
      from class_group cg
      join students s on s.level = cg.level
      where cg.id = class_session.class_group_id
        and s.profile_id = auth.uid()
    )
  );

-- Seed: one group per level, current real-world state (2026-08-15).
-- No fabricated names -- level name doubles as group name since there
-- is exactly one group per level today.
insert into public.class_group (level, name) values
  ('A',  'A'),
  ('A1', 'A1'),
  ('B',  'B'),
  ('C',  'C');
