-- Grounded content for the three game_content_bank games (Sentence
-- Scramble, Grammar Battle, Word Detective): 100 validated items each,
-- replacing the old ~106 pre-grounding draft rows.
--
-- Grounding discipline (session-long process, not a batch generation):
-- every item uses ONLY the 15 grammar points explicitly confirmed as
-- already taught within Lessons 1-100 (to be, basic pronouns, present
-- simple, plurals, there is/are, simple future, imperatives, basic
-- questions, can-for-ability, prepositions, past simple regular/
-- irregular, present continuous, comparatives/superlatives, first
-- conditional). No item anywhere - blank, correction, or surrounding
-- text - uses ungrounded grammar (was/were, should/must/might, present
-- perfect, passive, relative clauses, second conditional all excluded).
--
-- Five cognitive-complexity stages (very_easy/easy/medium/hard/very_hard)
-- replace the old three-tier easy/medium/hard scale. Difficulty comes
-- from complexity and combination of KNOWN grammar, never from
-- introducing grammar a student hasn't reached - e.g. very_hard uses
-- multi-clause first-conditional combinations, not second conditional.
--
-- min_lesson_number gives every item real curriculum provenance: the
-- highest lesson number among the grammar points it uses (a combined
-- item is gated by its latest component). This column is NOT YET
-- enforced by the round-selection RPCs (get_sentence_scramble_round(),
-- get_word_detective_round(), get_grammar_battle_round() still do a
-- plain random pick) - that filtering, plus difficulty-stage selection,
-- is deliberately deferred to a separate migration so this one stays a
-- pure content+schema change, reviewable and revertible on its own.
--
-- Word Detective content was rebuilt once already within this same
-- session after a mechanical cross-game overlap check found ~94 of its
-- first 100 items were near-duplicates of Sentence Scramble sentences
-- (not the ~5 initially estimated) - the current 100 are the rewritten,
-- independently-scripted set, re-verified to bring that down to 9
-- residual low-similarity overlaps (comparable to the 13 that already
-- exist, unremarkably, between Sentence Scramble and Grammar Battle).
--
-- Every wrong_index value in Word Detective was computed programmatically
-- against the actual frontend tokenization
-- (sentence.replace(/[.?!]$/, '').split(' ')) rather than hand-counted -
-- manual counting had already produced 11 wrong indices earlier in this
-- session's review process.

-- Widen the difficulty check from the old 3-tier scale to the 5 stages
-- above. Unnamed inline check constraints get an auto-generated name
-- (Postgres default: <table>_<column>_check).
alter table public.game_content_bank
  drop constraint if exists game_content_bank_difficulty_check;

alter table public.game_content_bank
  add constraint game_content_bank_difficulty_check
  check (difficulty in ('very_easy', 'easy', 'medium', 'hard', 'very_hard'));

-- Curriculum provenance: the highest lesson number required by any
-- grammar point an item uses. Nullable - existing rows in other game
-- types (grammar_battle/sentence_scramble/word_detective rows inserted
-- below all populate it; this column has no meaning for other
-- game_content_bank consumers, of which there are currently none).
alter table public.game_content_bank
  add column if not exists min_lesson_number integer;

-- Replace the old pre-grounding draft content entirely - not deleting
-- student data, just the game's own draft question/sentence bank for
-- these three game types (24 sentence_scramble + 40 grammar_battle + 42
-- word_detective rows, all authored before the confirmed-grammar rule
-- existed).
delete from public.game_content_bank
where game_type in ('sentence_scramble', 'grammar_battle', 'word_detective');

insert into public.game_content_bank (game_type, difficulty, category, payload, min_lesson_number)
values
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"statement","tense":"foundations","words":["My","name","is","Anna"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"statement","tense":"foundations","words":["I","am","ten","years","old"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"statement","tense":"foundations","words":["They","are","my","classmates"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"statement","tense":"foundations","words":["She","is","happy"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"statement","tense":"foundations","words":["It","is","my","dog"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"statement","tense":"foundations","words":["He","drinks","milk","every","morning"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"statement","tense":"foundations","words":["We","eat","breakfast","at","home"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"statement","tense":"foundations","words":["My","cat","sleeps","all","day"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"statement","tense":"foundations","words":["I","have","two","brothers"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"statement","tense":"foundations","words":["There","are","five","books","here"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"statement","tense":"foundations","words":["There","is","a","cat","outside"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"statement","tense":"foundations","words":["I","will","call","you","later"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"statement","tense":"foundations","words":["She","will","visit","her","aunt"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"command","tense":"foundations","words":["Please","close","the","door"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"command","tense":"foundations","words":["Sit","down","and","listen"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"exclamation","tense":"foundations","words":["What","a","funny","dog"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"exclamation","tense":"foundations","words":["That","is","a","great","game"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"statement","tense":"foundations","words":["My","brother","is","very","tall"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"statement","tense":"foundations","words":["We","are","happy","today"]}'::jsonb, 1),
  ('sentence_scramble', 'very_easy', 'foundations', '{"type":"statement","tense":"foundations","words":["My","fish","swims","in","circles"]}'::jsonb, 1),
  ('sentence_scramble', 'easy', 'basic_questions', '{"type":"question","tense":"basic_questions","words":["Do","you","like","tea"]}'::jsonb, 6),
  ('sentence_scramble', 'easy', 'basic_questions', '{"type":"question","tense":"basic_questions","words":["Does","she","live","near","here"]}'::jsonb, 6),
  ('sentence_scramble', 'easy', 'basic_questions', '{"type":"question","tense":"basic_questions","words":["Where","do","you","live"]}'::jsonb, 6),
  ('sentence_scramble', 'easy', 'basic_questions', '{"type":"question","tense":"basic_questions","words":["What","time","does","school","start"]}'::jsonb, 6),
  ('sentence_scramble', 'easy', 'basic_questions', '{"type":"negative","tense":"basic_questions","words":["He","does","not","like","spinach"]}'::jsonb, 6),
  ('sentence_scramble', 'easy', 'basic_questions', '{"type":"negative","tense":"basic_questions","words":["I","do","not","have","a","pet"]}'::jsonb, 6),
  ('sentence_scramble', 'easy', 'can_ability', '{"type":"statement","tense":"can_ability","words":["My","brother","can","swim","very","well"]}'::jsonb, 10),
  ('sentence_scramble', 'easy', 'can_ability', '{"type":"statement","tense":"can_ability","words":["I","can","speak","two","languages"]}'::jsonb, 10),
  ('sentence_scramble', 'easy', 'can_ability', '{"type":"question","tense":"can_ability","words":["Can","you","help","me","please"]}'::jsonb, 10),
  ('sentence_scramble', 'easy', 'can_ability', '{"type":"statement","tense":"can_ability","words":["My","grandfather","can","still","dance"]}'::jsonb, 10),
  ('sentence_scramble', 'easy', 'prepositions', '{"type":"statement","tense":"prepositions","words":["The","cat","is","on","the","table"]}'::jsonb, 34),
  ('sentence_scramble', 'easy', 'prepositions', '{"type":"statement","tense":"prepositions","words":["We","meet","at","five","oclock"]}'::jsonb, 34),
  ('sentence_scramble', 'easy', 'prepositions', '{"type":"statement","tense":"prepositions","words":["My","keys","are","in","my","bag"]}'::jsonb, 34),
  ('sentence_scramble', 'easy', 'prepositions', '{"type":"statement","tense":"prepositions","words":["The","bus","stops","at","the","corner"]}'::jsonb, 34),
  ('sentence_scramble', 'easy', 'prepositions', '{"type":"statement","tense":"prepositions","words":["There","is","no","milk","in","the","fridge"]}'::jsonb, 34),
  ('sentence_scramble', 'easy', 'prepositions', '{"type":"command","tense":"prepositions","words":["Please","put","your","bag","on","the","chair"]}'::jsonb, 34),
  ('sentence_scramble', 'easy', 'foundations', '{"type":"question","tense":"foundations","words":["Will","it","rain","tomorrow"]}'::jsonb, 1),
  ('sentence_scramble', 'easy', 'foundations', '{"type":"negative","tense":"foundations","words":["My","dog","will","not","eat","vegetables"]}'::jsonb, 1),
  ('sentence_scramble', 'easy', 'foundations', '{"type":"statement","tense":"foundations","words":["There","are","many","students","here"]}'::jsonb, 1),
  ('sentence_scramble', 'easy', 'foundations', '{"type":"negative","tense":"foundations","words":["Don''t","forget","your","umbrella"]}'::jsonb, 1),
  ('sentence_scramble', 'medium', 'past_simple_regular', '{"type":"statement","tense":"past_simple_regular","words":["Yesterday,","I","finished","my","homework"]}'::jsonb, 41),
  ('sentence_scramble', 'medium', 'past_simple_regular', '{"type":"statement","tense":"past_simple_regular","words":["She","closed","the","door","quietly"]}'::jsonb, 41),
  ('sentence_scramble', 'medium', 'past_simple_regular', '{"type":"statement","tense":"past_simple_regular","words":["We","watched","a","funny","movie"]}'::jsonb, 41),
  ('sentence_scramble', 'medium', 'past_simple_regular', '{"type":"statement","tense":"past_simple_regular","words":["My","brother","cleaned","his","room"]}'::jsonb, 41),
  ('sentence_scramble', 'medium', 'past_simple_regular', '{"type":"negative","tense":"past_simple_regular","words":["He","did","not","finish","his","lunch"]}'::jsonb, 41),
  ('sentence_scramble', 'medium', 'past_simple_irregular', '{"type":"statement","tense":"past_simple_irregular","words":["We","went","to","the","zoo","last","weekend"]}'::jsonb, 42),
  ('sentence_scramble', 'medium', 'past_simple_irregular', '{"type":"statement","tense":"past_simple_irregular","words":["She","lost","her","umbrella","yesterday"]}'::jsonb, 42),
  ('sentence_scramble', 'medium', 'past_simple_irregular', '{"type":"statement","tense":"past_simple_irregular","words":["My","dog","ate","my","sandwich"]}'::jsonb, 42),
  ('sentence_scramble', 'medium', 'past_simple_irregular', '{"type":"negative","tense":"past_simple_irregular","words":["They","did","not","go","to","the","party"]}'::jsonb, 42),
  ('sentence_scramble', 'medium', 'past_simple_irregular', '{"type":"question","tense":"past_simple_irregular","words":["Where","did","you","put","my","keys"]}'::jsonb, 42),
  ('sentence_scramble', 'medium', 'present_continuous', '{"type":"statement","tense":"present_continuous","words":["The","baby","is","sleeping","now"]}'::jsonb, 49),
  ('sentence_scramble', 'medium', 'present_continuous', '{"type":"statement","tense":"present_continuous","words":["It","is","raining","outside"]}'::jsonb, 49),
  ('sentence_scramble', 'medium', 'present_continuous', '{"type":"statement","tense":"present_continuous","words":["My","sister","is","cooking","dinner"]}'::jsonb, 49),
  ('sentence_scramble', 'medium', 'present_continuous', '{"type":"statement","tense":"present_continuous","words":["Look!","The","cat","is","climbing","the","tree"]}'::jsonb, 49),
  ('sentence_scramble', 'medium', 'present_continuous', '{"type":"question","tense":"present_continuous","words":["Are","you","listening","to","me"]}'::jsonb, 49),
  ('sentence_scramble', 'medium', 'present_continuous', '{"type":"negative","tense":"present_continuous","words":["The","children","are","not","listening"]}'::jsonb, 49),
  ('sentence_scramble', 'medium', 'comparatives', '{"type":"statement","tense":"comparatives","words":["This","book","is","more","interesting","than","that","one"]}'::jsonb, 51),
  ('sentence_scramble', 'medium', 'comparatives', '{"type":"statement","tense":"comparatives","words":["My","brother","is","taller","than","me"]}'::jsonb, 51),
  ('sentence_scramble', 'medium', 'comparatives', '{"type":"statement","tense":"comparatives","words":["The","blue","car","is","faster","than","the","red","one"]}'::jsonb, 51),
  ('sentence_scramble', 'medium', 'comparatives', '{"type":"negative","tense":"comparatives","words":["This","exercise","is","not","easier","than","the","last","one"]}'::jsonb, 51),
  ('sentence_scramble', 'medium', 'comparatives', '{"type":"question","tense":"comparatives","words":["Which","bag","is","heavier,","this","one","or","that","one"]}'::jsonb, 51),
  ('sentence_scramble', 'medium', 'comparatives', '{"type":"statement","tense":"comparatives","words":["My","grandmother","is","stronger","than","she","looks"]}'::jsonb, 51),
  ('sentence_scramble', 'medium', 'present_continuous', '{"type":"question","tense":"present_continuous","words":["What","are","you","doing","right","now"]}'::jsonb, 49),
  ('sentence_scramble', 'medium', 'present_continuous', '{"type":"negative","tense":"present_continuous","words":["We","are","not","walking","to","school","today"]}'::jsonb, 49),
  ('sentence_scramble', 'medium', 'comparatives', '{"type":"statement","tense":"comparatives","words":["My","cat","is","faster","than","my","dog"]}'::jsonb, 51),
  ('sentence_scramble', 'hard', 'present_continuous', '{"type":"statement","tense":"present_continuous","words":["My","brother","usually","walks","to","school,","but","today","he","is","running"]}'::jsonb, 49),
  ('sentence_scramble', 'hard', 'present_continuous', '{"type":"statement","tense":"present_continuous","words":["I","finished","my","homework,","so","now","I","am","watching","TV"]}'::jsonb, 49),
  ('sentence_scramble', 'hard', 'past_simple_irregular', '{"type":"statement","tense":"past_simple_irregular","words":["We","went","to","the","park","and","played","football"]}'::jsonb, 42),
  ('sentence_scramble', 'hard', 'comparatives', '{"type":"statement","tense":"comparatives","words":["My","sister","can","run","faster","than","me"]}'::jsonb, 51),
  ('sentence_scramble', 'hard', 'comparatives', '{"type":"statement","tense":"comparatives","words":["There","are","more","students","in","our","class","this","year"]}'::jsonb, 51),
  ('sentence_scramble', 'hard', 'foundations', '{"type":"command","tense":"foundations","words":["Please","close","the","door","before","you","leave"]}'::jsonb, 1),
  ('sentence_scramble', 'hard', 'past_simple_irregular', '{"type":"statement","tense":"past_simple_irregular","words":["My","dog","ate","my","homework","and","hid","under","the","sofa"]}'::jsonb, 42),
  ('sentence_scramble', 'hard', 'past_simple_regular', '{"type":"statement","tense":"past_simple_regular","words":["We","waited","at","the","bus","stop","for","twenty","minutes"]}'::jsonb, 41),
  ('sentence_scramble', 'hard', 'past_simple_regular', '{"type":"question","tense":"past_simple_regular","words":["Why","did","you","arrive","late","yesterday"]}'::jsonb, 41),
  ('sentence_scramble', 'hard', 'comparatives', '{"type":"statement","tense":"comparatives","words":["My","grandmother","can","cook","better","than","a","chef"]}'::jsonb, 51),
  ('sentence_scramble', 'hard', 'prepositions', '{"type":"negative","tense":"prepositions","words":["The","keys","are","on","the","table,","not","in","my","bag"]}'::jsonb, 34),
  ('sentence_scramble', 'hard', 'present_continuous', '{"type":"statement","tense":"present_continuous","words":["Look!","There","is","a","strange","noise","in","the","kitchen"]}'::jsonb, 49),
  ('sentence_scramble', 'hard', 'can_ability', '{"type":"statement","tense":"can_ability","words":["My","cat","can","open","doors","by","itself"]}'::jsonb, 10),
  ('sentence_scramble', 'hard', 'comparatives', '{"type":"statement","tense":"comparatives","words":["The","movie","we","watched","last","night","seemed","better","than","I","expected"]}'::jsonb, 51),
  ('sentence_scramble', 'hard', 'present_continuous', '{"type":"question","tense":"present_continuous","words":["Why","are","you","smiling","like","that"]}'::jsonb, 49),
  ('sentence_scramble', 'hard', 'can_ability', '{"type":"negative","tense":"can_ability","words":["My","brother","can","swim,","but","he","cannot","dive"]}'::jsonb, 10),
  ('sentence_scramble', 'hard', 'present_continuous', '{"type":"negative","tense":"present_continuous","words":["We","are","not","listening","to","the","radio","right","now"]}'::jsonb, 49),
  ('sentence_scramble', 'hard', 'present_continuous', '{"type":"statement","tense":"present_continuous","words":["My","mother","is","making","breakfast","while","my","brother","is","still","sleeping"]}'::jsonb, 49),
  ('sentence_scramble', 'hard', 'comparatives', '{"type":"statement","tense":"comparatives","words":["This","backpack","is","heavier","than","it","looks"]}'::jsonb, 51),
  ('sentence_scramble', 'hard', 'foundations', '{"type":"command","tense":"foundations","words":["Please","give","me","your","homework","before","the","bell","rings"]}'::jsonb, 1),
  ('sentence_scramble', 'very_hard', 'first_conditional', '{"type":"statement","tense":"first_conditional","words":["If","it","rains","tomorrow,","we","will","stay","at","home"]}'::jsonb, 86),
  ('sentence_scramble', 'very_hard', 'first_conditional', '{"type":"statement","tense":"first_conditional","words":["If","you","study","harder,","you","will","pass","the","exam"]}'::jsonb, 86),
  ('sentence_scramble', 'very_hard', 'first_conditional', '{"type":"statement","tense":"first_conditional","words":["Unless","you","hurry,","you","will","miss","the","bus"]}'::jsonb, 86),
  ('sentence_scramble', 'very_hard', 'first_conditional', '{"type":"statement","tense":"first_conditional","words":["If","my","cat","gets","hungry,","it","will","wake","me","up","at","five"]}'::jsonb, 86),
  ('sentence_scramble', 'very_hard', 'first_conditional', '{"type":"negative","tense":"first_conditional","words":["If","you","don''t","water","the","plant,","it","will","die"]}'::jsonb, 86),
  ('sentence_scramble', 'very_hard', 'first_conditional', '{"type":"statement","tense":"first_conditional","words":["If","the","weather","is","nice,","we","will","play","outside","all","afternoon"]}'::jsonb, 86),
  ('sentence_scramble', 'very_hard', 'first_conditional', '{"type":"statement","tense":"first_conditional","words":["If","she","practices","every","day,","she","can","speak","English","very","well"]}'::jsonb, 86),
  ('sentence_scramble', 'very_hard', 'first_conditional', '{"type":"statement","tense":"first_conditional","words":["If","you","leave","your","bag","in","the","classroom,","someone","will","take","it"]}'::jsonb, 86),
  ('sentence_scramble', 'very_hard', 'first_conditional', '{"type":"statement","tense":"first_conditional","words":["My","brother","usually","goes","to","school","by","bus,","but","if","it","rains,","he","will","walk"]}'::jsonb, 86),
  ('sentence_scramble', 'very_hard', 'first_conditional', '{"type":"negative","tense":"first_conditional","words":["If","we","don''t","have","enough","students,","the","trip","will","be","cancelled"]}'::jsonb, 86),
  ('sentence_scramble', 'very_hard', 'first_conditional', '{"type":"statement","tense":"first_conditional","words":["If","you","finish","your","homework","early,","you","can","watch","TV"]}'::jsonb, 86),
  ('sentence_scramble', 'very_hard', 'first_conditional', '{"type":"negative","tense":"first_conditional","words":["There","will","be","more","homework","if","you","don''t","finish","today"]}'::jsonb, 86),
  ('sentence_scramble', 'very_hard', 'first_conditional', '{"type":"statement","tense":"first_conditional","words":["If","our","teacher","is","absent","tomorrow,","we","will","have","a","free","period"]}'::jsonb, 86),
  ('sentence_scramble', 'very_hard', 'first_conditional', '{"type":"statement","tense":"first_conditional","words":["My","dog","will","bark","loudly","if","a","stranger","comes","near","the","house"]}'::jsonb, 86),
  ('sentence_scramble', 'very_hard', 'first_conditional', '{"type":"statement","tense":"first_conditional","words":["If","you","practice","every","day,","you","will","become","better","than","before"]}'::jsonb, 86),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"My uncle are very kind.","wrong_index":2,"correction":"is"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"She is my friend.","wrong_index":1,"correction":"am"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"Our neighbors is very friendly.","wrong_index":2,"correction":"are"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"My teacher are strict.","wrong_index":2,"correction":"is"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"This is my rabbit. She is fluffy.","wrong_index":4,"correction":"It"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"She likes apples.","wrong_index":1,"correction":"like"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"My aunt cook dinner every night.","wrong_index":2,"correction":"cooks"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"Our cow eat grass all day.","wrong_index":2,"correction":"eats"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"I have two book.","wrong_index":3,"correction":"books"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"There are five chair in the room.","wrong_index":3,"correction":"chairs"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"There is many cats outside.","wrong_index":1,"correction":"are"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"There are a parrot on the roof.","wrong_index":1,"correction":"is"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"My uncle will visits us tomorrow.","wrong_index":3,"correction":"visit"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"The coach will helps us practice.","wrong_index":3,"correction":"help"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"Please closes the window.","wrong_index":1,"correction":"close"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"Stands up and say hello.","wrong_index":0,"correction":"Stand"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"My cousin is very talls.","wrong_index":4,"correction":"tall"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"Our team are happy today.","wrong_index":2,"correction":"is"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"My rabbit hop around the garden.","wrong_index":2,"correction":"hops"}'::jsonb, 1),
  ('word_detective', 'very_easy', 'foundations', '{"sentence":"I are eleven years old.","wrong_index":1,"correction":"am"}'::jsonb, 1),
  ('word_detective', 'easy', 'basic_questions', '{"sentence":"Does he likes football?","wrong_index":2,"correction":"like"}'::jsonb, 6),
  ('word_detective', 'easy', 'basic_questions', '{"sentence":"Do your neighbor live near here?","wrong_index":0,"correction":"Does"}'::jsonb, 6),
  ('word_detective', 'easy', 'basic_questions', '{"sentence":"Where do he go on weekends?","wrong_index":1,"correction":"does"}'::jsonb, 6),
  ('word_detective', 'easy', 'basic_questions', '{"sentence":"What time do the shop open?","wrong_index":2,"correction":"does"}'::jsonb, 6),
  ('word_detective', 'easy', 'basic_questions', '{"sentence":"Our coach do not like losing.","wrong_index":2,"correction":"does"}'::jsonb, 6),
  ('word_detective', 'easy', 'basic_questions', '{"sentence":"I does not have a bicycle.","wrong_index":1,"correction":"do"}'::jsonb, 6),
  ('word_detective', 'easy', 'can_ability', '{"sentence":"My aunt can drives very well.","wrong_index":3,"correction":"drive"}'::jsonb, 10),
  ('word_detective', 'easy', 'can_ability', '{"sentence":"Our parrot can talks.","wrong_index":3,"correction":"talk"}'::jsonb, 10),
  ('word_detective', 'easy', 'can_ability', '{"sentence":"Can you helps me carry this bag?","wrong_index":2,"correction":"help"}'::jsonb, 10),
  ('word_detective', 'easy', 'can_ability', '{"sentence":"My grandfather can dances well.","wrong_index":3,"correction":"dance"}'::jsonb, 10),
  ('word_detective', 'easy', 'prepositions', '{"sentence":"The rabbit is at the box.","wrong_index":3,"correction":"in"}'::jsonb, 34),
  ('word_detective', 'easy', 'prepositions', '{"sentence":"We meet in six oclock.","wrong_index":2,"correction":"at"}'::jsonb, 34),
  ('word_detective', 'easy', 'prepositions', '{"sentence":"My uncles car is on the garage.","wrong_index":4,"correction":"in"}'::jsonb, 34),
  ('word_detective', 'easy', 'prepositions', '{"sentence":"The library closes in six.","wrong_index":3,"correction":"at"}'::jsonb, 34),
  ('word_detective', 'easy', 'prepositions', '{"sentence":"There is no bread on the kitchen.","wrong_index":4,"correction":"in"}'::jsonb, 34),
  ('word_detective', 'easy', 'prepositions', '{"sentence":"Please put your shoes in the shelf.","wrong_index":4,"correction":"on"}'::jsonb, 34),
  ('word_detective', 'easy', 'foundations', '{"sentence":"Will our team wins tomorrow?","wrong_index":3,"correction":"win"}'::jsonb, 1),
  ('word_detective', 'easy', 'foundations', '{"sentence":"Our cow will not walks fast.","wrong_index":4,"correction":"walk"}'::jsonb, 1),
  ('word_detective', 'easy', 'foundations', '{"sentence":"There is many chairs in the hall.","wrong_index":1,"correction":"are"}'::jsonb, 1),
  ('word_detective', 'easy', 'foundations', '{"sentence":"Dont forgets your homework.","wrong_index":1,"correction":"forget"}'::jsonb, 1),
  ('word_detective', 'medium', 'past_simple_regular', '{"sentence":"Yesterday, my aunt visit us.","wrong_index":3,"correction":"visited"}'::jsonb, 41),
  ('word_detective', 'medium', 'past_simple_regular', '{"sentence":"Our coach explain the rules.","wrong_index":2,"correction":"explained"}'::jsonb, 41),
  ('word_detective', 'medium', 'past_simple_regular', '{"sentence":"We watch a funny show last night.","wrong_index":1,"correction":"watched"}'::jsonb, 41),
  ('word_detective', 'medium', 'past_simple_regular', '{"sentence":"My cousin clean his bike yesterday.","wrong_index":2,"correction":"cleaned"}'::jsonb, 41),
  ('word_detective', 'medium', 'past_simple_regular', '{"sentence":"The team did not practiced enough.","wrong_index":4,"correction":"practice"}'::jsonb, 41),
  ('word_detective', 'medium', 'past_simple_irregular', '{"sentence":"We goed to the market yesterday.","wrong_index":1,"correction":"went"}'::jsonb, 42),
  ('word_detective', 'medium', 'past_simple_irregular', '{"sentence":"My uncle losed his phone.","wrong_index":2,"correction":"lost"}'::jsonb, 42),
  ('word_detective', 'medium', 'past_simple_irregular', '{"sentence":"Our rabbit eated the carrots.","wrong_index":2,"correction":"ate"}'::jsonb, 42),
  ('word_detective', 'medium', 'past_simple_irregular', '{"sentence":"They did not came to school.","wrong_index":3,"correction":"come"}'::jsonb, 42),
  ('word_detective', 'medium', 'past_simple_irregular', '{"sentence":"Where did you putted the ball?","wrong_index":3,"correction":"put"}'::jsonb, 42),
  ('word_detective', 'medium', 'present_continuous', '{"sentence":"My baby sister sleeping now.","wrong_index":3,"correction":"is sleeping"}'::jsonb, 49),
  ('word_detective', 'medium', 'present_continuous', '{"sentence":"It snowing outside.","wrong_index":1,"correction":"is snowing"}'::jsonb, 49),
  ('word_detective', 'medium', 'present_continuous', '{"sentence":"My aunt cooking soup.","wrong_index":2,"correction":"is cooking"}'::jsonb, 49),
  ('word_detective', 'medium', 'present_continuous', '{"sentence":"Look! The parrot dancing on the table.","wrong_index":3,"correction":"is dancing"}'::jsonb, 49),
  ('word_detective', 'medium', 'present_continuous', '{"sentence":"Are you listen to the teacher?","wrong_index":2,"correction":"listening"}'::jsonb, 49),
  ('word_detective', 'medium', 'present_continuous', '{"sentence":"The players is not listening.","wrong_index":2,"correction":"are"}'::jsonb, 49),
  ('word_detective', 'medium', 'comparatives', '{"sentence":"This puzzle is difficulter than the last one.","wrong_index":3,"correction":"more difficult"}'::jsonb, 51),
  ('word_detective', 'medium', 'comparatives', '{"sentence":"My cousin is shortter than me.","wrong_index":3,"correction":"shorter"}'::jsonb, 51),
  ('word_detective', 'medium', 'comparatives', '{"sentence":"The green bike is fastest than the black one.","wrong_index":4,"correction":"faster"}'::jsonb, 51),
  ('word_detective', 'medium', 'comparatives', '{"sentence":"This game is not easyer than the last one.","wrong_index":4,"correction":"easier"}'::jsonb, 51),
  ('word_detective', 'medium', 'comparatives', '{"sentence":"Which bag is heavyer than the other?","wrong_index":3,"correction":"heavier"}'::jsonb, 51),
  ('word_detective', 'medium', 'comparatives', '{"sentence":"Our coach is stronger that he looks.","wrong_index":4,"correction":"than"}'::jsonb, 51),
  ('word_detective', 'medium', 'present_continuous', '{"sentence":"What are you do after school?","wrong_index":3,"correction":"doing"}'::jsonb, 49),
  ('word_detective', 'medium', 'present_continuous', '{"sentence":"We are not walk to the park today.","wrong_index":3,"correction":"walking"}'::jsonb, 49),
  ('word_detective', 'medium', 'comparatives', '{"sentence":"My parrot is loud than my dog.","wrong_index":3,"correction":"louder"}'::jsonb, 51),
  ('word_detective', 'hard', 'foundations', '{"sentence":"My brother usually walk to school every day.","wrong_index":3,"correction":"walks"}'::jsonb, 1),
  ('word_detective', 'hard', 'past_simple_regular', '{"sentence":"I finish my homework already, so now I am relaxing.","wrong_index":1,"correction":"finished"}'::jsonb, 41),
  ('word_detective', 'hard', 'past_simple_irregular', '{"sentence":"We went to the market and buy some bread.","wrong_index":6,"correction":"bought"}'::jsonb, 42),
  ('word_detective', 'hard', 'can_ability', '{"sentence":"My cousin can jumps higher than me.","wrong_index":3,"correction":"jump"}'::jsonb, 51),
  ('word_detective', 'hard', 'comparatives', '{"sentence":"There is more chairs than yesterday.","wrong_index":1,"correction":"are"}'::jsonb, 51),
  ('word_detective', 'hard', 'foundations', '{"sentence":"Please closes the window before you leave.","wrong_index":1,"correction":"close"}'::jsonb, 1),
  ('word_detective', 'hard', 'past_simple_irregular', '{"sentence":"Our rabbit ran and hided under the table.","wrong_index":4,"correction":"hid"}'::jsonb, 42),
  ('word_detective', 'hard', 'past_simple_regular', '{"sentence":"We waited on the school gate for ten minutes.","wrong_index":2,"correction":"at"}'::jsonb, 34),
  ('word_detective', 'hard', 'past_simple_regular', '{"sentence":"Why did you arrived late today?","wrong_index":3,"correction":"arrive"}'::jsonb, 41),
  ('word_detective', 'hard', 'can_ability', '{"sentence":"My aunt can bakes better than a chef.","wrong_index":3,"correction":"bake"}'::jsonb, 51),
  ('word_detective', 'hard', 'prepositions', '{"sentence":"The ball are on the box.","wrong_index":2,"correction":"is"}'::jsonb, 34),
  ('word_detective', 'hard', 'present_continuous', '{"sentence":"Look! There are a loud noise upstairs.","wrong_index":2,"correction":"is"}'::jsonb, 49),
  ('word_detective', 'hard', 'can_ability', '{"sentence":"Our parrot can copies human voices.","wrong_index":3,"correction":"copy"}'::jsonb, 10),
  ('word_detective', 'hard', 'comparatives', '{"sentence":"The show we see last week seemed shorter than expected.","wrong_index":3,"correction":"saw"}'::jsonb, 51),
  ('word_detective', 'hard', 'present_continuous', '{"sentence":"Why is you laughing so much?","wrong_index":1,"correction":"are"}'::jsonb, 49),
  ('word_detective', 'hard', 'can_ability', '{"sentence":"My cousin can dance, but he cans not sing.","wrong_index":6,"correction":"can"}'::jsonb, 10),
  ('word_detective', 'hard', 'present_continuous', '{"sentence":"We are not watch the game right now.","wrong_index":3,"correction":"watching"}'::jsonb, 49),
  ('word_detective', 'hard', 'present_continuous', '{"sentence":"Our coach is giving instructions while the players still warming up.","wrong_index":9,"correction":"are warming"}'::jsonb, 49),
  ('word_detective', 'hard', 'comparatives', '{"sentence":"This bag is heavyer than it looks.","wrong_index":3,"correction":"heavier"}'::jsonb, 51),
  ('word_detective', 'hard', 'foundations', '{"sentence":"Please hand me your ticket before the show start.","wrong_index":8,"correction":"starts"}'::jsonb, 1),
  ('word_detective', 'very_hard', 'first_conditional', '{"sentence":"If it snow tomorrow, school will close.","wrong_index":2,"correction":"snows"}'::jsonb, 86),
  ('word_detective', 'very_hard', 'first_conditional', '{"sentence":"If you practice daily, you improve quickly.","wrong_index":5,"correction":"will improve"}'::jsonb, 86),
  ('word_detective', 'very_hard', 'first_conditional', '{"sentence":"Unless we hurry, we miss the train.","wrong_index":4,"correction":"will miss"}'::jsonb, 86),
  ('word_detective', 'very_hard', 'first_conditional', '{"sentence":"If our parrot get bored, it will scream all afternoon.","wrong_index":3,"correction":"gets"}'::jsonb, 86),
  ('word_detective', 'very_hard', 'first_conditional', '{"sentence":"If you dont feed the rabbit, it get hungry.","wrong_index":7,"correction":"will get"}'::jsonb, 86),
  ('word_detective', 'very_hard', 'first_conditional', '{"sentence":"If the road busy tomorrow, we will leave early.","wrong_index":3,"correction":"is busy"}'::jsonb, 86),
  ('word_detective', 'very_hard', 'first_conditional', '{"sentence":"If she train every week, she can win the competition.","wrong_index":2,"correction":"trains"}'::jsonb, 86),
  ('word_detective', 'very_hard', 'first_conditional', '{"sentence":"If you leave your bike outside, someone borrow it.","wrong_index":7,"correction":"will borrow"}'::jsonb, 86),
  ('word_detective', 'very_hard', 'first_conditional', '{"sentence":"Our coach usually arrive early, but if traffic is bad, he will be late.","wrong_index":3,"correction":"arrives"}'::jsonb, 86),
  ('word_detective', 'very_hard', 'first_conditional', '{"sentence":"If we dont sell enough ticket for the show, it will be cancelled.","wrong_index":5,"correction":"tickets"}'::jsonb, 86),
  ('word_detective', 'very_hard', 'first_conditional', '{"sentence":"If you finish your chores early, you watch a movie.","wrong_index":7,"correction":"can watch"}'::jsonb, 86),
  ('word_detective', 'very_hard', 'first_conditional', '{"sentence":"There will be more practice if the team dont improve.","wrong_index":8,"correction":"doesn''t"}'::jsonb, 86),
  ('word_detective', 'very_hard', 'first_conditional', '{"sentence":"If the weather cold tomorrow, we will stay inside.","wrong_index":3,"correction":"is cold"}'::jsonb, 86),
  ('word_detective', 'very_hard', 'first_conditional', '{"sentence":"Our parrot will scream loudly if a stranger enter the room.","wrong_index":8,"correction":"enters"}'::jsonb, 86),
  ('word_detective', 'very_hard', 'first_conditional', '{"sentence":"If you keep practicing, you become stronger than before.","wrong_index":5,"correction":"will become"}'::jsonb, 86),
  ('grammar_battle', 'very_easy', 'foundations', '{"question":"My name ___ Anna.","options":["am","is","are","be"],"correct_index":1,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_easy', 'foundations', '{"question":"They ___ my friends.","options":["is","am","are","be"],"correct_index":2,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_easy', 'foundations', '{"question":"I ___ ten years old.","options":["is","am","are","be"],"correct_index":1,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_easy', 'foundations', '{"question":"She ___ to school every day.","options":["go","goes","going","gone"],"correct_index":1,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_easy', 'foundations', '{"question":"We ___ pizza on Fridays.","options":["eats","eat","eating","ate"],"correct_index":1,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_easy', 'foundations', '{"question":"He ___ football on weekends.","options":["play","plays","playing","played"],"correct_index":1,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_easy', 'foundations', '{"question":"I have two ___.","options":["dog","dogs","doges","dog''s"],"correct_index":1,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_easy', 'foundations', '{"question":"There are five ___ in the box.","options":["box","boxs","boxes","boxies"],"correct_index":2,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_easy', 'foundations', '{"question":"The cat is ___ the table.","options":["on","at","to","for"],"correct_index":0,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_easy', 'foundations', '{"question":"We meet ___ 5 oclock.","options":["in","on","at","for"],"correct_index":2,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_easy', 'foundations', '{"question":"My birthday is ___ July.","options":["at","on","in","for"],"correct_index":2,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_easy', 'foundations', '{"question":"Maria is happy. ___ is smiling.","options":["He","She","It","They"],"correct_index":1,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_easy', 'foundations', '{"question":"This is my dog. ___ is friendly.","options":["He","She","It","They"],"correct_index":2,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_easy', 'basic_questions', '{"question":"Do you ___ tea?","options":["like","likes","liking","liked"],"correct_index":0,"category":"basic_questions"}'::jsonb, 6),
  ('grammar_battle', 'very_easy', 'basic_questions', '{"question":"Does he ___ in a big house?","options":["live","lives","living","lived"],"correct_index":0,"category":"basic_questions"}'::jsonb, 6),
  ('grammar_battle', 'very_easy', 'foundations', '{"question":"It ___ cold today.","options":["am","is","are","be"],"correct_index":1,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_easy', 'foundations', '{"question":"My mother has three ___.","options":["child","childs","children","childes"],"correct_index":2,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_easy', 'foundations', '{"question":"We ___ at school now.","options":["am","is","are","be"],"correct_index":2,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_easy', 'foundations', '{"question":"Look! It ___ raining.","options":["is","are","am","be"],"correct_index":0,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_easy', 'foundations', '{"question":"We ___ watching a movie right now.","options":["is","are","am","be"],"correct_index":1,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'easy', 'past_simple_regular', '{"question":"Yesterday, I ___ my homework.","options":["finish","finishes","finished","finishing"],"correct_index":2,"category":"past_simple_regular"}'::jsonb, 41),
  ('grammar_battle', 'easy', 'past_simple_regular', '{"question":"She ___ the door before she left.","options":["close","closed","closes","closing"],"correct_index":1,"category":"past_simple_regular"}'::jsonb, 41),
  ('grammar_battle', 'easy', 'past_simple_irregular', '{"question":"We ___ to the zoo last weekend.","options":["go","goes","went","gone"],"correct_index":2,"category":"past_simple_irregular"}'::jsonb, 42),
  ('grammar_battle', 'easy', 'past_simple_irregular', '{"question":"He ___ a big fish yesterday.","options":["catch","catches","caught","catched"],"correct_index":2,"category":"past_simple_irregular"}'::jsonb, 42),
  ('grammar_battle', 'easy', 'basic_questions', '{"question":"___ your friends like sports?","options":["Do","Does","Did","Is"],"correct_index":0,"category":"basic_questions"}'::jsonb, 6),
  ('grammar_battle', 'easy', 'basic_questions', '{"question":"___ it usually rain in autumn?","options":["Do","Does","Did","Is"],"correct_index":1,"category":"basic_questions"}'::jsonb, 6),
  ('grammar_battle', 'easy', 'basic_questions', '{"question":"___ your class start at nine?","options":["Do","Does","Did","Is"],"correct_index":1,"category":"basic_questions"}'::jsonb, 6),
  ('grammar_battle', 'easy', 'foundations', '{"question":"There ___ a cat in the garden.","options":["There is","There are","It is","They are"],"correct_index":0,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'easy', 'foundations', '{"question":"There ___ many students in the class.","options":["There is","There are","It is","They are"],"correct_index":1,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'easy', 'foundations', '{"question":"I ___ call you tomorrow.","options":["will","am","do","did"],"correct_index":0,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'easy', 'foundations', '{"question":"It ___ not rain this weekend.","options":["will","is","does","did"],"correct_index":0,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'easy', 'present_continuous', '{"question":"My sister ___ a letter at the moment.","options":["write","writes","is writing","wrote"],"correct_index":2,"category":"present_continuous"}'::jsonb, 49),
  ('grammar_battle', 'easy', 'past_simple_irregular', '{"question":"My grandfather ___ me a funny story last night.","options":["tell","tells","told","telled"],"correct_index":2,"category":"past_simple_irregular"}'::jsonb, 42),
  ('grammar_battle', 'easy', 'past_simple_irregular', '{"question":"They ___ their bikes in the park yesterday.","options":["ride","rides","rode","riding"],"correct_index":2,"category":"past_simple_irregular"}'::jsonb, 42),
  ('grammar_battle', 'easy', 'foundations', '{"question":"There ___ no milk in the fridge.","options":["There is","There are","It is","They are"],"correct_index":0,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'easy', 'foundations', '{"question":"___ they at home now?","options":["Do","Does","Did","Are"],"correct_index":3,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'easy', 'foundations', '{"question":"My dog ___ chase the ball if you throw it.","options":["will","is","does","did"],"correct_index":0,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'easy', 'foundations', '{"question":"The children ___ playing in the yard.","options":["is","are","am","be"],"correct_index":1,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'easy', 'foundations', '{"question":"I ___ my keys. Can you help me find them?","options":["lost","have lost","am losing","lose"],"correct_index":0,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'easy', 'comparatives', '{"question":"This puzzle is ___ than the last one.","options":["hard","harder","hardest","more hard"],"correct_index":1,"category":"comparatives"}'::jsonb, 51),
  ('grammar_battle', 'medium', 'comparatives', '{"question":"My brother is ___ than me.","options":["tall","taller","tallest","more tall"],"correct_index":1,"category":"comparatives"}'::jsonb, 51),
  ('grammar_battle', 'medium', 'can_ability', '{"question":"You ___ finish your homework before dinner.","options":["can","must","may","could"],"correct_index":0,"category":"can_ability"}'::jsonb, 10),
  ('grammar_battle', 'medium', 'can_ability', '{"question":"___ I open the window, please?","options":["Must","Should","Can","Have to"],"correct_index":2,"category":"can_ability"}'::jsonb, 10),
  ('grammar_battle', 'medium', 'can_ability', '{"question":"He ___ speak three languages.","options":["can","must","should","has to"],"correct_index":0,"category":"can_ability"}'::jsonb, 10),
  ('grammar_battle', 'medium', 'comparatives', '{"question":"The red bike is ___ than the blue one.","options":["cheap","cheaper","cheapest","more cheap"],"correct_index":1,"category":"comparatives"}'::jsonb, 51),
  ('grammar_battle', 'medium', 'foundations', '{"question":"I ___ this book twice already.","options":["read","have read","reads","am reading"],"correct_index":2,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'medium', 'comparatives', '{"question":"Today is ___ than yesterday.","options":["cold","colder","coldest","more cold"],"correct_index":1,"category":"comparatives"}'::jsonb, 51),
  ('grammar_battle', 'medium', 'first_conditional', '{"question":"If it rains, we ___ stay inside.","options":["will","would","do","did"],"correct_index":0,"category":"first_conditional"}'::jsonb, 86),
  ('grammar_battle', 'medium', 'first_conditional', '{"question":"If you ___ hard, you will pass the exam.","options":["study","studied","will study","studying"],"correct_index":0,"category":"first_conditional"}'::jsonb, 86),
  ('grammar_battle', 'medium', 'first_conditional', '{"question":"If my cat gets hungry, it ___ wake me up at 5am.","options":["will","would","does","did"],"correct_index":0,"category":"first_conditional"}'::jsonb, 86),
  ('grammar_battle', 'medium', 'first_conditional', '{"question":"If you dont water the plant, it ___ die.","options":["will","would","does","did"],"correct_index":0,"category":"first_conditional"}'::jsonb, 86),
  ('grammar_battle', 'medium', 'first_conditional', '{"question":"What will happen if it ___ tomorrow?","options":["rain","rains","rained","raining"],"correct_index":1,"category":"first_conditional"}'::jsonb, 86),
  ('grammar_battle', 'medium', 'first_conditional', '{"question":"If our teacher ___ absent tomorrow, we will have a free period.","options":["is","are","am","be"],"correct_index":0,"category":"first_conditional"}'::jsonb, 86),
  ('grammar_battle', 'medium', 'first_conditional', '{"question":"My brother usually goes to school by bus, but if it rains, he will ___.","options":["walk","walks","walked","walking"],"correct_index":0,"category":"first_conditional"}'::jsonb, 86),
  ('grammar_battle', 'medium', 'first_conditional', '{"question":"If we dont have enough students, the trip ___ be cancelled.","options":["will","would","does","did"],"correct_index":0,"category":"first_conditional"}'::jsonb, 86),
  ('grammar_battle', 'medium', 'basic_questions', '{"question":"Why ___ your brother go to school so early?","options":["does","do","did","is"],"correct_index":0,"category":"basic_questions"}'::jsonb, 6),
  ('grammar_battle', 'medium', 'foundations', '{"question":"My cat ___ like water.","options":["does not","do not","did not","is not"],"correct_index":0,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'medium', 'foundations', '{"question":"Why ___ you so tired today?","options":["am","are","is","be"],"correct_index":1,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'medium', 'foundations', '{"question":"My little sister ___ afraid of the dark anymore.","options":["is not","are not","am not","do not"],"correct_index":0,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'medium', 'basic_questions', '{"question":"I ___ know the answer to that question.","options":["do not","does not","did not","am not"],"correct_index":0,"category":"basic_questions"}'::jsonb, 6),
  ('grammar_battle', 'medium', 'foundations', '{"question":"___ enough chairs for everyone?","options":["Is there","Are there","Does there","There are"],"correct_index":1,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'medium', 'foundations', '{"question":"How many ___ do you have at home?","options":["pet","pets","petes","pet''s"],"correct_index":1,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'medium', 'can_ability', '{"question":"My brother ___ swim, but he can ride a bike.","options":["cannot","can not to","is cannot","am cannot"],"correct_index":0,"category":"can_ability"}'::jsonb, 10),
  ('grammar_battle', 'medium', 'can_ability', '{"question":"___ your dog do any tricks?","options":["Can","Does","Is","Do"],"correct_index":0,"category":"can_ability"}'::jsonb, 10),
  ('grammar_battle', 'medium', 'prepositions', '{"question":"What time do you usually arrive ___ school?","options":["at","in","to","for"],"correct_index":0,"category":"prepositions"}'::jsonb, 34),
  ('grammar_battle', 'hard', 'past_simple_regular', '{"question":"What time ___ you finish your homework yesterday?","options":["did","do","does","are"],"correct_index":0,"category":"past_simple_regular"}'::jsonb, 41),
  ('grammar_battle', 'hard', 'past_simple_irregular', '{"question":"We ___ go to the party last night.","options":["did not","do not","does not","are not"],"correct_index":0,"category":"past_simple_irregular"}'::jsonb, 42),
  ('grammar_battle', 'hard', 'present_continuous', '{"question":"Why ___ you smiling like that?","options":["am","are","is","be"],"correct_index":1,"category":"present_continuous"}'::jsonb, 49),
  ('grammar_battle', 'hard', 'present_continuous', '{"question":"The children ___ listening to the teacher right now.","options":["is not","are not","am not","do not"],"correct_index":1,"category":"present_continuous"}'::jsonb, 49),
  ('grammar_battle', 'hard', 'comparatives', '{"question":"Which bag is ___, this one or that one?","options":["heavy","heavier","heaviest","more heavy"],"correct_index":1,"category":"comparatives"}'::jsonb, 51),
  ('grammar_battle', 'hard', 'basic_questions', '{"question":"Where ___ your parents work?","options":["do","does","did","is"],"correct_index":0,"category":"basic_questions"}'::jsonb, 6),
  ('grammar_battle', 'hard', 'foundations', '{"question":"___ your friends coming to the party tonight?","options":["Is","Are","Am","Do"],"correct_index":1,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'hard', 'can_ability', '{"question":"My little brother ___ tie his own shoes yet.","options":["cannot","can","cans","is can"],"correct_index":0,"category":"can_ability"}'::jsonb, 10),
  ('grammar_battle', 'hard', 'past_simple_regular', '{"question":"She ___ close the window before she left.","options":["did not","do not","does not","is not"],"correct_index":0,"category":"past_simple_regular"}'::jsonb, 41),
  ('grammar_battle', 'hard', 'basic_questions', '{"question":"___ is your favorite subject at school?","options":["What","Who","Where","When"],"correct_index":0,"category":"basic_questions"}'::jsonb, 6),
  ('grammar_battle', 'hard', 'foundations', '{"question":"___ any milk left in the fridge.","options":["There is not","There are not","It is not","They are not"],"correct_index":0,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'hard', 'prepositions', '{"question":"My homework is not ___ my bag; I think I left it at home.","options":["in","at","to","for"],"correct_index":0,"category":"prepositions"}'::jsonb, 34),
  ('grammar_battle', 'hard', 'present_continuous', '{"question":"What ___ your mother cooking for dinner tonight?","options":["is","are","am","does"],"correct_index":0,"category":"present_continuous"}'::jsonb, 49),
  ('grammar_battle', 'hard', 'comparatives', '{"question":"This exercise is not ___ than the last one.","options":["easy","easier","easiest","more easy"],"correct_index":1,"category":"comparatives"}'::jsonb, 51),
  ('grammar_battle', 'hard', 'present_continuous', '{"question":"My brother usually goes to school by bus, but today he ___ to school.","options":["is walking","walks","walked","walk"],"correct_index":0,"category":"present_continuous"}'::jsonb, 49),
  ('grammar_battle', 'hard', 'present_continuous', '{"question":"I usually drink tea, but right now I ___ coffee.","options":["am drinking","drink","drank","drinking"],"correct_index":0,"category":"present_continuous"}'::jsonb, 49),
  ('grammar_battle', 'hard', 'foundations', '{"question":"My sister is tall, but my brother ___ even taller.","options":["is","are","am","be"],"correct_index":0,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'hard', 'can_ability', '{"question":"My brother is doing his homework now, but he ___ finish it without help.","options":["cannot","can","is cannot","am cannot"],"correct_index":0,"category":"can_ability"}'::jsonb, 10),
  ('grammar_battle', 'hard', 'past_simple_irregular', '{"question":"We ___ to the park and played football yesterday.","options":["went","go","goes","going"],"correct_index":0,"category":"past_simple_irregular"}'::jsonb, 42),
  ('grammar_battle', 'hard', 'present_continuous', '{"question":"Why ___ you watching TV?","options":["are","is","am","do"],"correct_index":0,"category":"present_continuous"}'::jsonb, 49),
  ('grammar_battle', 'very_hard', 'foundations', '{"question":"There ___ many books on the shelf, but only one dictionary.","options":["is","are","am","be"],"correct_index":1,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_hard', 'prepositions', '{"question":"The children are playing ___ the garden right now.","options":["in","at","to","for"],"correct_index":0,"category":"prepositions"}'::jsonb, 34),
  ('grammar_battle', 'very_hard', 'comparatives', '{"question":"Yesterdays test seemed ___ than todays test.","options":["hard","harder","hardest","more hard"],"correct_index":1,"category":"comparatives"}'::jsonb, 51),
  ('grammar_battle', 'very_hard', 'first_conditional', '{"question":"If you ___ hard every day, you will pass the exam.","options":["study","studied","will study","studying"],"correct_index":0,"category":"first_conditional"}'::jsonb, 86),
  ('grammar_battle', 'very_hard', 'first_conditional', '{"question":"If it stops raining, we ___ play outside.","options":["will","do","did","can"],"correct_index":0,"category":"first_conditional"}'::jsonb, 86),
  ('grammar_battle', 'very_hard', 'past_simple_regular', '{"question":"Why ___ you arrive late for school yesterday?","options":["did","do","does","are"],"correct_index":0,"category":"past_simple_regular"}'::jsonb, 41),
  ('grammar_battle', 'very_hard', 'can_ability', '{"question":"My sister ___ run faster than me.","options":["can","cans","is can","am can"],"correct_index":0,"category":"can_ability"}'::jsonb, 51),
  ('grammar_battle', 'very_hard', 'present_continuous', '{"question":"Look! ___ a strange noise coming from the kitchen.","options":["there is","there are","it is","they are"],"correct_index":0,"category":"present_continuous"}'::jsonb, 49),
  ('grammar_battle', 'very_hard', 'first_conditional', '{"question":"If you are not careful, you ___ fall down.","options":["will","are","is","do"],"correct_index":0,"category":"first_conditional"}'::jsonb, 86),
  ('grammar_battle', 'very_hard', 'comparatives', '{"question":"The movie we ___ last night seemed better than I expected.","options":["saw","see","sees","seeing"],"correct_index":0,"category":"comparatives"}'::jsonb, 51),
  ('grammar_battle', 'very_hard', 'past_simple_regular', '{"question":"We waited ___ the bus stop for twenty minutes yesterday.","options":["at","in","to","for"],"correct_index":0,"category":"past_simple_regular"}'::jsonb, 41),
  ('grammar_battle', 'very_hard', 'can_ability', '{"question":"My cat ___ open doors by itself.","options":["can","cans","is can","am can"],"correct_index":0,"category":"can_ability"}'::jsonb, 10),
  ('grammar_battle', 'very_hard', 'foundations', '{"question":"The keys ___ on the table, not in my bag.","options":["am","are","is","be"],"correct_index":1,"category":"foundations"}'::jsonb, 1),
  ('grammar_battle', 'very_hard', 'first_conditional', '{"question":"If the shop ___ closed, we will go home.","options":["is","are","am","be"],"correct_index":0,"category":"first_conditional"}'::jsonb, 86),
  ('grammar_battle', 'very_hard', 'first_conditional', '{"question":"If it ___ tomorrow, we will stay inside and watch movies all day.","options":["rains","rain","rained","raining"],"correct_index":0,"category":"first_conditional"}'::jsonb, 86);
