-- Lesson Library: reusable lesson templates that a teacher/admin can pick
-- from when scheduling an actual lesson (see src/pages/Lessons.jsx), so a
-- recurring curriculum topic doesn't need to be retyped every time.
--
-- Same shape and conventions as lessons/exams/homework in migration 0005:
-- content metadata, not sensitive - every signed-in role can read it,
-- only admin/teacher can write. Optional file reuses the shared
-- 'attachments' storage bucket from migration 0009 rather than adding a
-- new one.
--
-- This migration only adds a new table - it doesn't touch any existing
-- table, column, or policy.

create table if not exists public.lesson_templates (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  level text check (level in ('A', 'B', 'C')),
  file_url text,
  file_name text,
  file_type text,
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

alter table public.lesson_templates enable row level security;

drop policy if exists lesson_templates_read_all on public.lesson_templates;
create policy lesson_templates_read_all on public.lesson_templates for select
  using (auth.uid() is not null);

drop policy if exists lesson_templates_admin_all on public.lesson_templates;
create policy lesson_templates_admin_all on public.lesson_templates for all
  using (is_admin())
  with check (is_admin());

drop policy if exists lesson_templates_teacher_all on public.lesson_templates;
create policy lesson_templates_teacher_all on public.lesson_templates for all
  using (is_teacher())
  with check (is_teacher());
