-- Phase 1 security fixes for Exams (audit findings, 2026-07-26):
--
-- 1. The 'exams' folder in the shared 'attachments' bucket was still in
--    attachments_read's bucket-wide "open to any signed-in user" branch -
--    unlike 'exam-answers' (0014) and 'lesson-pdfs' (0032/0033), it never
--    got a level-scoped read policy. A student could open another level's
--    exam file via its signed URL even though Exams.jsx/MyExams.jsx only
--    ever surface same-level exams in the UI - the restriction was
--    frontend-only.
-- 2. attachments_insert/attachments_update leave 'exam-answers' in the
--    `else true` branch (0014/0032) - any authenticated user can write to
--    any exam-answers/* path, not just their own. The real protection
--    against a forged *submission* is exam_scores RLS (is_own_student()),
--    but the storage object itself is unprotected, unlike every other
--    scoped folder in this bucket.
-- 3. Exams.jsx's grading panel lists every active student regardless of
--    the exam's level (activeStudents has no level filter), unlike
--    MyExams.jsx which does filter client-side. That part of this fix is
--    a frontend-only change (Exams.jsx), included here only as a comment
--    for context - no SQL is required for it.
--
-- Nothing here touches lesson-pdfs, certificates, recognition, attendance,
-- payments, rankings/points, or the exam-answers *read* policy
-- (is_own_exam_answer, untouched and correct). is_admin()/is_teacher()
-- keep unrestricted access to every folder in this bucket, matching the
-- existing authorization model (teacher-level CRUD scoping is a separate,
-- not-yet-approved Phase 2 concern).

-- ============================================================
-- 1. Exam file reads: scope 'exams' folder to the exam's own level
-- ============================================================
--
-- Path format actually generated by uploadAttachment(file, 'exams')
-- (storageBridge.js) is flat - 'exams/{timestamp}-{random}{ext}' - the
-- exam id is never embedded in the path (unlike lesson-pdfs, where the
-- lesson already exists before its PDF is uploaded). So, unlike
-- storage_lesson_id/can_read_lesson_pdf, this can't resolve an id from
-- the path itself; instead it looks up the exams row that owns this exact
-- stored path via exams.file_url, the same way is_own_exam_answer (0033)
-- already matches exam-answers objects via exam_scores.answer_file_url
-- rather than a parsed path segment.
--
-- exams.level is nullable (0005: `level text check (...)`, no not null) -
-- a null-level exam is treated as open to every level, matching the exact
-- same convention already used by can_read_lesson_pdf, can_send_message's
-- exam branch (0009), and MyExams.jsx's own client-side filter
-- (`!e.level || e.level === me.level`). students.level is NOT NULL
-- (0001), so every real student always has exactly one level to compare
-- against.
--
-- A path that matches no exams.file_url (guessed/stale/malformed) simply
-- makes the `exists (...)` false - no error, safe deny, same shape as
-- storage_lesson_id's "return null for anything that doesn't parse".
create or replace function public.can_read_exam_file(p_name text)
returns boolean
language sql
stable
security definer
set search_path = 'public'
as $$
  select exists (
    select 1
    from public.exams e
    join public.students s on s.profile_id = auth.uid()
    where e.file_url = p_name
      and (e.level is null or e.level = s.level)
  );
$$;

revoke execute on function public.can_read_exam_file(text) from public;
grant execute on function public.can_read_exam_file(text) to authenticated;

drop policy if exists attachments_read on storage.objects;
create policy attachments_read on storage.objects for select
  using (
    bucket_id = 'attachments'
    and auth.uid() is not null
    and (
      is_admin()
      or is_teacher()
      -- Every folder except exam-answers/lesson-pdfs/exams keeps the
      -- original bucket-wide "any signed-in user can read" rule -
      -- unchanged from 0033.
      or (
        (storage.foldername(name))[1] is distinct from 'exam-answers'
        and (storage.foldername(name))[1] is distinct from 'lesson-pdfs'
        and (storage.foldername(name))[1] is distinct from 'exams'
      )
      -- exam-answers / lesson-pdfs branches: verbatim from 0033, untouched.
      or public.is_own_exam_answer(name)
      or (
        public.storage_lesson_id(name) is not null
        and public.can_read_lesson_pdf(public.storage_lesson_id(name))
      )
      -- exams: new level-scoped branch.
      or public.can_read_exam_file(name)
    )
  );

-- ============================================================
-- 2. Exam-answer writes: scope 'exam-answers' insert/update to the
--    uploading student's own path
-- ============================================================
--
-- Current path format, MyExams.jsx's handleUpload -> uploadAttachment(file,
-- 'exam-answers') -> storageBridge.js: 'exam-answers/{timestamp}-{random}
-- {ext}', flat, no student id embedded - and the file is uploaded to
-- storage BEFORE submitMyExamAnswer() ever writes/updates the exam_scores
-- row, so there is no existing exam_scores row to join against at INSERT
-- time (unlike the read-side check, which runs after the row exists).
-- Ownership therefore can't be verified by looking anything up in the
-- database at upload time; it has to be readable directly off the path
-- itself, the same way lesson-pdfs embeds {lesson_id} as path segment 2.
--
-- This migration adds an equivalent {student_id} segment to the
-- exam-answers path: 'exam-answers/{student_id}/{timestamp}-{random}
-- {ext}'. The matching frontend change (MyExams.jsx) uploads to
-- `exam-answers/${me.id}` instead of the bare `'exam-answers'` folder -
-- me.id is already available in that component (it's the signed-in
-- user's own linked students.id). Old flat-path objects already in the
-- bucket are untouched and remain readable (is_own_exam_answer matches on
-- the stored exam_scores.answer_file_url column, not the path shape) -
-- this only changes how *new* uploads are named and checked.
create or replace function public.storage_exam_answer_student_id(p_name text)
returns bigint
language sql
immutable
set search_path = 'public'
as $$
  select case
    when (storage.foldername(p_name))[1] = 'exam-answers'
     and (storage.foldername(p_name))[2] ~ '^[0-9]+$'
    then ((storage.foldername(p_name))[2])::bigint
    else null
  end;
$$;

-- Not security definer: it only calls storage_exam_answer_student_id
-- (plain path parsing, no table access) and is_own_student (already a
-- SECURITY DEFINER function, granted to authenticated) - it never touches
-- public.students directly itself, so it doesn't need elevated
-- privileges of its own. Same treatment as storage_lesson_id: pinned
-- search_path, default PUBLIC execute (nothing privileged to guard).
create or replace function public.can_write_exam_answer(p_name text)
returns boolean
language sql
stable
set search_path = 'public'
as $$
  select public.storage_exam_answer_student_id(p_name) is not null
     and public.is_own_student(public.storage_exam_answer_student_id(p_name));
$$;

drop policy if exists attachments_insert on storage.objects;
create policy attachments_insert on storage.objects for insert
  with check (
    bucket_id = 'attachments'
    and auth.uid() is not null
    and (
      case (storage.foldername(name))[1]
        when 'exams' then is_admin() or is_teacher()
        when 'certificate-template' then is_admin()
        when 'lesson-pdfs' then is_admin() or is_teacher()
        when 'exam-answers' then is_admin() or is_teacher() or public.can_write_exam_answer(name)
        else true
      end
    )
  );

drop policy if exists attachments_update on storage.objects;
create policy attachments_update on storage.objects for update
  using (
    bucket_id = 'attachments'
    and auth.uid() is not null
    and (
      case (storage.foldername(name))[1]
        when 'exams' then is_admin() or is_teacher()
        when 'certificate-template' then is_admin()
        when 'lesson-pdfs' then is_admin() or is_teacher()
        when 'exam-answers' then is_admin() or is_teacher() or public.can_write_exam_answer(name)
        else true
      end
    )
  );

-- attachments_delete_admin (admin-only delete, from 0009) is untouched.
--
-- Note on "students cannot modify a graded submission": that rule is (and
-- remains) enforced at the exam_scores table layer, not here -
-- exam_scores_student_update_own (0028) already requires `score is null`
-- in both USING and WITH CHECK, so a student can never repoint
-- exam_scores.answer_file_url at a newly-uploaded object once graded,
-- regardless of what this storage policy allows. can_write_exam_answer
-- only controls whether the storage object itself can be written under
-- the student's own id segment - it doesn't need to duplicate the graded
-- check, since an ungraded-only re-link is already guaranteed by the
-- table policy that was already in place before this migration.
