-- Vocabulary Learning System, Phase 1: the data foundation.
--
-- Vocabulary is owned by lessons (Lesson -> Vocabulary), not a standalone
-- module - lesson_vocabulary.lesson_id is the only thing that scopes a
-- word to anything. id is a UUID, deliberately not the bigint identity
-- pattern used elsewhere in this schema: every future feature (favorites,
-- flashcards, quizzes, AI review, analytics) must reference a word by this
-- id, never by its english text, so a later typo fix/translation edit
-- never breaks anything pointing at it.
--
-- Teacher RLS intentionally matches the existing lesson-resource
-- precedent (lesson-pdfs, 0032): any is_teacher() can manage vocabulary
-- for any lesson, same as any teacher can already attach/replace a
-- lesson's PDF. There is no teacher-lesson ownership concept anywhere in
-- this schema to scope against - introducing one here would be new,
-- undocumented restriction logic invented for this feature alone. If
-- real teacher-lesson assignment is added later, this can be tightened
-- to match without a data model change (id stays the same).

create table if not exists public.lesson_vocabulary (
  id uuid primary key default gen_random_uuid(),
  lesson_id bigint not null references public.lessons (id) on delete cascade,
  english text not null,
  uzbek text not null,
  example text,
  pronunciation text,
  image_path text,
  image_name text,
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists lesson_vocabulary_lesson_id_idx on public.lesson_vocabulary (lesson_id);
create index if not exists lesson_vocabulary_display_order_idx on public.lesson_vocabulary (display_order);

-- Kept separate from lesson_vocabulary itself, per design: a student's
-- favorites are their own data, not an attribute of the word.
create table if not exists public.student_vocabulary_favorites (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students (id) on delete cascade,
  vocabulary_id uuid not null references public.lesson_vocabulary (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (student_id, vocabulary_id)
);

create index if not exists student_vocabulary_favorites_student_id_idx on public.student_vocabulary_favorites (student_id);
create index if not exists student_vocabulary_favorites_vocabulary_id_idx on public.student_vocabulary_favorites (vocabulary_id);

alter table public.lesson_vocabulary enable row level security;
alter table public.student_vocabulary_favorites enable row level security;

-- updated_at is app-relevant audit data, not just a timestamp - keep it
-- accurate on every UPDATE without every caller having to remember to set
-- it (mirrors the plain "set explicitly in the payload" approach used
-- elsewhere in this schema, but as a trigger since teacher CRUD here does
-- partial-field updates from a shared form).
create or replace function public.set_lesson_vocabulary_updated_at()
returns trigger
language plpgsql
set search_path = 'public'
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists lesson_vocabulary_set_updated_at on public.lesson_vocabulary;
create trigger lesson_vocabulary_set_updated_at
  before update on public.lesson_vocabulary
  for each row execute function public.set_lesson_vocabulary_updated_at();

-- ---------- lesson_vocabulary ----------

drop policy if exists lesson_vocabulary_admin_all on public.lesson_vocabulary;
create policy lesson_vocabulary_admin_all on public.lesson_vocabulary for all
  using (is_admin()) with check (is_admin());

drop policy if exists lesson_vocabulary_teacher_all on public.lesson_vocabulary;
create policy lesson_vocabulary_teacher_all on public.lesson_vocabulary for all
  using (is_teacher()) with check (is_teacher());

-- A student may read an active word only for a lesson whose level matches
-- their own (or the lesson has no level restriction) - identical scoping
-- rule to the lesson-pdfs storage policy in 0032, applied here to the row
-- itself instead of a storage path.
drop policy if exists lesson_vocabulary_student_read on public.lesson_vocabulary;
create policy lesson_vocabulary_student_read on public.lesson_vocabulary for select
  using (
    is_active
    and exists (
      select 1
      from public.lessons l
      join public.students s on s.profile_id = auth.uid()
      where l.id = lesson_vocabulary.lesson_id
        and (l.level is null or l.level = s.level)
    )
  );

-- ---------- student_vocabulary_favorites ----------

drop policy if exists student_vocabulary_favorites_admin_all on public.student_vocabulary_favorites;
create policy student_vocabulary_favorites_admin_all on public.student_vocabulary_favorites for all
  using (is_admin()) with check (is_admin());

drop policy if exists student_vocabulary_favorites_self_read on public.student_vocabulary_favorites;
create policy student_vocabulary_favorites_self_read on public.student_vocabulary_favorites for select
  using (public.is_own_student(student_id));

drop policy if exists student_vocabulary_favorites_self_insert on public.student_vocabulary_favorites;
create policy student_vocabulary_favorites_self_insert on public.student_vocabulary_favorites for insert
  with check (public.is_own_student(student_id));

drop policy if exists student_vocabulary_favorites_self_delete on public.student_vocabulary_favorites;
create policy student_vocabulary_favorites_self_delete on public.student_vocabulary_favorites for delete
  using (public.is_own_student(student_id));

-- ---------- storage: optional per-word image, same private 'attachments'
-- bucket as lesson-pdfs, under 'vocabulary-images/{lesson_id}/{filename}'.
-- Mirrors 0032's storage_lesson_id() exactly but for this folder name -
-- kept as a separate function (rather than parameterizing the folder)
-- because storage_lesson_id() is immutable and already relied upon
-- as-is by the lesson-pdfs branch of attachments_read/insert/update.

create or replace function public.storage_vocabulary_lesson_id(p_name text)
returns bigint
language sql
immutable
set search_path = 'public'
as $$
  select case
    when (storage.foldername(p_name))[1] = 'vocabulary-images'
     and (storage.foldername(p_name))[2] ~ '^[0-9]+$'
    then ((storage.foldername(p_name))[2])::bigint
    else null
  end;
$$;

drop policy if exists attachments_read on storage.objects;
create policy attachments_read on storage.objects for select
  using (
    bucket_id = 'attachments'
    and auth.uid() is not null
    and (
      is_admin()
      or is_teacher()
      or (
        (storage.foldername(name))[1] is distinct from 'exam-answers'
        and (storage.foldername(name))[1] is distinct from 'lesson-pdfs'
        and (storage.foldername(name))[1] is distinct from 'vocabulary-images'
      )
      or exists (
        select 1
        from public.exam_scores es
        join public.students s on s.id = es.student_id
        where s.profile_id = auth.uid()
          and es.answer_file_url = name
      )
      or (
        public.storage_lesson_id(name) is not null
        and exists (
          select 1
          from public.lessons l
          join public.students s on s.profile_id = auth.uid()
          where l.id = public.storage_lesson_id(name)
            and (l.level is null or l.level = s.level)
        )
      )
      -- vocabulary-images: same level-scoped rule as lesson-pdfs above.
      or (
        public.storage_vocabulary_lesson_id(name) is not null
        and exists (
          select 1
          from public.lessons l
          join public.students s on s.profile_id = auth.uid()
          where l.id = public.storage_vocabulary_lesson_id(name)
            and (l.level is null or l.level = s.level)
        )
      )
    )
  );

drop policy if exists attachments_insert on storage.objects;
create policy attachments_insert on storage.objects for insert
  with check (
    bucket_id = 'attachments'
    and auth.uid() is not null
    and (
      case (storage.foldername(name))[1]
        when 'exams' then is_admin() or is_teacher()
        when 'certificate-template' then is_admin()
        when 'lesson-pdfs' then is_admin() or is_teacher()
        when 'vocabulary-images' then is_admin() or is_teacher()
        else true
      end
    )
  );

drop policy if exists attachments_update on storage.objects;
create policy attachments_update on storage.objects for update
  using (
    bucket_id = 'attachments'
    and auth.uid() is not null
    and (
      case (storage.foldername(name))[1]
        when 'exams' then is_admin() or is_teacher()
        when 'certificate-template' then is_admin()
        when 'lesson-pdfs' then is_admin() or is_teacher()
        when 'vocabulary-images' then is_admin() or is_teacher()
        else true
      end
    )
  );

-- attachments_delete_admin (admin-only delete, from 0009) already covers
-- the whole bucket, including vocabulary-images - untouched.
