-- Curriculum foundation: the master 120-lesson yearly plan, authored once
-- and shared across all levels/groups. This is deliberately separate from
-- the existing `lessons` table (which represents actual taught classes,
-- see 0005) - curriculum_lessons is the "what the academy teaches all
-- year" template; `lessons` stays "what Dave actually taught on a given
-- date to a given group". Session 2 will add a nullable FK from `lessons`
-- to this table to connect the two; nothing here touches `lessons`,
-- `homework`, `exams`, `lesson_attendance`, or any storage/PDF path.
--
-- No seed data in this migration - only 20 of the 120 titles were
-- confirmed at authoring time, and the exam lesson_type mapping
-- (writing_exam/oral_exam split vs a single row) was still unresolved.
-- Seeding happens in a follow-up migration once the full list and type
-- mapping are final, so this table's contents are inserted in one
-- consistent pass rather than patched incrementally.

create table if not exists public.curriculum_lessons (
  id bigint generated by default as identity primary key,
  lesson_number int not null unique check (lesson_number between 1 and 120),
  title text not null,
  month int not null check (month between 1 and 12),
  lesson_type text not null default 'normal'
    check (lesson_type in ('normal', 'review', 'writing_exam', 'oral_exam', 'activity', 'final_exam')),
  description text,
  created_at timestamptz not null default now()
);

alter table public.curriculum_lessons enable row level security;

-- Same read/write shape as `lessons` (0005): any authenticated user
-- (including students) can read the curriculum, only admin/teacher can
-- write it.
create policy curriculum_lessons_read_all on public.curriculum_lessons
  for select using (auth.uid() is not null);

create policy curriculum_lessons_admin_teacher_write on public.curriculum_lessons
  for all
  using (is_admin() or is_teacher())
  with check (is_admin() or is_teacher());
