-- Lesson Work Submission, Phase 1 (foundation only): a student uploads up
-- to 5 photos of practice work for a specific lesson and submits it for
-- later teacher review. This is intentionally separate from the existing
-- Homework domain (homework/homework_status/homework_submission_files) -
-- lesson work is keyed directly to lessons.id, not a homework assignment,
-- and nothing here modifies any homework table or policy.
--
-- Out of scope for this phase (deferred): teacher review UI, points
-- awarding (no write to point_transactions), feedback, resubmission/
-- delete-after-review flows. status only distinguishes 'submitted' from
-- 'reviewed' as a foundation for phase 2 to build on.
--
-- Mirrors homework_submission_files' proven shape (0009/0041): denormalized
-- student_id on the files table (avoids a join for RLS/ownership checks),
-- a SECURITY DEFINER cap function using a COUNT subquery so the 5-file
-- limit is safe under concurrent single-row inserts (see comment on
-- can_add_lesson_work_submission_file below - same reasoning as
-- can_add_homework_submission_file).

create table if not exists public.lesson_work_submissions (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  lesson_id bigint not null references public.lessons(id) on delete cascade,
  status text not null default 'submitted' check (status in ('submitted', 'reviewed')),
  submitted_at timestamptz not null default now(),
  unique (student_id, lesson_id)
);

create index if not exists lesson_work_submissions_lesson_idx
  on public.lesson_work_submissions (lesson_id);

alter table public.lesson_work_submissions enable row level security;

drop policy if exists lesson_work_submissions_admin_all on public.lesson_work_submissions;
create policy lesson_work_submissions_admin_all on public.lesson_work_submissions for all
  using (is_admin()) with check (is_admin());

-- Teacher gets full access now (matches the existing homework_status/
-- homework_submission_files "teacher_all" precedent) even though the
-- review UI itself isn't built until phase 2 - RLS is provisioned ahead
-- of the frontend, not the other way around.
drop policy if exists lesson_work_submissions_teacher_all on public.lesson_work_submissions;
create policy lesson_work_submissions_teacher_all on public.lesson_work_submissions for all
  using (is_teacher()) with check (is_teacher());

drop policy if exists lesson_work_submissions_self_read on public.lesson_work_submissions;
create policy lesson_work_submissions_self_read on public.lesson_work_submissions for select
  using (public.is_own_student(student_id));

-- A student may only create their own submission, and only in the
-- 'submitted' state - they can never insert a row already marked
-- 'reviewed'. No student update/delete policy: phase 1 has no
-- resubmission or self-service edit flow.
drop policy if exists lesson_work_submissions_student_insert on public.lesson_work_submissions;
create policy lesson_work_submissions_student_insert on public.lesson_work_submissions for insert
  with check (public.is_own_student(student_id) and status = 'submitted');

create table if not exists public.lesson_work_submission_files (
  id bigint generated by default as identity primary key,
  submission_id bigint not null references public.lesson_work_submissions(id) on delete cascade,
  student_id bigint not null references public.students(id) on delete cascade,
  file_url text not null,
  file_name text,
  position smallint not null default 0,
  created_at timestamptz not null default now(),
  unique (submission_id, file_url)
);

create index if not exists lesson_work_submission_files_submission_idx
  on public.lesson_work_submission_files (submission_id);

alter table public.lesson_work_submission_files enable row level security;

-- Server-side 5-file cap, same shape as can_add_homework_submission_file
-- (0041): a student may add a file only to their own, still-'submitted'
-- (not yet reviewed) submission, and only while fewer than 5 rows already
-- exist for that submission_id. Sequential single-row inserts (see
-- storageBridge.js) each see the previous insert's committed row, so the
-- COUNT is race-safe the same way homework's is - a single multi-row
-- INSERT would NOT be safe here (all rows would see the same pre-insert
-- count), which is why the frontend must insert one file per request.
create or replace function public.can_add_lesson_work_submission_file(p_submission_id bigint, p_student_id bigint)
returns boolean
language sql
stable
security definer
set search_path = 'public'
as $$
  select
    public.is_own_student(p_student_id)
    and exists (
      select 1 from public.lesson_work_submissions s
      where s.id = p_submission_id
        and s.student_id = p_student_id
        and s.status = 'submitted'
    )
    and (
      select count(*) from public.lesson_work_submission_files f
      where f.submission_id = p_submission_id
    ) < 5
$$;

revoke execute on function public.can_add_lesson_work_submission_file(bigint, bigint) from public;
grant execute on function public.can_add_lesson_work_submission_file(bigint, bigint) to authenticated;

drop policy if exists lesson_work_submission_files_admin_all on public.lesson_work_submission_files;
create policy lesson_work_submission_files_admin_all on public.lesson_work_submission_files for all
  using (is_admin()) with check (is_admin());

drop policy if exists lesson_work_submission_files_teacher_all on public.lesson_work_submission_files;
create policy lesson_work_submission_files_teacher_all on public.lesson_work_submission_files for all
  using (is_teacher()) with check (is_teacher());

drop policy if exists lesson_work_submission_files_self_read on public.lesson_work_submission_files;
create policy lesson_work_submission_files_self_read on public.lesson_work_submission_files for select
  using (public.is_own_student(student_id));

drop policy if exists lesson_work_submission_files_student_insert on public.lesson_work_submission_files;
create policy lesson_work_submission_files_student_insert on public.lesson_work_submission_files for insert
  with check (public.can_add_lesson_work_submission_file(submission_id, student_id));

-- A student may remove one of their own files while the submission is
-- still 'submitted' (not yet reviewed) - e.g. to swap out a bad photo
-- before the teacher looks at it. Same "cannot touch it once reviewed"
-- gate as homework's file-delete policy.
drop policy if exists lesson_work_submission_files_student_delete on public.lesson_work_submission_files;
create policy lesson_work_submission_files_student_delete on public.lesson_work_submission_files for delete
  using (
    public.is_own_student(student_id)
    and exists (
      select 1 from public.lesson_work_submissions s
      where s.id = lesson_work_submission_files.submission_id
        and s.status = 'submitted'
    )
  );

-- ============================================================
-- Storage: new 'lesson-work/{student_id}/...' path in the existing shared
-- 'attachments' bucket, following the exact convention exam-answers/
-- homework-answers already use (0036/0039) - without adding this branch,
-- the bucket's catch-all "any signed-in user can read/write" default
-- (0009/0039) would apply to this new folder, which is not acceptable for
-- student photo submissions.
-- ============================================================

create or replace function public.storage_lesson_work_student_id(p_name text)
returns bigint
language sql
immutable
set search_path = 'public'
as $$
  select case
    when (storage.foldername(p_name))[1] = 'lesson-work'
     and (storage.foldername(p_name))[2] ~ '^[0-9]+$'
    then ((storage.foldername(p_name))[2])::bigint
    else null
  end;
$$;

-- Not security definer, same reasoning as can_write_homework_answer: it
-- only calls storage_lesson_work_student_id (plain path parsing) and
-- is_own_student (already security definer, already granted to
-- authenticated) - it never touches public.students directly.
create or replace function public.can_access_lesson_work_file(p_name text)
returns boolean
language sql
stable
set search_path = 'public'
as $$
  select public.storage_lesson_work_student_id(p_name) is not null
     and public.is_own_student(public.storage_lesson_work_student_id(p_name));
$$;

-- ADDITIVE REWRITE (audited against live production, not local files):
-- `supabase migration list` / the local 0039/0041/0046 history is NOT
-- what's actually live. A direct `pg_policies` read on production
-- (2026-08-09) showed attachments_read/insert/update already diverged
-- from every local migration file - notably a 'vocabulary-images' branch
-- that exists in no local file, and the ABSENCE of the homework/
-- homework-answers/chat restrictions that 0039/0046 add locally.
--
-- That gap (homework-answers and chat currently unprotected in prod) is
-- real but explicitly out of scope for this migration - see the Lesson
-- Work Submission Phase 1 session notes. This migration does not restore,
-- remove, or otherwise touch it; that's a separate future security-
-- reconciliation task. The three policies below are the verbatim live
-- conditions (captured via `pg_policies.qual`/`with_check`) with exactly
-- one addition each: a 'lesson-work' branch. Every other condition -
-- including the missing homework/chat branches - is left exactly as it
-- was found live, not as local files imply it should be.

drop policy if exists attachments_read on storage.objects;
create policy attachments_read on storage.objects for select
  using (
    bucket_id = 'attachments'
    and auth.uid() is not null
    and (
      is_admin()
      or is_teacher()
      or (
        (storage.foldername(name))[1] is distinct from 'exam-answers'
        and (storage.foldername(name))[1] is distinct from 'lesson-pdfs'
        and (storage.foldername(name))[1] is distinct from 'vocabulary-images'
        and (storage.foldername(name))[1] is distinct from 'lesson-work'
      )
      or is_own_exam_answer(name)
      or (
        storage_lesson_id(name) is not null
        and can_read_lesson_pdf(storage_lesson_id(name))
      )
      or (
        storage_vocabulary_lesson_id(name) is not null
        and can_read_lesson_vocabulary(storage_vocabulary_lesson_id(name))
      )
      or public.can_access_lesson_work_file(name)
    )
  );

drop policy if exists attachments_insert on storage.objects;
create policy attachments_insert on storage.objects for insert
  with check (
    bucket_id = 'attachments'
    and auth.uid() is not null
    and (
      case (storage.foldername(name))[1]
        when 'exams' then is_admin() or is_teacher()
        when 'certificate-template' then is_admin()
        when 'lesson-pdfs' then is_admin() or is_teacher()
        when 'vocabulary-images' then is_admin() or is_teacher()
        when 'lesson-work' then is_admin() or is_teacher() or public.can_access_lesson_work_file(name)
        else true
      end
    )
  );

drop policy if exists attachments_update on storage.objects;
create policy attachments_update on storage.objects for update
  using (
    bucket_id = 'attachments'
    and auth.uid() is not null
    and (
      case (storage.foldername(name))[1]
        when 'exams' then is_admin() or is_teacher()
        when 'certificate-template' then is_admin()
        when 'lesson-pdfs' then is_admin() or is_teacher()
        when 'vocabulary-images' then is_admin() or is_teacher()
        when 'lesson-work' then is_admin() or is_teacher() or public.can_access_lesson_work_file(name)
        else true
      end
    )
  );

-- attachments_delete_admin (admin-only delete, from 0009) is untouched -
-- not captured/verified here since this migration doesn't modify it.
