-- Word Scramble game, MVP. First of the "Game & Practice System" family
-- (see architecture/security validation sessions, 2026-08-10). Reuses
-- lesson_vocabulary/lessons (no duplicate word list) and the existing
-- achievement engine (bump_student_metric/evaluate_achievements, 0105-0107)
-- for any reward hook - this migration adds no new points/reward mechanism
-- and never writes point_transactions or students.points directly.
--
-- Core rule this migration exists to enforce: the client is never trusted
-- to report its own score. get_word_scramble_round() hands out only word
-- ids + the scrambled text needed to render the round; the English word
-- itself is not secret (students can already read it via listAllVocabulary
-- under RLS - see can_read_lesson_vocabulary, 0048/0049), but *correctness*
-- is decided nowhere except submit_word_scramble_round(), which re-reads
-- lesson_vocabulary.english server-side. student_id is always derived from
-- auth.uid(), never accepted as a parameter.

create table if not exists public.game_sessions (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  game_type text not null,
  score numeric not null,
  words_correct integer not null,
  words_total integer not null,
  played_at timestamptz not null default now()
);

create index if not exists game_sessions_student_played_idx
  on public.game_sessions (student_id, played_at desc);

alter table public.game_sessions enable row level security;

drop policy if exists game_sessions_admin_all on public.game_sessions;
create policy game_sessions_admin_all on public.game_sessions for all
  using (is_admin()) with check (is_admin());

drop policy if exists game_sessions_teacher_select on public.game_sessions;
create policy game_sessions_teacher_select on public.game_sessions for select
  using (is_teacher());

-- Read-only for students - deliberately no insert policy. The only writer
-- is submit_word_scramble_round() below, running as SECURITY DEFINER,
-- which bypasses RLS entirely. A student calling
-- supabase.from('game_sessions').insert(...) directly gets a permission
-- denied, same shape as student_metric_snapshots today.
drop policy if exists game_sessions_self_select on public.game_sessions;
create policy game_sessions_self_select on public.game_sessions for select
  using (public.is_own_student(student_id));

-- Hands out a round: 8 random single-word, alphabetic vocabulary entries
-- from lessons at the caller's own level (or level-agnostic lessons),
-- i.e. the exact same set can_read_lesson_vocabulary() already lets this
-- student SELECT directly - this function doesn't expose anything new,
-- it just pre-filters to words that scramble sensibly (no phrases,
-- no punctuation) and randomizes selection server-side so the "8 words"
-- come from the authoritative set, not a client-chosen list.
create or replace function public.get_word_scramble_round()
returns table (id uuid, english text)
language sql
stable
security definer
set search_path = 'public'
as $$
  select v.id, v.english
  from public.lesson_vocabulary v
  join public.lessons l on l.id = v.lesson_id
  join public.students s on s.profile_id = auth.uid()
  where v.is_active
    and (l.level is null or l.level = s.level)
    and v.english ~ '^[A-Za-z]+$'
    and length(v.english) >= 3
  order by random()
  limit 8;
$$;

revoke execute on function public.get_word_scramble_round() from public;
grant execute on function public.get_word_scramble_round() to authenticated;

-- Grades a completed round. p_answers shape:
--   [{ "vocabulary_id": "<uuid>", "answer": "<text>", "used_hint": bool, "skipped": bool }, ...]
--
-- Client-controlled: which vocabulary_id it's answering, its typed answer,
-- and the hint/skip flags (informational only - they affect scoring, not
-- correctness). Everything else - student_id, correctness, words_correct,
-- score, the game_sessions row, the achievement metric bump, and any
-- resulting achievement/bonus points - is derived here, server-side, and
-- cannot be supplied by the caller. Every vocabulary_id is re-checked
-- against the caller's own level (not just "does this uuid exist") so a
-- student can't inflate their metric by answering words from another
-- level's curriculum.
--
-- Scoring: 10 points per correct answer, 5 if a hint was used on that
-- word, 0 for incorrect or skipped. Simple and stated here rather than
-- configurable - MVP, not a scoring engine.
create or replace function public.submit_word_scramble_round(p_answers jsonb)
returns jsonb
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_student_id bigint;
  v_level text;
  v_words_correct integer := 0;
  v_words_total integer := 0;
  v_score numeric := 0;
  v_results jsonb := '[]'::jsonb;
  r record;
  v_correct boolean;
  v_points numeric;
  v_session_id bigint;
  v_is_new_best boolean;
begin
  select id, level into v_student_id, v_level from public.students where profile_id = auth.uid();
  if v_student_id is null then
    raise exception 'No student record for the current user';
  end if;

  for r in
    select
      (a->>'vocabulary_id')::uuid as vocabulary_id,
      a->>'answer' as answer,
      coalesce((a->>'used_hint')::boolean, false) as used_hint,
      coalesce((a->>'skipped')::boolean, false) as skipped
    from jsonb_array_elements(p_answers) as a
  loop
    v_words_total := v_words_total + 1;

    -- Re-validate the word belongs to this student's own level (same
    -- predicate as can_read_lesson_vocabulary) - a vocabulary_id from a
    -- different level's curriculum is simply excluded, not graded.
    select (not r.skipped) and lower(trim(r.answer)) = lower(v.english)
      into v_correct
    from public.lesson_vocabulary v
    join public.lessons l on l.id = v.lesson_id
    where v.id = r.vocabulary_id
      and v.is_active
      and (l.level is null or l.level = v_level);

    v_correct := coalesce(v_correct, false);

    if v_correct then
      v_words_correct := v_words_correct + 1;
      v_points := case when r.used_hint then 5 else 10 end;
      v_score := v_score + v_points;
    end if;

    v_results := v_results || jsonb_build_object('vocabulary_id', r.vocabulary_id, 'correct', v_correct);
  end loop;

  select v_score > coalesce(max(score), -1)
    into v_is_new_best
  from public.game_sessions
  where student_id = v_student_id and game_type = 'word_scramble';

  insert into public.game_sessions (student_id, game_type, score, words_correct, words_total)
  values (v_student_id, 'word_scramble', v_score, v_words_correct, v_words_total)
  returning id into v_session_id;

  perform public.bump_student_metric(v_student_id, 'game_words_scrambled_correct', v_words_correct);
  perform public.evaluate_achievements(v_student_id);

  return jsonb_build_object(
    'session_id', v_session_id,
    'score', v_score,
    'words_correct', v_words_correct,
    'words_total', v_words_total,
    'is_new_best', coalesce(v_is_new_best, true),
    'results', v_results
  );
end;
$$;

revoke execute on function public.submit_word_scramble_round(jsonb) from public;
grant execute on function public.submit_word_scramble_round(jsonb) to authenticated;
