-- Reconstructed historical migration. This file was never committed to the
-- repository when originally applied to production on 2026-08-10 (ledger
-- versions 20260810100503_dictionary_foundation / 0116_dictionary_foundation
-- both point at this same logical change - see migration-ledger archaeology
-- session 2026-08-16). Rebuilt verbatim from the live production schema via
-- read-only introspection, not invented: information_schema.columns,
-- pg_indexes, pg_constraint, pg_policies, pg_trigger, information_schema
-- role_table_grants for public.dictionary_entries. No speculative columns.

-- pg_trgm is enabled in production but, like this table, was never
-- committed as a migration file (undocumented gap found during the same
-- archaeology pass) - creating it here since this is its first real use.
create extension if not exists pg_trgm with schema public;

create table public.dictionary_entries (
  id bigint generated by default as identity primary key,
  english text not null,
  uzbek text not null,
  pronunciation text,
  part_of_speech text,
  example text,
  example_uzbek text,
  usage_note text,
  alternate_translations text[],
  difficulty text check (difficulty in ('beginner', 'intermediate', 'advanced')),
  audio_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index dictionary_entries_english_lower_idx on public.dictionary_entries (lower(english));
create index dictionary_entries_english_trgm_idx on public.dictionary_entries using gin (english gin_trgm_ops);
create index dictionary_entries_uzbek_trgm_idx on public.dictionary_entries using gin (uzbek gin_trgm_ops);

alter table public.dictionary_entries enable row level security;

create policy dictionary_entries_read_all
  on public.dictionary_entries
  for select
  using (auth.uid() is not null);

create policy dictionary_entries_admin_teacher_write
  on public.dictionary_entries
  for all
  using (is_admin() or is_teacher())
  with check (is_admin() or is_teacher());

create function public.set_dictionary_entries_updated_at()
returns trigger
language plpgsql
set search_path to 'public'
as $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

create trigger dictionary_entries_set_updated_at
  before update on public.dictionary_entries
  for each row
  execute function public.set_dictionary_entries_updated_at();

grant select, insert, update, delete, truncate, references, trigger
  on public.dictionary_entries to anon, authenticated, service_role;
