-- Payment deadline history: tracks changes to a student's recurring payment day
-- so that historical billing periods can use the deadline that was in effect
-- at the time, while future periods use the current deadline.
--
-- This fixes the bug where changing payment_deadline (e.g., 1 -> 11)
-- retroactively shifted all historical billing periods, making paid months
-- appear unpaid.
--
-- The table records each deadline change with an effective date.
-- Historical billing logic will use this to determine which deadline
-- applies to each billing period.

create table if not exists public.student_payment_deadline_history (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students (id) on delete cascade,
  old_deadline integer not null check (old_deadline between 1 and 31),
  new_deadline integer not null check (new_deadline between 1 and 31),
  effective_date timestamptz not null default now(),
  changed_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

create index if not exists student_payment_deadline_history_student_effective_idx
  on public.student_payment_deadline_history (student_id, effective_date);

alter table public.student_payment_deadline_history enable row level security;

-- Admin full access
drop policy if exists student_payment_deadline_history_admin_all on public.student_payment_deadline_history;
create policy student_payment_deadline_history_admin_all on public.student_payment_deadline_history
  for all using (is_admin()) with check (is_admin());

-- Students can read their own history
drop policy if exists student_payment_deadline_history_self_read on public.student_payment_deadline_history;
create policy student_payment_deadline_history_self_read on public.student_payment_deadline_history
  for select using (public.is_own_student(student_payment_deadline_history.student_id));

-- Teachers can read history for their students
drop policy if exists student_payment_deadline_history_teacher_read on public.student_payment_deadline_history;
create policy student_payment_deadline_history_teacher_read on public.student_payment_deadline_history
  for select using (
    exists (
      select 1 from public.students s
      where s.id = student_payment_deadline_history.student_id
        and s.group_name is not null
        and exists (
          select 1 from public.teacher_group_assignments tga
          where tga.teacher_id = auth.uid()
            and tga.level = s.level
        )
    )
  );

-- Helper function: get the payment deadline that was effective on a given date
-- for a specific student. Returns the deadline in effect at that moment.
create or replace function public.get_payment_deadline_at_date(p_student_id bigint, p_at_date timestamptz)
returns integer
language plpgsql
stable
security definer
set search_path = 'public'
as $$
declare
  v_current_deadline integer;
  v_history_deadline integer;
begin
  -- Get current deadline from students table
  select payment_deadline into v_current_deadline
  from public.students
  where id = p_student_id;

  if not found then
    raise exception 'Student % not found', p_student_id;
  end if;

  -- Check history for a more specific deadline at the given date
  -- We want the most recent change that occurred ON OR BEFORE p_at_date
  select new_deadline into v_history_deadline
  from public.student_payment_deadline_history
  where student_id = p_student_id
    and effective_date <= p_at_date
  order by effective_date desc
  limit 1;

  if found then
    return v_history_deadline;
  else
    return v_current_deadline;
  end if;
end;
$$;

revoke execute on function public.get_payment_deadline_at_date(bigint, timestamptz) from public;
revoke execute on function public.get_payment_deadline_at_date(bigint, timestamptz) from anon;
grant execute on function public.get_payment_deadline_at_date(bigint, timestamptz) to authenticated;

-- Helper function: get all deadline changes for a student ordered by effective date
create or replace function public.get_student_payment_deadline_history(p_student_id bigint)
returns table(
  id bigint,
  old_deadline integer,
  new_deadline integer,
  effective_date timestamptz,
  changed_by uuid,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = 'public'
as $$
begin
  if not (is_admin() or public.is_own_student(p_student_id)) then
    raise exception 'Unauthorized';
  end if;

  return query
    select h.id, h.old_deadline, h.new_deadline, h.effective_date, h.changed_by, h.created_at
    from public.student_payment_deadline_history h
    where h.student_id = p_student_id
    order by h.effective_date;
end;
$$;

revoke execute on function public.get_student_payment_deadline_history(bigint) from public;
revoke execute on function public.get_student_payment_deadline_history(bigint) from anon;
grant execute on function public.get_student_payment_deadline_history(bigint) to authenticated;