-- Seed historical payment deadline changes from the August 2026 batch shift
--
-- The administrator confirmed a universal +10 day shift for all active students'
-- recurring payment deadlines, performed as a single batch operation "around
-- August 2026". Original deadlines are reconstructed as:
--   OLD DEADLINE = CURRENT DEADLINE - 10 DAYS
-- with correct month rollover.
--
-- Admin-explicitly confirmed:
--   Dalia (student 3): 5 → 26
--   Maya (student 43): 3 → 23
--
-- For all other students, original deadlines are mathematically reconstructed
-- using the confirmed formula with July 2026 (31 days) as the previous month
-- for rollover calculations, consistent with 4 of 5 admin-provided examples.
--
-- Effective date: 2026-08-01 00:00:00+05:00 (Asia/Tashkent)
-- This is the start of "August 2026" per administrator's "around August 2026"
-- statement. Using the month start is conservative: it ensures all August
-- billing periods use the historical (original) deadlines, preserving paid
-- status for all known August/September payments.
--
-- Changed by: Dave (admin profile f7952e64-bde0-4c12-b9bc-cf1b5e534514)
-- Date of batch operation: around August 2026 (administrator statement)

-- First, ensure the history table exists (idempotent with 0210)
create table if not exists public.student_payment_deadline_history (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students (id) on delete cascade,
  old_deadline integer not null check (old_deadline between 1 and 31),
  new_deadline integer not null check (new_deadline between 1 and 31),
  effective_date timestamptz not null default now(),
  changed_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

create index if not exists student_payment_deadline_history_student_effective_idx
  on public.student_payment_deadline_history (student_id, effective_date);

alter table public.student_payment_deadline_history enable row level security;

drop policy if exists student_payment_deadline_history_admin_all on public.student_payment_deadline_history;
create policy student_payment_deadline_history_admin_all on public.student_payment_deadline_history
  for all using (is_admin()) with check (is_admin());

drop policy if exists student_payment_deadline_history_self_read on public.student_payment_deadline_history;
create policy student_payment_deadline_history_self_read on public.student_payment_deadline_history
  for select using (public.is_own_student(student_payment_deadline_history.student_id));

drop policy if exists student_payment_deadline_history_teacher_read on public.student_payment_deadline_history;
create policy student_payment_deadline_history_teacher_read on public.student_payment_deadline_history
  for select using (
    exists (
      select 1 from public.students s
      where s.id = student_payment_deadline_history.student_id
        and s.group_name is not null
        and exists (
          select 1 from public.teacher_group_assignments tga
          where tga.teacher_id = auth.uid()
            and tga.level = s.level
        )
    )
  );

-- Seed historical deadline changes for all 35 active students
-- Effective date: 2026-08-01 00:00:00+05:00 (Asia/Tashkent)
-- Changed by: Dave (admin profile f7952e64-bde0-4c12-b9bc-cf1b5e534514)

insert into public.student_payment_deadline_history
  (student_id, old_deadline, new_deadline, effective_date, changed_by)
values
  -- Dalia: explicitly confirmed 5 → 26
  (3, 26, 5, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  -- Maya: explicitly confirmed 3 → 23
  (43, 23, 3, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  -- Mathematically reconstructed (July 2026 = 31 days previous month)
  -- Formula: if current > 10 then current - 10 else 31 - (10 - current)
  (1, 16, 26, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (2, 22, 1, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (4, 26, 5, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (6, 26, 5, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (8, 30, 10, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (9, 9, 19, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (10, 30, 10, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (11, 6, 16, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (14, 28, 8, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (16, 9, 19, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (17, 29, 9, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (19, 11, 21, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (20, 5, 15, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (21, 19, 29, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (24, 4, 14, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (25, 4, 14, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (27, 3, 13, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (28, 25, 4, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (30, 9, 19, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (31, 12, 22, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (32, 12, 22, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (33, 7, 17, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (34, 10, 20, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (35, 12, 22, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (37, 25, 4, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (38, 14, 24, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (44, 22, 1, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (46, 6, 16, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (49, 6, 16, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (50, 6, 16, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (59, 4, 14, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (62, 11, 21, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514'),
  (86, 26, 5, '2026-08-01 00:00:00+05:00', 'f7952e64-bde0-4c12-b9bc-cf1b5e534514')
on conflict do nothing;

-- Verify the seed
-- select student_id, old_deadline, new_deadline, effective_date
-- from student_payment_deadline_history
-- order by student_id;