-- New Semester Billing Reset: Add semester_start_date to track billing cycle resets
-- when students are reactivated after being inactive.
--
-- The problem: billing_periods_historical() generates periods continuously from
-- join_date, but students who were inactive (e.g., August) and then reactivated
-- with a new payment date should have their billing cycle restart from the new
-- payment date, not continue accumulating from join_date.
--
-- Solution: Add semester_start_date column to students. When a student is
-- reactivated (Inactive -> Active) with a new payment date, set
-- semester_start_date to the new payment date. billing_periods_historical()
-- will then generate periods from semester_start_date instead of join_date.

-- Add semester_start_date column to students (defaults to join_date for existing students)
alter table public.students
  add column if not exists semester_start_date date;

-- Backfill existing students: semester_start_date = join_date for all existing students
update public.students
set semester_start_date = join_date
where semester_start_date is null;

-- History table to track billing cycle resets (semester starts)
-- This provides audit trail and enables historical reconstruction
create table if not exists public.student_semester_start_history (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students (id) on delete cascade,
  old_semester_start_date date,
  new_semester_start_date date not null,
  effective_date timestamptz not null default now(),
  reason text, -- e.g., 'reactivation after inactivity', 'new semester', 'manual reset'
  changed_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

create index if not exists student_semester_start_history_student_effective_idx
  on public.student_semester_start_history (student_id, effective_date);

alter table public.student_semester_start_history enable row level security;

-- Admin full access
drop policy if exists student_semester_start_history_admin_all on public.student_semester_start_history;
create policy student_semester_start_history_admin_all on public.student_semester_start_history
  for all using (is_admin()) with check (is_admin());

-- Students can read their own history
drop policy if exists student_semester_start_history_self_read on public.student_semester_start_history;
create policy student_semester_start_history_self_read on public.student_semester_start_history
  for select using (public.is_own_student(student_semester_start_history.student_id));

-- Teachers can read history for their students
drop policy if exists student_semester_start_history_teacher_read on public.student_semester_start_history;
create policy student_semester_start_history_teacher_read on public.student_semester_start_history
  for select using (
    exists (
      select 1 from public.students s
      where s.id = student_semester_start_history.student_id
        and s.group_name is not null
        and exists (
          select 1 from public.teacher_group_assignments tga
          where tga.teacher_id = auth.uid()
            and tga.level = s.level
        )
    )
  );

-- Helper function: get the semester start date that was effective on a given date
-- Returns the most recent semester_start_date change on or before the given date,
-- or the student's current semester_start_date if no history exists before that date.
create or replace function public.get_semester_start_at_date(p_student_id bigint, p_at_date timestamptz)
returns date
language plpgsql
stable
security definer
set search_path = 'public'
as $$
declare
  v_current_start_date date;
  v_history_start_date date;
begin
  -- Get current semester_start_date from students table
  select semester_start_date into v_current_start_date
  from public.students
  where id = p_student_id;

  if not found then
    raise exception 'Student % not found', p_student_id;
  end if;

  -- Check history for a more specific start date at the given date
  -- We want the most recent change that occurred ON OR BEFORE p_at_date
  select new_semester_start_date into v_history_start_date
  from public.student_semester_start_history
  where student_id = p_student_id
    and effective_date <= p_at_date
  order by effective_date desc
  limit 1;

  if found then
    return v_history_start_date;
  else
    return v_current_start_date;
  end if;
end;
$$;

revoke execute on function public.get_semester_start_at_date(bigint, timestamptz) from public;
revoke execute on function public.get_semester_start_at_date(bigint, timestamptz) from anon;
grant execute on function public.get_semester_start_at_date(bigint, timestamptz) to authenticated;

-- Helper function: get all semester start changes for a student
create or replace function public.get_student_semester_start_history(p_student_id bigint)
returns table(
  id bigint,
  old_semester_start_date date,
  new_semester_start_date date,
  effective_date timestamptz,
  reason text,
  changed_by uuid,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = 'public'
as $$
begin
  if not (is_admin() or public.is_own_student(p_student_id)) then
    raise exception 'Unauthorized';
  end if;

  return query
    select h.id, h.old_semester_start_date, h.new_semester_start_date, h.effective_date, h.reason, h.changed_by, h.created_at
    from public.student_semester_start_history h
    where h.student_id = p_student_id
    order by h.effective_date;
end;
$$;

revoke execute on function public.get_student_semester_start_history(bigint) from public;
revoke execute on function public.get_student_semester_start_history(bigint) from anon;
grant execute on function public.get_student_semester_start_history(bigint) to authenticated;