-- Online English Tests: Test 10 frozen content (Lessons 91-100).
-- Generated by scripts/build-online-test1-migration.cjs from
-- src/features/onlineTests/data/test10.json. Do not hand-edit;
-- regenerate instead. Inserts are DO NOTHING on conflict so
-- re-applying never mutates published (frozen) items.

insert into public.online_tests (test_number, title, lesson_from, lesson_to, is_published)
values (10, 'Test 10', 91, 100, true)
on conflict (test_number) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'vocabulary', 'multiple_choice', 1, '{"question":"What does “Kashf etmoq” mean in English?","options":["discover","invent","inspire","admire"]}'::jsonb, '{"correct_value":"discover"}'::jsonb, 1, 'L91 people')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'vocabulary', 'multiple_choice', 2, '{"question":"What does “To''satdan” mean in English?","options":["suddenly","finally","memory","story"]}'::jsonb, '{"correct_value":"suddenly"}'::jsonb, 1, 'L92 story')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'vocabulary', 'multiple_choice', 3, '{"question":"What does “Ssenariy” mean in English?","options":["script","scene","camera","editing"]}'::jsonb, '{"correct_value":"script"}'::jsonb, 1, 'L93 film')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'vocabulary', 'matching', 4, '{"instruction":"Match each word with its Uzbek word.","left":["skills","experience","apply","contact"],"right":["Mahoratlar","Tajriba","Ariza bermoq","Bog''lanish"]}'::jsonb, '{"pairs":[["skills","Mahoratlar"],["experience","Tajriba"],["apply","Ariza bermoq"],["contact","Bog''lanish"]]}'::jsonb, 1, 'L95 applications')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'vocabulary', 'multiple_choice', 5, '{"question":"What does “Kulmoq” mean in English?","options":["laugh","memory","surprise","finally"]}'::jsonb, '{"correct_value":"laugh"}'::jsonb, 1, 'L94 storytelling')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'vocabulary', 'multiple_choice', 6, '{"question":"What does “Imzo” mean in English?","options":["signature","attachment","draft","sender"]}'::jsonb, '{"correct_value":"signature"}'::jsonb, 1, 'L96 email')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'vocabulary', 'matching', 7, '{"instruction":"Match each word with its Uzbek word.","left":["advice","problem","solution","decision"],"right":["Maslahat","Muammo","Yechim","Qaror"]}'::jsonb, '{"pairs":[["advice","Maslahat"],["problem","Muammo"],["solution","Yechim"],["decision","Qaror"]]}'::jsonb, 1, 'L97 advice')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'vocabulary', 'multiple_choice', 8, '{"question":"What does “Taqdimot” mean in English?","options":["presentation","project","slide","topic"]}'::jsonb, '{"correct_value":"presentation"}'::jsonb, 1, 'L99 project')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'vocabulary', 'multiple_choice', 9, '{"question":"What does “Bitirmoq” mean in English?","options":["graduate","congratulate","success","present"]}'::jsonb, '{"correct_value":"graduate"}'::jsonb, 1, 'L100 presentations')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'vocabulary', 'multiple_choice', 10, '{"question":"What does “Qiyin” mean in English?","options":["difficult","succeed","improve","fix"]}'::jsonb, '{"correct_value":"difficult"}'::jsonb, 1, 'L98 problems')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'grammar', 'multiple_choice', 1, '{"question":"He ___ born in 1980.","options":["was","is"]}'::jsonb, '{"correct_value":"was"}'::jsonb, 1, 'L91 people')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'grammar', 'multiple_choice', 2, '{"question":"Which sentence is correct?","options":["She famous for her work.","She is famous for her work.","She are famous for her work."]}'::jsonb, '{"correct_value":"She is famous for her work."}'::jsonb, 1, 'L91 people correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'grammar', 'multiple_choice', 3, '{"question":"I was ___ when it rang.","options":["reading","read"]}'::jsonb, '{"correct_value":"reading"}'::jsonb, 1, 'L92 story')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'grammar', 'multiple_choice', 4, '{"question":"Which sentence is correct?","options":["I was read a book.","I was reading a book.","I were reading a book."]}'::jsonb, '{"correct_value":"I was reading a book."}'::jsonb, 1, 'L92 story correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'grammar', 'multiple_choice', 5, '{"question":"I am writing ___ apply.","options":["to","for"]}'::jsonb, '{"correct_value":"to"}'::jsonb, 1, 'L95 applications')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'grammar', 'multiple_choice', 6, '{"question":"Write a clear ___ line.","options":["subject","object"]}'::jsonb, '{"correct_value":"subject"}'::jsonb, 1, 'L96 email')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'grammar', 'multiple_choice', 7, '{"question":"If I ___ you, I would rest.","options":["were","was"]}'::jsonb, '{"correct_value":"were"}'::jsonb, 1, 'L97 advice')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'grammar', 'multiple_choice', 8, '{"question":"The best solution is ___ a plan.","options":["to make","making"]}'::jsonb, '{"correct_value":"to make"}'::jsonb, 1, 'L98 problems')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'grammar', 'multiple_choice', 9, '{"question":"Finish with a ___.","options":["conclusion","concluding"]}'::jsonb, '{"correct_value":"conclusion"}'::jsonb, 1, 'L99 project')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'grammar', 'multiple_choice', 10, '{"question":"My project is ___ about my town.","options":["about","of"]}'::jsonb, '{"correct_value":"about"}'::jsonb, 1, 'L100 presentations')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'sentences', 'ordering', 1, '{"instruction":"Put the words in order.","tokens":["In","the","end,","they","found","it."]}'::jsonb, '{"correct_order":["In","the","end,","they","found","it."]}'::jsonb, 1, 'L94 storytelling')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'sentences', 'ordering', 2, '{"instruction":"Put the words in order.","tokens":["The","narrator","tells","the","story."]}'::jsonb, '{"correct_order":["The","narrator","tells","the","story."]}'::jsonb, 1, 'L93 documentary')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'sentences', 'fill_blank', 3, '{"instruction":"Fill in the blank.","template":"We wrote a short ___."}'::jsonb, '{"answer":"script"}'::jsonb, 1, 'L93 film')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'sentences', 'fill_blank', 4, '{"instruction":"Fill in the blank.","template":"My skills ___ English."}'::jsonb, '{"answer":"include"}'::jsonb, 1, 'L95 applications')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'sentences', 'ordering', 5, '{"instruction":"Put the words in order.","tokens":["Best","regards,","Malika."]}'::jsonb, '{"correct_order":["Best","regards,","Malika."]}'::jsonb, 1, 'L96 email')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'sentences', 'fill_blank', 6, '{"instruction":"Fill in the blank.","template":"I would ___ to the teacher."}'::jsonb, '{"answer":"talk"}'::jsonb, 1, 'L97 advice')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'sentences', 'ordering', 7, '{"instruction":"Put the words in order.","tokens":["How","do","you","deal","with","stress?"]}'::jsonb, '{"correct_order":["How","do","you","deal","with","stress?"]}'::jsonb, 1, 'L98 problems')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'sentences', 'fill_blank', 8, '{"instruction":"Fill in the blank.","template":"Choose an ___ topic."}'::jsonb, '{"answer":"interesting"}'::jsonb, 1, 'L99 project')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'writing', 'translation', 1, '{"instruction":"Translate into English.","source_text":"Tarix","direction":"uz2en"}'::jsonb, '{"target_text":"history"}'::jsonb, 1, 'L91 people')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'writing', 'ordering', 2, '{"instruction":"Put the words in order.","tokens":["While","we","were","walking,","it","rained."]}'::jsonb, '{"correct_order":["While","we","were","walking,","it","rained."]}'::jsonb, 1, 'L92 story')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'writing', 'translation', 3, '{"instruction":"Translate into English.","source_text":"Xotira","direction":"uz2en"}'::jsonb, '{"target_text":"memory"}'::jsonb, 1, 'L94 storytelling')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'writing', 'ordering', 4, '{"instruction":"Put the words in order.","tokens":["The","solution","is","to","make","a","plan."]}'::jsonb, '{"correct_order":["The","solution","is","to","make","a","plan."]}'::jsonb, 1, 'L98 problems correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'writing', 'translation', 5, '{"instruction":"Translate into English.","source_text":"Slayd","direction":"uz2en"}'::jsonb, '{"target_text":"slide"}'::jsonb, 1, 'L99 project')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 10), 'writing', 'translation', 6, '{"instruction":"Translate into English.","source_text":"Muvaffaqiyat","direction":"uz2en"}'::jsonb, '{"target_text":"success"}'::jsonb, 1, 'L100 presentations')
on conflict (test_id, stage, position) do nothing;
