-- Online English Tests: Test 2 frozen content (Lessons 11-20).
-- Generated by scripts/build-online-test1-migration.cjs from
-- src/features/onlineTests/data/test2.json. Do not hand-edit;
-- regenerate instead. Inserts are DO NOTHING on conflict so
-- re-applying never mutates published (frozen) items.

insert into public.online_tests (test_number, title, lesson_from, lesson_to, is_published)
values (2, 'Test 2', 11, 20, true)
on conflict (test_number) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'vocabulary', 'multiple_choice', 1, '{"question":"What does “Country” mean?","options":["Davlat","Shahar","Millat","Poytaxt"]}'::jsonb, '{"correct_value":"Davlat"}'::jsonb, 1, 'L11 countries')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'vocabulary', 'multiple_choice', 2, '{"question":"What does “Ona” mean in English?","options":["Mother","Father","Sister","Daughter"]}'::jsonb, '{"correct_value":"Mother"}'::jsonb, 1, 'L12 family')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'vocabulary', 'multiple_choice', 3, '{"question":"What does “Juma” mean in English?","options":["Friday","Thursday","Saturday","Monday"]}'::jsonb, '{"correct_value":"Friday"}'::jsonb, 1, 'L14 weekdays')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'vocabulary', 'matching', 4, '{"instruction":"Match each family member with its Uzbek word.","left":["Mother","Father","Son","Daughter"],"right":["Ona","Ota","O''g''il","Qiz"]}'::jsonb, '{"pairs":[["Mother","Ona"],["Father","Ota"],["Son","O''g''il"],["Daughter","Qiz"]]}'::jsonb, 1, 'L12 family')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'vocabulary', 'multiple_choice', 5, '{"question":"What does “Mehribon” mean in English?","options":["Kind","Happy","Funny","Strong"]}'::jsonb, '{"correct_value":"Kind"}'::jsonb, 1, 'L15 adjectives')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'vocabulary', 'multiple_choice', 6, '{"question":"What does “Musiqa” mean in English?","options":["Music","Sport","Dance","Read"]}'::jsonb, '{"correct_value":"Music"}'::jsonb, 1, 'L16 hobbies')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'vocabulary', 'matching', 7, '{"instruction":"Match each thing with its Uzbek word.","left":["bag","phone","bike","ball"],"right":["sumka","telefon","velosiped","to''p"]}'::jsonb, '{"pairs":[["bag","sumka"],["phone","telefon"],["bike","velosiped"],["ball","to''p"]]}'::jsonb, 1, 'L13 possessions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'vocabulary', 'multiple_choice', 8, '{"question":"What does “Kutubxona” mean in English?","options":["Library","Gym","Playground","Classroom"]}'::jsonb, '{"correct_value":"Library"}'::jsonb, 1, 'L19 school')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'vocabulary', 'multiple_choice', 9, '{"question":"What does “Best friend” mean?","options":["Eng yaqin do''st","Sevimli fan","O''ziga ishongan","Allaqachon"]}'::jsonb, '{"correct_value":"Eng yaqin do''st"}'::jsonb, 1, 'L20 friendship')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'vocabulary', 'multiple_choice', 10, '{"question":"What does “Qarindosh” mean in English?","options":["Relative","Aunt","Uncle","Cousin"]}'::jsonb, '{"correct_value":"Relative"}'::jsonb, 1, 'L17 relatives')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'grammar', 'multiple_choice', 1, '{"question":"I ___ from Uzbekistan.","options":["am","is"]}'::jsonb, '{"correct_value":"am"}'::jsonb, 1, 'L11 be-from')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'grammar', 'multiple_choice', 2, '{"question":"She ___ in London.","options":["live","lives"]}'::jsonb, '{"correct_value":"lives"}'::jsonb, 1, 'L11 live')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'grammar', 'multiple_choice', 3, '{"question":"Talking about your own father: This is ___ father.","options":["my","his"]}'::jsonb, '{"correct_value":"my"}'::jsonb, 1, 'L12 possessives')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'grammar', 'multiple_choice', 4, '{"question":"She ___ a bike.","options":["have","has"]}'::jsonb, '{"correct_value":"has"}'::jsonb, 1, 'L13 have-has')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'grammar', 'multiple_choice', 5, '{"question":"___ you have a dog?","options":["Do","Does"]}'::jsonb, '{"correct_value":"Do"}'::jsonb, 1, 'L13 do-questions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'grammar', 'multiple_choice', 6, '{"question":"He ___ tall.","options":["is","am"]}'::jsonb, '{"correct_value":"is"}'::jsonb, 1, 'L15 be-verb')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'grammar', 'multiple_choice', 7, '{"question":"I ___ to dance.","options":["like","likes"]}'::jsonb, '{"correct_value":"like"}'::jsonb, 1, 'L16 like')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'grammar', 'multiple_choice', 8, '{"question":"I ___ English on Monday.","options":["have","has"]}'::jsonb, '{"correct_value":"have"}'::jsonb, 1, 'L19 have')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'grammar', 'multiple_choice', 9, '{"question":"Which sentence is correct?","options":["today is monday.","Today is Monday.","Today is monday."]}'::jsonb, '{"correct_value":"Today is Monday."}'::jsonb, 1, 'L14 capitalization correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'grammar', 'multiple_choice', 10, '{"question":"Talking about a boy''s brother. Which sentence is correct?","options":["This is her brother.","This is his brother.","This is my brother."]}'::jsonb, '{"correct_value":"This is his brother."}'::jsonb, 1, 'L12 possessives correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'sentences', 'ordering', 1, '{"instruction":"Put the words in order.","tokens":["I","am","from","Uzbekistan."]}'::jsonb, '{"correct_order":["I","am","from","Uzbekistan."]}'::jsonb, 1, 'L11 countries')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'sentences', 'ordering', 2, '{"instruction":"Put the words in order.","tokens":["This","is","my","mother."]}'::jsonb, '{"correct_order":["This","is","my","mother."]}'::jsonb, 1, 'L12 family')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'sentences', 'fill_blank', 3, '{"instruction":"Fill in the blank.","template":"The day after Sunday is ___."}'::jsonb, '{"answer":"Monday"}'::jsonb, 1, 'L14 weekdays')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'sentences', 'fill_blank', 4, '{"instruction":"Fill in the blank.","template":"The opposite of “tall” is ___."}'::jsonb, '{"answer":"short"}'::jsonb, 1, 'L15 opposites')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'sentences', 'ordering', 5, '{"instruction":"Put the words in order.","tokens":["I","like","to","sing."]}'::jsonb, '{"correct_order":["I","like","to","sing."]}'::jsonb, 1, 'L16 likes')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'sentences', 'fill_blank', 6, '{"instruction":"Fill in the blank.","template":"We read books in the ___."}'::jsonb, '{"answer":"library"}'::jsonb, 1, 'L19 school')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'sentences', 'ordering', 7, '{"instruction":"Put the words in order.","tokens":["He","has","a","dog."]}'::jsonb, '{"correct_order":["He","has","a","dog."]}'::jsonb, 1, 'L13 have-has')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'sentences', 'fill_blank', 8, '{"instruction":"Fill in the blank.","template":"I am ___ of my school."}'::jsonb, '{"answer":"proud"}'::jsonb, 1, 'L20 pride')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'writing', 'translation', 1, '{"instruction":"Translate into English.","source_text":"Angliya","direction":"uz2en"}'::jsonb, '{"target_text":"England"}'::jsonb, 1, 'L11 countries')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'writing', 'translation', 2, '{"instruction":"Translate into English.","source_text":"Ona","direction":"uz2en"}'::jsonb, '{"target_text":"Mother"}'::jsonb, 1, 'L12 family')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'writing', 'translation', 3, '{"instruction":"Translate into English.","source_text":"Birga","direction":"uz2en"}'::jsonb, '{"target_text":"Together"}'::jsonb, 1, 'L18 togetherness')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'writing', 'ordering', 4, '{"instruction":"Put the words in order to fix the sentence.","tokens":["She","is","kind."]}'::jsonb, '{"correct_order":["She","is","kind."]}'::jsonb, 1, 'L15 adjectives correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'writing', 'translation', 5, '{"instruction":"Translate into English.","source_text":"Sevimli","direction":"uz2en"}'::jsonb, '{"target_text":"Favorite"}'::jsonb, 1, 'L16 hobbies')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 2), 'writing', 'translation', 6, '{"instruction":"Translate into English.","source_text":"Maktab","direction":"uz2en"}'::jsonb, '{"target_text":"School"}'::jsonb, 1, 'L19 school')
on conflict (test_id, stage, position) do nothing;
