-- 20261101000000_homework_auto_grading.sql
-- Homework automatic submission + server-side grading (isolated subsystem).
--
-- Root cause it fixes: homework had no deterministic questions, no answer
-- keys, and no auto-grading path at all - it was photo-upload + manual
-- teacher grading only, and the pre-existing HomeworkStages.jsx was dead UI
-- referencing stage/question/answer tables and RPCs that never existed.
-- (Exams are manual too - "no auto-scoring" per MyExams.jsx - so the only
-- in-repo reference for reliable server-side grading is the games
-- submit_game_round() SECURITY DEFINER pattern, which this mirrors.)
--
-- Design:
-- * Authoritative answer keys = lesson_vocabulary rows of the homework's
--   linked lesson (teacher-managed, level-scoped). No new authoring UI,
--   no invented keys, no subjective grading.
-- * get_homework_auto_quiz() returns deterministic questions with NO
--   correct answers. submit_homework_auto_stage() re-derives the same quiz
--   server-side and grades. The client is never trusted for correctness,
--   score, percentage, or completion.
-- * Student identity comes from auth.uid() inside the RPCs (no student_id
--   parameter), so a student can only ever submit their own homework.
-- * Results persist in homework_auto_stage_results (no student write
--   policies at all - RPC-only writes) and the overall percentage in
--   homework_status (status='Graded' + score, satisfying the existing
--   homework_status_score_status_check / homework_status_feedback_check).
-- * A teacher's manual grade is never overwritten: submit raises if the
--   row already carries a non-auto score.
-- * Never touches Academy points: no point_transactions writes, no
--   triggers. Manual point awarding is unchanged.
-- * Homeworks with no linked lesson or fewer than 4 active vocabulary
--   words are explicitly ineligible (eligible=false + reason string) - the
--   teacher-graded photo/manual flow is preserved for those, untouched.
-- * Submission boundary: one submit per stage (vocabulary -> sentences ->
--   tests). Completing a stage's questions auto-submits that stage.
--   Resubmission is deterministic: re-graded from keys, best score kept,
--   attempts counted - replays cannot corrupt the result.
-- * Autosave stays client-side (localStorage drafts, never sent until the
--   stage is complete), so a temporary save can never finalize anything.
--
-- Data safety: purely additive. No updates/deletes on existing rows except
-- the student's own homework_status row on submit (upsert of
-- status/score/feedback/submitted_at only). No backfill, no migration of
-- historical submissions.

-- =========================
-- 1) Answer normalization (single canonical form, used for keys AND answers)
-- =========================

create or replace function public.homework_normalize_answer(p_text text)
returns text
language sql
immutable
set search_path = 'public'
as $$
  select nullif(
    trim(both ' .,!?;:-"''()[]{}' from
      regexp_replace(
        replace(replace(replace(replace(replace(replace(
          lower(coalesce(p_text, '')),
        '‘', ''''), '’', ''''), '`', ''''), '´', ''''), 'ʻ', ''''), 'ʼ', ''''),
        '\s+', ' ', 'g'
      )
    ),
    ''
  );
$$;

-- =========================
-- 2) Per-stage auto-grading results (RPC-only writes)
-- =========================

create table if not exists public.homework_auto_stage_results (
  id bigint generated by default as identity primary key,
  homework_id bigint not null references public.homework (id) on delete cascade,
  student_id bigint not null references public.students (id) on delete cascade,
  stage_key text not null check (stage_key in ('vocabulary', 'sentences', 'tests')),
  correct integer not null default 0 check (correct >= 0),
  total integer not null default 0 check (total >= 0),
  best_correct integer not null default 0 check (best_correct >= 0),
  attempts integer not null default 0 check (attempts >= 0),
  details jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (homework_id, student_id, stage_key),
  check (correct <= total),
  check (best_correct <= total)
);

create index if not exists homework_auto_stage_results_hw_student_idx
  on public.homework_auto_stage_results (homework_id, student_id);

alter table public.homework_auto_stage_results enable row level security;

drop policy if exists homework_auto_stage_results_admin_all on public.homework_auto_stage_results;
create policy homework_auto_stage_results_admin_all on public.homework_auto_stage_results
for all using (is_admin()) with check (is_admin());

-- Teacher read/write scoped by the student's level, mirroring the
-- homework_status_teacher_all shape from 0132 (teacher_group_assignments).
drop policy if exists homework_auto_stage_results_teacher_all on public.homework_auto_stage_results;
create policy homework_auto_stage_results_teacher_all on public.homework_auto_stage_results
for all
using (
  is_teacher()
  and exists (
    select 1
    from students s
    join teacher_group_assignments tga
      on tga.level = s.level
     and tga.teacher_id = auth.uid()
    where s.id = homework_auto_stage_results.student_id
  )
)
with check (
  is_teacher()
  and exists (
    select 1
    from students s
    join teacher_group_assignments tga
      on tga.level = s.level
     and tga.teacher_id = auth.uid()
    where s.id = homework_auto_stage_results.student_id
  )
);

-- Students read their own rows (active or inactive - historical results
-- stay visible, same rule as every other self_read policy). Deliberately
-- NO insert/update/delete policy for students: the only writer is the
-- SECURITY DEFINER submit RPC, so fake scores/correctness cannot be
-- written through PostgREST at the SQL layer.
drop policy if exists homework_auto_stage_results_self_read on public.homework_auto_stage_results;
create policy homework_auto_stage_results_self_read on public.homework_auto_stage_results
for select using (public.is_own_student(student_id));

-- =========================
-- 3) Deterministic quiz builder (definer-internal, never directly callable)
-- =========================
-- Same inputs -> same questions, same option order, same qids. Called by
-- both RPCs so grading always re-derives from authoritative keys.
-- p_include_keys=true adds the 'answer' field per question (submit path
-- only - keys never leave the server except as post-submission review).

create or replace function public.homework_build_auto_quiz(
  p_homework_id bigint,
  p_student_id bigint,
  p_include_keys boolean
)
returns jsonb
language plpgsql
stable
security definer
set search_path = 'public'
as $$
declare
  v_lesson_id bigint;
  v_seed text;
  v_words jsonb := '[]'::jsonb;
  v_total int := 0;
  v_n_vocab int;
  v_n_sent int;
  v_n_test int;
  v_vocab jsonb := '[]'::jsonb;
  v_sent jsonb := '[]'::jsonb;
  v_test jsonb := '[]'::jsonb;
  v_questions jsonb;
  v_q jsonb;
  i int;
  v_w jsonb;
  v_wid text;
  v_en text;
  v_uz text;
  v_ex text;
  v_qid text;
  v_d jsonb;
  v_opts jsonb;
  v_tokens text[];
  v_ord_tokens text[];
  v_norm_en text;
  v_blank_idx int := -1;
  v_prompt text;
  v_shuffled jsonb;
  v_pairs jsonb;
  v_left jsonb;
  v_right jsonb;
  j int;
begin
  select h.lesson_id into v_lesson_id
  from public.homework h
  where h.id = p_homework_id;

  if v_lesson_id is null then
    return jsonb_build_object('eligible', false, 'reason', 'no_lesson');
  end if;

  v_seed := p_homework_id::text || ':' || p_student_id::text;

  select coalesce(jsonb_agg(
           jsonb_build_object(
             'id', lv.id::text, 'en', lv.english, 'uz', lv.uzbek, 'ex', lv.example
           )
           order by md5(v_seed || '|' || lv.id::text)
         ), '[]'::jsonb)
    into v_words
  from public.lesson_vocabulary lv
  where lv.lesson_id = v_lesson_id
    and lv.is_active;

  v_total := jsonb_array_length(v_words);

  if v_total < 4 then
    return jsonb_build_object('eligible', false, 'reason', 'needs_vocabulary');
  end if;

  -- Word partition across stages: vocabulary gets roughly half, the rest
  -- split between sentences and tests, each stage guaranteed >= 1 word.
  v_n_vocab := (v_total + 1) / 2;
  if v_n_vocab > 6 then v_n_vocab := 6; end if;
  v_n_sent := greatest(1, (v_total - v_n_vocab) / 2);
  if v_n_sent > 4 then v_n_sent := 4; end if;
  v_n_test := v_total - v_n_vocab - v_n_sent;
  if v_n_test < 1 then
    v_n_test := 1;
    if v_n_sent > 1 then v_n_sent := v_n_sent - 1;
    else v_n_vocab := v_n_vocab - 1; end if;
  end if;
  if v_n_test > 6 then v_n_test := 6; end if;

  -- ---------- Stage 1: vocabulary (multiple choice both directions) ----------
  v_questions := '[]'::jsonb;
  for i in 0 .. v_n_vocab - 1 loop
    v_w := v_words -> i;
    v_wid := v_w ->> 'id';
    v_en := v_w ->> 'en';
    v_uz := v_w ->> 'uz';

    -- en -> uz
    v_qid := 'v-mcq-eu:' || v_wid;
    select coalesce(jsonb_agg(x.d), '[]'::jsonb) into v_d
    from (
      select (w ->> 'uz') as d
      from jsonb_array_elements(v_words) w
      where (w ->> 'id') <> v_wid
      order by md5(v_seed || '|d|' || v_qid || '|' || (w ->> 'id'))
      limit 3
    ) x;
    select jsonb_agg(o order by md5(v_seed || '|o|' || v_qid || '|' || o)) into v_opts
    from jsonb_array_elements_text(jsonb_build_array(v_uz) || v_d) o;
    v_q := jsonb_build_object(
      'qid', v_qid, 'type', 'mcq', 'dir', 'en_uz',
      'prompt', v_en, 'options', v_opts
    );
    if p_include_keys then v_q := v_q || jsonb_build_object('answer', v_uz); end if;
    v_questions := v_questions || v_q;

    -- uz -> en
    v_qid := 'v-mcq-ue:' || v_wid;
    select coalesce(jsonb_agg(x.d), '[]'::jsonb) into v_d
    from (
      select (w ->> 'en') as d
      from jsonb_array_elements(v_words) w
      where (w ->> 'id') <> v_wid
      order by md5(v_seed || '|d|' || v_qid || '|' || (w ->> 'id'))
      limit 3
    ) x;
    select jsonb_agg(o order by md5(v_seed || '|o|' || v_qid || '|' || o)) into v_opts
    from jsonb_array_elements_text(jsonb_build_array(v_en) || v_d) o;
    v_q := jsonb_build_object(
      'qid', v_qid, 'type', 'mcq', 'dir', 'uz_en',
      'prompt', v_uz, 'options', v_opts
    );
    if p_include_keys then v_q := v_q || jsonb_build_object('answer', v_en); end if;
    v_questions := v_questions || v_q;
  end loop;
  v_vocab := v_questions;

  -- ---------- Stage 2: sentences (fill-in-the-blank + ordering) ----------
  v_questions := '[]'::jsonb;
  for i in 0 .. v_n_sent - 1 loop
    v_w := v_words -> (v_n_vocab + i);
    v_wid := v_w ->> 'id';
    v_en := v_w ->> 'en';
    v_uz := v_w ->> 'uz';
    v_ex := v_w ->> 'ex';
    v_norm_en := public.homework_normalize_answer(v_en);

    -- fill-in-the-blank from the example sentence when it contains the
    -- word as a whole token, otherwise fall back to typing the word.
    v_blank_idx := -1;
    v_tokens := null;
    if v_ex is not null and btrim(v_ex) <> '' then
      v_tokens := string_to_array(v_ex, ' ');
      for j in 1 .. array_length(v_tokens, 1) loop
        if public.homework_normalize_answer(v_tokens[j]) = v_norm_en then
          v_blank_idx := j;
          exit;
        end if;
      end loop;
    end if;

    v_qid := 's-fib:' || v_wid;
    if v_blank_idx > 0 then
      v_tokens[v_blank_idx] := '_____';
      v_prompt := array_to_string(v_tokens, ' ');
      v_q := jsonb_build_object(
        'qid', v_qid, 'type', 'fib',
        'prompt', v_prompt, 'hint', v_uz
      );
      if p_include_keys then v_q := v_q || jsonb_build_object('answer', v_en); end if;
      v_questions := v_questions || v_q;
    else
      v_q := jsonb_build_object(
        'qid', v_qid, 'type', 'type', 'dir', 'uz_en',
        'prompt', v_uz
      );
      if p_include_keys then v_q := v_q || jsonb_build_object('answer', v_en); end if;
      v_questions := v_questions || v_q;
    end if;

    -- ordering: example-sentence tokens when usable, else word letters.
    -- NOTE: v_tokens may carry the '_____' blank from the fib branch above,
    -- so ordering always re-splits from the original example (or letters).
    v_qid := 's-ord:' || v_wid;
    v_ord_tokens := null;
    if v_ex is not null and btrim(v_ex) <> '' then
      v_ord_tokens := string_to_array(v_ex, ' ');
    end if;
    if v_ord_tokens is not null and array_length(v_ord_tokens, 1) >= 3
       and array_length(v_ord_tokens, 1) <= 15 then
      select coalesce(jsonb_agg(t order by md5(v_seed || '|s|' || v_qid || '|' || t || '|' || n::text)), '[]'::jsonb)
        into v_shuffled
      from unnest(v_ord_tokens) with ordinality as u(t, n);
      v_q := jsonb_build_object(
        'qid', v_qid, 'type', 'order',
        'prompt', v_uz, 'tokens', v_shuffled
      );
      if p_include_keys then v_q := v_q || jsonb_build_object('answer', to_jsonb(v_ord_tokens)); end if;
      v_questions := v_questions || v_q;
    elsif char_length(v_en) >= 3 and char_length(v_en) <= 15 then
      v_ord_tokens := regexp_split_to_array(v_en, '');
      select coalesce(jsonb_agg(t order by md5(v_seed || '|s|' || v_qid || '|' || t || '|' || n::text)), '[]'::jsonb)
        into v_shuffled
      from unnest(v_ord_tokens) with ordinality as u(t, n);
      v_q := jsonb_build_object(
        'qid', v_qid, 'type', 'order',
        'prompt', v_uz || case when v_ex is not null and btrim(v_ex) <> ''
                               then ' (' || v_ex || ')' else '' end,
        'tokens', v_shuffled
      );
      if p_include_keys then v_q := v_q || jsonb_build_object('answer', to_jsonb(v_ord_tokens)); end if;
      v_questions := v_questions || v_q;
    else
      v_q := jsonb_build_object(
        'qid', v_qid, 'type', 'type', 'dir', 'en_uz',
        'prompt', v_en
      );
      if p_include_keys then v_q := v_q || jsonb_build_object('answer', v_uz); end if;
      v_questions := v_questions || v_q;
    end if;
  end loop;
  v_sent := v_questions;

  -- ---------- Stage 3: tests (matching set + controlled translation) ----------
  v_questions := '[]'::jsonb;
  v_qid := 't-match';
  select coalesce(jsonb_agg((v_words -> (v_n_vocab + v_n_sent + k)) ->> 'en'
                    order by md5(v_seed || '|ml|' || k::text)), '[]'::jsonb)
    into v_left
  from generate_series(0, v_n_test - 1) k;
  select coalesce(jsonb_agg((v_words -> (v_n_vocab + v_n_sent + k)) ->> 'uz'
                    order by md5(v_seed || '|mr|' || k::text)), '[]'::jsonb)
    into v_right
  from generate_series(0, v_n_test - 1) k;
  select coalesce(jsonb_object_agg((v_words -> (v_n_vocab + v_n_sent + k)) ->> 'en',
                                   (v_words -> (v_n_vocab + v_n_sent + k)) ->> 'uz'),
                  '{}'::jsonb)
    into v_pairs
  from generate_series(0, v_n_test - 1) k;
  if v_n_test >= 2 then
    v_q := jsonb_build_object(
      'qid', v_qid, 'type', 'match',
      'prompt', 'match', 'left', v_left, 'right', v_right
    );
    if p_include_keys then v_q := v_q || jsonb_build_object('answer', v_pairs); end if;
    v_questions := v_questions || v_q;
  end if;
  for i in 0 .. v_n_test - 1 loop
    v_w := v_words -> (v_n_vocab + v_n_sent + i);
    v_wid := v_w ->> 'id';
    v_en := v_w ->> 'en';
    v_uz := v_w ->> 'uz';
    if i % 2 = 0 then
      v_q := jsonb_build_object(
        'qid', 't-tr-eu:' || v_wid, 'type', 'translate', 'dir', 'en_uz',
        'prompt', v_en
      );
      if p_include_keys then v_q := v_q || jsonb_build_object('answer', v_uz); end if;
      v_questions := v_questions || v_q;
    else
      v_q := jsonb_build_object(
        'qid', 't-tr-ue:' || v_wid, 'type', 'translate', 'dir', 'uz_en',
        'prompt', v_uz
      );
      if p_include_keys then v_q := v_q || jsonb_build_object('answer', v_en); end if;
      v_questions := v_questions || v_q;
    end if;
    if jsonb_array_length(v_questions) >= 8 then exit; end if;
  end loop;
  v_test := v_questions;

  return jsonb_build_object(
    'eligible', true,
    'stages', jsonb_build_array(
      jsonb_build_object('key', 'vocabulary', 'questions', v_vocab),
      jsonb_build_object('key', 'sentences', 'questions', v_sent),
      jsonb_build_object('key', 'tests', 'questions', v_test)
    )
  );
end;
$$;

-- Internal helper: callable only from inside other definer functions.
revoke execute on function public.homework_build_auto_quiz(bigint, bigint, boolean) from anon;
revoke execute on function public.homework_build_auto_quiz(bigint, bigint, boolean) from public;

-- =========================
-- 4) Grade one submitted stage (definer-internal)
-- =========================
-- Returns { correct, total, review[] }. Malformed/missing answers count as
-- incorrect - grading never throws on answer shape, only on auth/assignment.

create or replace function public.homework_grade_auto_stage(
  p_quiz jsonb,
  p_stage_key text,
  p_answers jsonb
)
returns jsonb
language plpgsql
stable
security definer
set search_path = 'public'
as $$
declare
  v_stage jsonb;
  v_q jsonb;
  v_qid text;
  v_qtype text;
  v_ans jsonb;
  v_correct int := 0;
  v_total int := 0;
  v_review jsonb := '[]'::jsonb;
  v_item jsonb;
  v_ok boolean;
  v_your text;
  v_expected jsonb;
  v_pair_key text;
  v_pair_correct int;
  v_pair_total int;
  v_exp_arr text[];
  v_got_arr text[];
  v_arr_ok boolean;
  k int;
begin
  select s into v_stage
  from jsonb_array_elements(p_quiz -> 'stages') s
  where s ->> 'key' = p_stage_key;

  if v_stage is null then
    raise exception 'Unknown stage: %', p_stage_key;
  end if;

  for v_q in select * from jsonb_array_elements(v_stage -> 'questions') loop
    v_qid := v_q ->> 'qid';
    v_qtype := v_q ->> 'type';
    v_ans := case
      when p_answers is null then null
      when jsonb_typeof(p_answers) = 'object' then p_answers -> v_qid
      else null
    end;
    v_expected := v_q -> 'answer';

    if v_qtype = 'match' then
      -- per-pair scoring: each pair is one deterministic scoring unit.
      -- Pair count comes from the keyless 'left' list so grading stays
      -- well-defined even if keys were somehow absent.
      v_pair_correct := 0;
      v_pair_total := coalesce(jsonb_array_length(v_q -> 'left'), 0);
      if v_expected is not null and jsonb_typeof(v_expected) = 'object' then
        for v_pair_key in select * from jsonb_object_keys(v_expected) loop
          if v_ans is not null and jsonb_typeof(v_ans) = 'object'
             and public.homework_normalize_answer(v_ans ->> v_pair_key)
               = public.homework_normalize_answer(v_expected ->> v_pair_key) then
            v_pair_correct := v_pair_correct + 1;
          end if;
        end loop;
      end if;
      v_correct := v_correct + v_pair_correct;
      v_total := v_total + v_pair_total;
      v_review := v_review || jsonb_build_object(
        'qid', v_qid, 'type', v_qtype,
        'prompt', v_q ->> 'prompt',
        'correct', v_pair_correct, 'total', v_pair_total,
        'is_correct', (v_pair_correct = v_pair_total),
        'your_answer', v_ans, 'correct_answer', v_expected
      );
      continue;
    end if;

    v_total := v_total + 1;
    v_ok := false;
    v_your := null;

    if v_qtype = 'order' then
      if v_ans is not null and jsonb_typeof(v_ans) = 'array' then
        select array_agg(e order by ord) into v_exp_arr
        from jsonb_array_elements_text(v_expected) with ordinality as u(e, ord);
        select array_agg(e order by ord) into v_got_arr
        from jsonb_array_elements_text(v_ans) with ordinality as u(e, ord);
        if array_length(v_exp_arr, 1) = array_length(v_got_arr, 1) then
          v_arr_ok := true;
          for k in 1 .. array_length(v_exp_arr, 1) loop
            if public.homework_normalize_answer(v_exp_arr[k])
             <> public.homework_normalize_answer(v_got_arr[k]) then
              v_arr_ok := false;
              exit;
            end if;
          end loop;
          v_ok := v_arr_ok;
        end if;
        v_your := (select string_agg(e, ' ' order by ord)
                   from jsonb_array_elements_text(v_ans) with ordinality as u(e, ord));
      end if;
      v_review := v_review || jsonb_build_object(
        'qid', v_qid, 'type', v_qtype,
        'prompt', v_q ->> 'prompt',
        'is_correct', coalesce(v_ok, false),
        'your_answer', v_ans,
        'correct_answer', v_expected
      );
    elsif v_qtype = 'mcq' and v_ans is not null and jsonb_typeof(v_ans) = 'number'
          and (v_ans #>> '{}') ~ '^[0-9]+$' then
      -- tolerate option-index answers (0-based into the shown options)
      v_your := (v_q -> 'options') ->> ((v_ans #>> '{}')::int);
      v_ok := v_your is not null
        and public.homework_normalize_answer(v_your)
          = public.homework_normalize_answer(v_expected #>> '{}');
      v_review := v_review || jsonb_build_object(
        'qid', v_qid, 'type', v_qtype,
        'prompt', v_q ->> 'prompt', 'options', v_q -> 'options',
        'is_correct', coalesce(v_ok, false),
        'your_answer', v_your,
        'correct_answer', v_expected
      );
    else
      -- mcq (text), fib, type, translate: normalized string equality
      if v_ans is not null and jsonb_typeof(v_ans) = 'string' then
        v_your := v_ans #>> '{}';
      end if;
      v_ok := v_your is not null
        and public.homework_normalize_answer(v_your)
          = public.homework_normalize_answer(v_expected #>> '{}');
      v_item := jsonb_build_object(
        'qid', v_qid, 'type', v_qtype,
        'prompt', v_q ->> 'prompt',
        'is_correct', coalesce(v_ok, false),
        'your_answer', v_your,
        'correct_answer', v_expected
      );
      if v_q ? 'options' then
        v_item := v_item || jsonb_build_object('options', v_q -> 'options');
      end if;
      if v_q ? 'tokens' then
        v_item := v_item || jsonb_build_object('tokens', v_q -> 'tokens');
      end if;
      if v_qtype = 'match' then
        v_item := v_item || jsonb_build_object('left', v_q -> 'left', 'right', v_q -> 'right');
      end if;
      if v_q ? 'hint' then
        v_item := v_item || jsonb_build_object('hint', v_q -> 'hint');
      end if;
      v_review := v_review || v_item;
    end if;

    -- normalize() returns null for empty input, which would make v_ok
    -- null instead of false - coalesce so review JSON is always boolean.
    v_ok := coalesce(v_ok, false);
    if v_ok then v_correct := v_correct + 1; end if;
  end loop;

  return jsonb_build_object('correct', v_correct, 'total', v_total, 'review', v_review);
end;
$$;

revoke execute on function public.homework_grade_auto_stage(jsonb, text, jsonb) from anon;
revoke execute on function public.homework_grade_auto_stage(jsonb, text, jsonb) from public;

-- =========================
-- 5) Student RPC: fetch quiz (no answer keys) + progress + earned review
-- =========================

create or replace function public.get_homework_auto_quiz(p_homework_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = 'public'
as $$
declare
  v_student_id bigint;
  v_student_level text;
  v_student_status text;
  v_hw_level text;
  v_hw_title text;
  v_built jsonb;
  v_out jsonb;
  v_stage jsonb;
  v_key text;
  v_row record;
  v_overall_correct int := 0;
  v_overall_total int := 0;
  v_done int := 0;
  v_progress jsonb := '{}'::jsonb;
  v_reviews jsonb := '{}'::jsonb;
  v_pct int;
begin
  select s.id, s.level, s.status into v_student_id, v_student_level, v_student_status
  from public.students s
  where s.profile_id = auth.uid();

  if v_student_id is null then
    raise exception 'No student record for the current user';
  end if;
  if v_student_status <> 'Active' then
    raise exception 'Inactive students cannot open auto-graded homework';
  end if;

  select h.level, h.title into v_hw_level, v_hw_title
  from public.homework h
  where h.id = p_homework_id;
  if v_hw_title is null then
    raise exception 'Homework not found';
  end if;
  if v_hw_level is not null and v_hw_level <> v_student_level then
    raise exception 'This homework is not assigned to your level';
  end if;

  v_built := public.homework_build_auto_quiz(p_homework_id, v_student_id, false);
  if not coalesce((v_built ->> 'eligible')::boolean, false) then
    return jsonb_build_object(
      'eligible', false,
      'reason', v_built ->> 'reason',
      'homework', jsonb_build_object('id', p_homework_id, 'title', v_hw_title)
    );
  end if;

  -- strip any 'answer' fields defense-in-depth and rebuild the public
  -- quiz shape explicitly (the builder only adds keys when
  -- p_include_keys=true, but never trust that here).
  v_out := (
    select jsonb_agg(
      jsonb_build_object(
        'key', s ->> 'key',
        'questions', (
          select coalesce(jsonb_agg(q - 'answer'), '[]'::jsonb)
          from jsonb_array_elements(s -> 'questions') q
        )
      )
    )
    from jsonb_array_elements(v_built -> 'stages') s
  );

  for v_row in
    select r.stage_key, r.correct, r.total, r.best_correct, r.attempts, r.details
    from public.homework_auto_stage_results r
    where r.homework_id = p_homework_id and r.student_id = v_student_id
  loop
    v_progress := v_progress || jsonb_build_object(v_row.stage_key, jsonb_build_object(
      'correct', v_row.correct, 'total', v_row.total,
      'best_correct', v_row.best_correct, 'attempts', v_row.attempts
    ));
    v_reviews := v_reviews || jsonb_build_object(v_row.stage_key, v_row.details);
  end loop;

  -- overall uses best-per-stage over the CURRENT quiz totals (unsubmitted
  -- stages contribute 0) - deterministic across reloads. Totals for
  -- unsubmitted stages count each question once, with match questions
  -- counting their pair count (from the keyless 'left' list, which carries
  -- no answers); submitted stages use their stored authoritative totals.
  v_overall_total := 0;
  for v_stage in select * from jsonb_array_elements(v_built -> 'stages') loop
    v_key := v_stage ->> 'key';
    if v_progress ? v_key then
      v_overall_total := v_overall_total + ((v_progress -> v_key) ->> 'total')::int;
    else
      -- unsubmitted stage: count its keyless questions; match pairs are
      -- unknown until graded, so count the match question as its pair
      -- count from the keyed builder (server-side only, never returned).
      v_overall_total := v_overall_total + (
        select coalesce(sum(
          case when (q ->> 'type') = 'match'
               then greatest(jsonb_array_length(q -> 'left'), 1)
               else 1 end
        ), 0)::int
        from jsonb_array_elements(v_stage -> 'questions') q
      );
    end if;
  end loop;

  for v_key in select * from jsonb_object_keys(v_progress) loop
    v_overall_correct := v_overall_correct + ((v_progress -> v_key) ->> 'best_correct')::int;
    v_done := v_done + 1;
  end loop;

  v_pct := case when v_overall_total > 0
    then round(100.0 * v_overall_correct / v_overall_total)::int else 0 end;

  return jsonb_build_object(
    'eligible', true,
    'homework', jsonb_build_object('id', p_homework_id, 'title', v_hw_title),
    'stages', v_out,
    'progress', jsonb_build_object(
      'stages', v_progress,
      'overall', jsonb_build_object(
        'correct', v_overall_correct, 'total', v_overall_total,
        'percentage', v_pct, 'stages_completed', v_done
      )
    ),
    -- review details only for already-submitted stages (post-submission,
    -- never a pre-answer leak: unsubmitted stages have no entry here)
    'review', v_reviews
  );
end;
$$;

revoke execute on function public.get_homework_auto_quiz(bigint) from anon;
revoke execute on function public.get_homework_auto_quiz(bigint) from public;
grant execute on function public.get_homework_auto_quiz(bigint) to authenticated;

-- =========================
-- 6) Student RPC: submit a stage -> grade -> persist -> return result
-- =========================

create or replace function public.submit_homework_auto_stage(
  p_homework_id bigint,
  p_stage_key text,
  p_answers jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = 'public'
as $$
declare
  v_student_id bigint;
  v_student_level text;
  v_student_status text;
  v_hw_level text;
  v_hw_title text;
  v_built jsonb;
  v_graded jsonb;
  v_correct int;
  v_total int;
  v_prev record;
  v_attempts int;
  v_best int;
  v_overall_correct int := 0;
  v_overall_total int := 0;
  v_done int := 0;
  v_pct int;
  v_row record;
  v_existing_score numeric;
  v_existing_feedback text;
begin
  if p_stage_key not in ('vocabulary', 'sentences', 'tests') then
    raise exception 'Unknown stage: %', p_stage_key;
  end if;

  select s.id, s.level, s.status into v_student_id, v_student_level, v_student_status
  from public.students s
  where s.profile_id = auth.uid();

  if v_student_id is null then
    raise exception 'No student record for the current user';
  end if;
  if v_student_status <> 'Active' then
    raise exception 'Inactive students cannot submit homework';
  end if;

  select h.level, h.title into v_hw_level, v_hw_title
  from public.homework h
  where h.id = p_homework_id;
  if v_hw_title is null then
    raise exception 'Homework not found';
  end if;
  if v_hw_level is not null and v_hw_level <> v_student_level then
    raise exception 'This homework is not assigned to your level';
  end if;

  -- a teacher's manual grade is authoritative and never overwritten
  select hs.score, hs.feedback into v_existing_score, v_existing_feedback
  from public.homework_status hs
  where hs.homework_id = p_homework_id and hs.student_id = v_student_id;
  if v_existing_score is not null
     and (v_existing_feedback is null or v_existing_feedback not like 'Auto-graded%') then
    raise exception 'This homework was already graded by the teacher';
  end if;

  -- re-derive the quiz WITH keys and grade purely server-side
  v_built := public.homework_build_auto_quiz(p_homework_id, v_student_id, true);
  if not coalesce((v_built ->> 'eligible')::boolean, false) then
    raise exception 'This homework does not support automatic grading: %', v_built ->> 'reason';
  end if;

  v_graded := public.homework_grade_auto_stage(v_built, p_stage_key, p_answers);
  v_correct := (v_graded ->> 'correct')::int;
  v_total := (v_graded ->> 'total')::int;

  select r.attempts, r.best_correct, r.total as prev_total into v_prev
  from public.homework_auto_stage_results r
  where r.homework_id = p_homework_id
    and r.student_id = v_student_id
    and r.stage_key = p_stage_key;

  v_attempts := coalesce(v_prev.attempts, 0) + 1;
  -- Best score is per quiz version: if the teacher edited the lesson
  -- vocabulary since the last attempt, totals change and the old best is
  -- meaningless (and could violate best_correct <= total) - reset it.
  if v_prev.prev_total is null or v_prev.prev_total = v_total then
    v_best := greatest(coalesce(v_prev.best_correct, 0), v_correct);
  else
    v_best := v_correct;
  end if;

  insert into public.homework_auto_stage_results
    (homework_id, student_id, stage_key, correct, total, best_correct, attempts, details, updated_at)
  values
    (p_homework_id, v_student_id, p_stage_key, v_correct, v_total, v_best, v_attempts, v_graded -> 'review', now())
  on conflict (homework_id, student_id, stage_key)
  do update set
    correct = excluded.correct,
    total = excluded.total,
    best_correct = excluded.best_correct,
    attempts = excluded.attempts,
    details = excluded.details,
    updated_at = now();

  -- overall = best-per-stage over current quiz totals (deterministic)
  for v_row in
    select (s ->> 'key') as skey,
           (select coalesce(sum(
              case when (q ->> 'type') = 'match'
                   then greatest(jsonb_array_length(q -> 'left'), 1)
                   else 1 end
            ), 0)::int
            from jsonb_array_elements(s -> 'questions') q) as stotal
    from jsonb_array_elements(
      public.homework_build_auto_quiz(p_homework_id, v_student_id, false) -> 'stages'
    ) s
  loop
    v_overall_total := v_overall_total + v_row.stotal;
  end loop;

  for v_row in
    select r.stage_key, r.best_correct
    from public.homework_auto_stage_results r
    where r.homework_id = p_homework_id and r.student_id = v_student_id
  loop
    v_overall_correct := v_overall_correct + v_row.best_correct;
    v_done := v_done + 1;
  end loop;

  v_pct := case when v_overall_total > 0
    then round(100.0 * v_overall_correct / v_overall_total)::int else 0 end;

  -- persist the authoritative result on homework_status (satisfies the
  -- score/feedback CHECKs: Graded + score + Graded-only feedback).
  -- No points are awarded here - manual Academy point flow is untouched.
  insert into public.homework_status
    (homework_id, student_id, status, score, feedback, submitted_at)
  values
    (p_homework_id, v_student_id, 'Graded', v_pct,
     format('Auto-graded: %s/%s correct (%s%%) · %s/3 stages complete',
            v_overall_correct, v_overall_total, v_pct, v_done),
     now())
  on conflict (homework_id, student_id)
  do update set
    status = 'Graded',
    score = excluded.score,
    feedback = excluded.feedback,
    submitted_at = excluded.submitted_at;

  return jsonb_build_object(
    'stage', jsonb_build_object(
      'key', p_stage_key, 'correct', v_correct, 'total', v_total,
      'best_correct', v_best, 'attempts', v_attempts
    ),
    'overall', jsonb_build_object(
      'correct', v_overall_correct, 'total', v_overall_total,
      'percentage', v_pct, 'stages_completed', v_done
    ),
    'review', v_graded -> 'review'
  );
end;
$$;

revoke execute on function public.submit_homework_auto_stage(bigint, text, jsonb) from anon;
revoke execute on function public.submit_homework_auto_stage(bigint, text, jsonb) from public;
grant execute on function public.submit_homework_auto_stage(bigint, text, jsonb) to authenticated;

-- Helper normalization: pure function, same convention as other RLS/SQL
-- helpers (explicit anon revoke, authenticated grant).
revoke execute on function public.homework_normalize_answer(text) from anon;
revoke execute on function public.homework_normalize_answer(text) from public;
grant execute on function public.homework_normalize_answer(text) to authenticated;
