-- Online English Tests: Test 9 frozen content (Lessons 81-90).
-- Generated by scripts/build-online-test1-migration.cjs from
-- src/features/onlineTests/data/test9.json. Do not hand-edit;
-- regenerate instead. Inserts are DO NOTHING on conflict so
-- re-applying never mutates published (frozen) items.

insert into public.online_tests (test_number, title, lesson_from, lesson_to, is_published)
values (9, 'Test 9', 81, 90, true)
on conflict (test_number) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'vocabulary', 'multiple_choice', 1, '{"question":"What does “Qurilma” mean in English?","options":["device","screen","battery","search"]}'::jsonb, '{"correct_value":"device"}'::jsonb, 1, 'L81 technology')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'vocabulary', 'multiple_choice', 2, '{"question":"What does “Izoh” mean in English?","options":["comment","profile","share","private"]}'::jsonb, '{"correct_value":"comment"}'::jsonb, 1, 'L82 social media')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'vocabulary', 'multiple_choice', 3, '{"question":"What does “Chunki” mean in English?","options":["because","opinion","probably","certainly"]}'::jsonb, '{"correct_value":"because"}'::jsonb, 1, 'L83 opinions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'vocabulary', 'matching', 4, '{"instruction":"Match each environment word with its Uzbek word.","left":["pollution","recycle","rubbish","nature"],"right":["Ifloslanish","Qayta ishlash","Axlat","Tabiat"]}'::jsonb, '{"pairs":[["pollution","Ifloslanish"],["recycle","Qayta ishlash"],["rubbish","Axlat"],["nature","Tabiat"]]}'::jsonb, 1, 'L85 environment')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'vocabulary', 'multiple_choice', 5, '{"question":"What does “Biroq” mean in English?","options":["however","exactly","perhaps","in fact"]}'::jsonb, '{"correct_value":"however"}'::jsonb, 1, 'L84 agreement')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'vocabulary', 'multiple_choice', 6, '{"question":"What does “Agar” mean in English?","options":["if","will","probably","instead"]}'::jsonb, '{"correct_value":"if"}'::jsonb, 1, 'L86 conditional')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'vocabulary', 'matching', 7, '{"instruction":"Match each debate word with its Uzbek word.","left":["debate","reason","support","conclusion"],"right":["Munozara","Sabab","Qo''llab-quvvatlamoq","Xulosa"]}'::jsonb, '{"pairs":[["debate","Munozara"],["reason","Sabab"],["support","Qo''llab-quvvatlamoq"],["conclusion","Xulosa"]]}'::jsonb, 1, 'L87 debate')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'vocabulary', 'multiple_choice', 8, '{"question":"What does “Tinch” mean in English?","options":["peaceful","crowded","noisy","convenient"]}'::jsonb, '{"correct_value":"peaceful"}'::jsonb, 1, 'L89 city-country')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'vocabulary', 'multiple_choice', 9, '{"question":"What does “Festival” mean in English?","options":["festival","culture","custom","exchange"]}'::jsonb, '{"correct_value":"festival"}'::jsonb, 1, 'L90 cultures')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'vocabulary', 'multiple_choice', 10, '{"question":"What does “Hurmat” mean in English?","options":["respect","opinion","reason","conclusion"]}'::jsonb, '{"correct_value":"respect"}'::jsonb, 1, 'L88 opinions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'grammar', 'multiple_choice', 1, '{"question":"I ___ used this app.","options":["have","has"]}'::jsonb, '{"correct_value":"have"}'::jsonb, 1, 'L81 present perfect')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'grammar', 'multiple_choice', 2, '{"question":"Which sentence is correct?","options":["I have download it.","I have downloaded it.","I has downloaded it."]}'::jsonb, '{"correct_value":"I have downloaded it."}'::jsonb, 1, 'L81 present perfect correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'grammar', 'multiple_choice', 3, '{"question":"You ___ share your password.","options":["shouldn''t","should"]}'::jsonb, '{"correct_value":"shouldn''t"}'::jsonb, 1, 'L82 social media')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'grammar', 'multiple_choice', 4, '{"question":"___ my opinion, it''s great.","options":["In","On"]}'::jsonb, '{"correct_value":"In"}'::jsonb, 1, 'L83 opinions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'grammar', 'multiple_choice', 5, '{"question":"I completely ___.","options":["agree","disagree"]}'::jsonb, '{"correct_value":"agree"}'::jsonb, 1, 'L84 agreement')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'grammar', 'multiple_choice', 6, '{"question":"If you study, you ___ pass.","options":["will","does"]}'::jsonb, '{"correct_value":"will"}'::jsonb, 1, 'L86 conditional')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'grammar', 'multiple_choice', 7, '{"question":"Which sentence is correct?","options":["If it will rain, I stay.","If it rains, I will stay.","If it rains, I stay."]}'::jsonb, '{"correct_value":"If it rains, I will stay."}'::jsonb, 1, 'L86 conditional correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'grammar', 'multiple_choice', 8, '{"question":"An ___ of the village is fresh air.","options":["advantage","disadvantage"]}'::jsonb, '{"correct_value":"advantage"}'::jsonb, 1, 'L89 city-country')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'grammar', 'multiple_choice', 9, '{"question":"It is a ___ to drink tea.","options":["tradition","traditional"]}'::jsonb, '{"correct_value":"tradition"}'::jsonb, 1, 'L90 cultures')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'grammar', 'multiple_choice', 10, '{"question":"Give me a ___.","options":["reason","reasons"]}'::jsonb, '{"correct_value":"reason"}'::jsonb, 1, 'L87 debate')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'sentences', 'ordering', 1, '{"instruction":"Put the words in order.","tokens":["Respect","different","views."]}'::jsonb, '{"correct_order":["Respect","different","views."]}'::jsonb, 1, 'L88 opinions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'sentences', 'ordering', 2, '{"instruction":"Put the words in order.","tokens":["I","think","English","is","important."]}'::jsonb, '{"correct_order":["I","think","English","is","important."]}'::jsonb, 1, 'L83 opinions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'sentences', 'fill_blank', 3, '{"instruction":"Fill in the blank.","template":"I''m afraid I ___."}'::jsonb, '{"answer":"disagree"}'::jsonb, 1, 'L84 agreement')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'sentences', 'fill_blank', 4, '{"instruction":"Fill in the blank.","template":"We should ___ plastic."}'::jsonb, '{"answer":"recycle"}'::jsonb, 1, 'L85 environment')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'sentences', 'ordering', 5, '{"instruction":"Put the words in order.","tokens":["The","countryside","is","peaceful."]}'::jsonb, '{"correct_order":["The","countryside","is","peaceful."]}'::jsonb, 1, 'L89 city-country')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'sentences', 'fill_blank', 6, '{"instruction":"Fill in the blank.","template":"___ Japan, people bow."}'::jsonb, '{"answer":"In"}'::jsonb, 1, 'L90 cultures')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'sentences', 'fill_blank', 7, '{"instruction":"Fill in the blank.","template":"Keep your profile ___."}'::jsonb, '{"answer":"private"}'::jsonb, 1, 'L82 social media')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'sentences', 'ordering', 8, '{"instruction":"Put the words in order.","tokens":["I","am","against","this","idea."]}'::jsonb, '{"correct_order":["I","am","against","this","idea."]}'::jsonb, 1, 'L87 debate')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'writing', 'translation', 1, '{"instruction":"Translate into English.","source_text":"Xulosa","direction":"uz2en"}'::jsonb, '{"target_text":"conclusion"}'::jsonb, 1, 'L88 opinions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'writing', 'translation', 2, '{"instruction":"Translate into English.","source_text":"Sport qiziqarli.","direction":"uz2en"}'::jsonb, '{"target_text":"Sport is fun."}'::jsonb, 1, 'L83 opinions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'writing', 'translation', 3, '{"instruction":"Translate into English.","source_text":"Siz bilan to''liq roziman.","direction":"uz2en"}'::jsonb, '{"target_text":"I completely agree with you."}'::jsonb, 1, 'L84 agreement')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'writing', 'ordering', 4, '{"instruction":"Put the words in order.","tokens":["We","should","recycle","more."]}'::jsonb, '{"correct_order":["We","should","recycle","more."]}'::jsonb, 1, 'L85 environment')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'writing', 'translation', 5, '{"instruction":"Translate into English.","source_text":"Bashorat qilmoq","direction":"uz2en"}'::jsonb, '{"target_text":"predict"}'::jsonb, 1, 'L86 conditional')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 9), 'writing', 'translation', 6, '{"instruction":"Translate into English.","source_text":"Parol","direction":"uz2en"}'::jsonb, '{"target_text":"password"}'::jsonb, 1, 'L82 social media')
on conflict (test_id, stage, position) do nothing;
