-- Online English Tests: Test 7 frozen content (Lessons 61-70).
-- Generated by scripts/build-online-test1-migration.cjs from
-- src/features/onlineTests/data/test7.json. Do not hand-edit;
-- regenerate instead. Inserts are DO NOTHING on conflict so
-- re-applying never mutates published (frozen) items.

insert into public.online_tests (test_number, title, lesson_from, lesson_to, is_published)
values (7, 'Test 7', 61, 70, true)
on conflict (test_number) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'vocabulary', 'multiple_choice', 1, '{"question":"What does “Sovg''a” mean in English?","options":["gift","tradition","guest","invite"]}'::jsonb, '{"correct_value":"gift"}'::jsonb, 1, 'L61 holidays')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'vocabulary', 'multiple_choice', 2, '{"question":"What does “Poyezd” mean in English?","options":["train","plane","bus","ticket"]}'::jsonb, '{"correct_value":"train"}'::jsonb, 1, 'L62 travel')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'vocabulary', 'multiple_choice', 3, '{"question":"What does “Bojxona” mean in English?","options":["customs","security","gate","delayed"]}'::jsonb, '{"correct_value":"customs"}'::jsonb, 1, 'L63 airport')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'vocabulary', 'matching', 4, '{"instruction":"Match each health word with its Uzbek word.","left":["healthy","sleep","fresh","habit"],"right":["Sog''lom","Uyqu","Yangi","Odat"]}'::jsonb, '{"pairs":[["healthy","Sog''lom"],["sleep","Uyqu"],["fresh","Yangi"],["habit","Odat"]]}'::jsonb, 1, 'L69 health')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'vocabulary', 'multiple_choice', 5, '{"question":"What does “Nihoyat” mean in English?","options":["finally","first","then","after that"]}'::jsonb, '{"correct_value":"finally"}'::jsonb, 1, 'L64 sequencing')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'vocabulary', 'multiple_choice', 6, '{"question":"What does “Sokin” mean in English?","options":["quiet","crowded","modern","ancient"]}'::jsonb, '{"correct_value":"quiet"}'::jsonb, 1, 'L65 cities')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'vocabulary', 'matching', 7, '{"instruction":"Match each feeling with its Uzbek word.","left":["happy","sad","angry","tired"],"right":["Xursand","G''amgin","Jahli chiqqan","Charchagan"]}'::jsonb, '{"pairs":[["happy","Xursand"],["sad","G''amgin"],["angry","Jahli chiqqan"],["tired","Charchagan"]]}'::jsonb, 1, 'L70 feelings')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'vocabulary', 'multiple_choice', 8, '{"question":"What does “To''y” mean in English?","options":["wedding","culture","ceremony","respect"]}'::jsonb, '{"correct_value":"wedding"}'::jsonb, 1, 'L66 traditions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'vocabulary', 'multiple_choice', 9, '{"question":"What does “Kirish to''lovi” mean in English?","options":["entrance fee","budget","schedule","guide"]}'::jsonb, '{"correct_value":"entrance fee"}'::jsonb, 1, 'L67 trip')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'vocabulary', 'multiple_choice', 10, '{"question":"What does “Dengiz qirg''og''i” mean in English?","options":["beach","rest","memories","enjoy"]}'::jsonb, '{"correct_value":"beach"}'::jsonb, 1, 'L68 holiday')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'grammar', 'multiple_choice', 1, '{"question":"How ___ you celebrate Nowruz?","options":["do","does"]}'::jsonb, '{"correct_value":"do"}'::jsonb, 1, 'L61 holidays')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'grammar', 'multiple_choice', 2, '{"question":"Which sentence is correct?","options":["How you celebrate Nowruz?","How do you celebrate Nowruz?","How does you celebrate Nowruz?"]}'::jsonb, '{"correct_value":"How do you celebrate Nowruz?"}'::jsonb, 1, 'L61 holidays correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'grammar', 'multiple_choice', 3, '{"question":"We travel ___ plane.","options":["by","on"]}'::jsonb, '{"correct_value":"by"}'::jsonb, 1, 'L62 travel')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'grammar', 'multiple_choice', 4, '{"question":"Where ___ the check-in desk?","options":["is","are"]}'::jsonb, '{"correct_value":"is"}'::jsonb, 1, 'L63 airport')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'grammar', 'multiple_choice', 5, '{"question":"This is ___ city.","options":["the oldest","older"]}'::jsonb, '{"correct_value":"the oldest"}'::jsonb, 1, 'L65 cities')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'grammar', 'multiple_choice', 6, '{"question":"Which is correct?","options":["the more biggest","the biggest","most biggest"]}'::jsonb, '{"correct_value":"the biggest"}'::jsonb, 1, 'L65 cities correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'grammar', 'multiple_choice', 7, '{"question":"___ we packed our bags.","options":["First","Finally"]}'::jsonb, '{"correct_value":"First"}'::jsonb, 1, 'L64 sequencing')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'grammar', 'multiple_choice', 8, '{"question":"Which sentence is correct?","options":["You should to eat fruit.","You should eat fruit.","You should eating fruit."]}'::jsonb, '{"correct_value":"You should eat fruit."}'::jsonb, 1, 'L69 health correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'grammar', 'multiple_choice', 9, '{"question":"I am ___ before the exam.","options":["nervous","happy"]}'::jsonb, '{"correct_value":"nervous"}'::jsonb, 1, 'L70 feelings')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'grammar', 'multiple_choice', 10, '{"question":"It is ___ tradition to greet guests.","options":["a","the"]}'::jsonb, '{"correct_value":"a"}'::jsonb, 1, 'L66 traditions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'sentences', 'ordering', 1, '{"instruction":"Put the words in order.","tokens":["The","train","departs","at","8:30."]}'::jsonb, '{"correct_order":["The","train","departs","at","8:30."]}'::jsonb, 1, 'L62 travel')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'sentences', 'ordering', 2, '{"instruction":"Put the words in order.","tokens":["First","we","bought","tickets."]}'::jsonb, '{"correct_order":["First","we","bought","tickets."]}'::jsonb, 1, 'L64 sequencing')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'sentences', 'fill_blank', 3, '{"instruction":"Fill in the blank.","template":"The flight is ___."}'::jsonb, '{"answer":"delayed"}'::jsonb, 1, 'L63 airport')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'sentences', 'fill_blank', 4, '{"instruction":"Fill in the blank.","template":"A ___ will show us around."}'::jsonb, '{"answer":"guide"}'::jsonb, 1, 'L67 trip')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'sentences', 'ordering', 5, '{"instruction":"Put the words in order.","tokens":["I","am","happy","because","I","passed."]}'::jsonb, '{"correct_order":["I","am","happy","because","I","passed."]}'::jsonb, 1, 'L70 feelings')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'sentences', 'fill_blank', 6, '{"instruction":"Fill in the blank.","template":"We ___ our guests."}'::jsonb, '{"answer":"welcome"}'::jsonb, 1, 'L66 traditions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'sentences', 'fill_blank', 7, '{"instruction":"Fill in the blank.","template":"The ___ fee is 10,000 som."}'::jsonb, '{"answer":"entrance"}'::jsonb, 1, 'L67 trip')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'sentences', 'fill_blank', 8, '{"instruction":"Fill in the past verb.","template":"We ___ (go) to the beach."}'::jsonb, '{"answer":"went"}'::jsonb, 1, 'L68 holiday')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'writing', 'translation', 1, '{"instruction":"Translate into English.","source_text":"Navro''zni qanday nishonlaysiz?","direction":"uz2en"}'::jsonb, '{"target_text":"How do you celebrate Nowruz?"}'::jsonb, 1, 'L61 holidays')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'writing', 'translation', 2, '{"instruction":"Translate into English.","source_text":"Poyezd 8:30 da jo''naydi.","direction":"uz2en"}'::jsonb, '{"target_text":"The train departs at 8:30."}'::jsonb, 1, 'L62 travel')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'writing', 'translation', 3, '{"instruction":"Translate into English.","source_text":"Menda ajoyib xotiralar bor.","direction":"uz2en"}'::jsonb, '{"target_text":"I have wonderful memories."}'::jsonb, 1, 'L68 holiday')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'writing', 'ordering', 4, '{"instruction":"Put the words in order.","tokens":["It","is","a","tradition","to","eat","plov."]}'::jsonb, '{"correct_order":["It","is","a","tradition","to","eat","plov."]}'::jsonb, 1, 'L66 traditions correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'writing', 'translation', 5, '{"instruction":"Translate into English.","source_text":"Ko''proq suv ichishingiz kerak.","direction":"uz2en"}'::jsonb, '{"target_text":"You should drink more water."}'::jsonb, 1, 'L69 health')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 7), 'writing', 'translation', 6, '{"instruction":"Translate into English.","source_text":"Xavotirlangan","direction":"uz2en"}'::jsonb, '{"target_text":"worried"}'::jsonb, 1, 'L70 feelings')
on conflict (test_id, stage, position) do nothing;
