-- Online English Tests: Test 6 frozen content (Lessons 51-60).
-- Generated by scripts/build-online-test1-migration.cjs from
-- src/features/onlineTests/data/test6.json. Do not hand-edit;
-- regenerate instead. Inserts are DO NOTHING on conflict so
-- re-applying never mutates published (frozen) items.

insert into public.online_tests (test_number, title, lesson_from, lesson_to, is_published)
values (6, 'Test 6', 51, 60, true)
on conflict (test_number) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'vocabulary', 'multiple_choice', 1, '{"question":"What does “Sayil” mean in English?","options":["picnic","concert","ticket","together"]}'::jsonb, '{"correct_value":"picnic"}'::jsonb, 1, 'L54 plans')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'vocabulary', 'multiple_choice', 2, '{"question":"What does “Shaxmat o''ynamoq” mean in English?","options":["play chess","play games","watch movies","read comics"]}'::jsonb, '{"correct_value":"play chess"}'::jsonb, 1, 'L52 free time')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'vocabulary', 'multiple_choice', 3, '{"question":"What does “Zerikarli” mean in English?","options":["boring","hobby","usually","sometimes"]}'::jsonb, '{"correct_value":"boring"}'::jsonb, 1, 'L55 free time')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'vocabulary', 'matching', 4, '{"instruction":"Match each frequency word with its Uzbek word.","left":["always","usually","sometimes","never"],"right":["Har doim","Odatda","Ba''zan","Hech qachon"]}'::jsonb, '{"pairs":[["always","Har doim"],["usually","Odatda"],["sometimes","Ba''zan"],["never","Hech qachon"]]}'::jsonb, 1, 'L57 frequency')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'vocabulary', 'multiple_choice', 5, '{"question":"What does “Bilet” mean in English?","options":["ticket","picnic","concert","together"]}'::jsonb, '{"correct_value":"ticket"}'::jsonb, 1, 'L54 plans')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'vocabulary', 'multiple_choice', 6, '{"question":"What does “Bo''sh vaqt” mean in English?","options":["free time","every day","usually","sometimes"]}'::jsonb, '{"correct_value":"free time"}'::jsonb, 1, 'L55 free time')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'vocabulary', 'matching', 7, '{"instruction":"Match each trip word with its Uzbek word.","left":["mountain","lake","map","backpack"],"right":["Tog''","Ko''l","Xarita","Ryukzak"]}'::jsonb, '{"pairs":[["mountain","Tog''"],["lake","Ko''l"],["map","Xarita"],["backpack","Ryukzak"]]}'::jsonb, 1, 'L59 trip')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'vocabulary', 'multiple_choice', 8, '{"question":"What does “Uy vazifasi” mean in English?","options":["homework","class","sports","weekend"]}'::jsonb, '{"correct_value":"homework"}'::jsonb, 1, 'L58 week')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'vocabulary', 'multiple_choice', 9, '{"question":"What does “Takrorlash” mean in English?","options":["review","remember","happen","plan"]}'::jsonb, '{"correct_value":"review"}'::jsonb, 1, 'L60 review')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'vocabulary', 'multiple_choice', 10, '{"question":"What does “Eslab qolmoq” mean in English?","options":["remember","happen","review","plan"]}'::jsonb, '{"correct_value":"remember"}'::jsonb, 1, 'L60 review')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'grammar', 'multiple_choice', 1, '{"question":"This phone is ___ expensive than that one.","options":["more","most"]}'::jsonb, '{"correct_value":"more"}'::jsonb, 1, 'L51 comparatives')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'grammar', 'multiple_choice', 2, '{"question":"Which is correct?","options":["more big","bigger","more bigger"]}'::jsonb, '{"correct_value":"bigger"}'::jsonb, 1, 'L51 comparatives correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'grammar', 'multiple_choice', 3, '{"question":"I like ___ chess.","options":["playing","play"]}'::jsonb, '{"correct_value":"playing"}'::jsonb, 1, 'L52 like-ing')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'grammar', 'multiple_choice', 4, '{"question":"Would you like ___ come?","options":["to","for"]}'::jsonb, '{"correct_value":"to"}'::jsonb, 1, 'L53 invitations')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'grammar', 'multiple_choice', 5, '{"question":"Which sentence is correct?","options":["Would you like come?","Would you like to come?","Would you like coming?"]}'::jsonb, '{"correct_value":"Would you like to come?"}'::jsonb, 1, 'L53 invitations correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'grammar', 'multiple_choice', 6, '{"question":"___ Friday I go to the club.","options":["On","In"]}'::jsonb, '{"correct_value":"On"}'::jsonb, 1, 'L58 week')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'grammar', 'multiple_choice', 7, '{"question":"Which sentence is correct?","options":["I do always my homework.","I always do my homework.","I always does my homework."]}'::jsonb, '{"correct_value":"I always do my homework."}'::jsonb, 1, 'L57 frequency correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'grammar', 'multiple_choice', 8, '{"question":"___ Monday I go to school.","options":["On","In"]}'::jsonb, '{"correct_value":"On"}'::jsonb, 1, 'L58 on-days')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'grammar', 'multiple_choice', 9, '{"question":"She ___ a film.","options":["watched","watch"]}'::jsonb, '{"correct_value":"watched"}'::jsonb, 1, 'L56 past simple')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'grammar', 'multiple_choice', 10, '{"question":"We''re going to ___ camping.","options":["go","going"]}'::jsonb, '{"correct_value":"go"}'::jsonb, 1, 'L59 going-to')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'sentences', 'ordering', 1, '{"instruction":"Put the words in order.","tokens":["A","car","is","faster."]}'::jsonb, '{"correct_order":["A","car","is","faster."]}'::jsonb, 1, 'L51 comparatives')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'sentences', 'ordering', 2, '{"instruction":"Put the words in order.","tokens":["I","like","playing","chess."]}'::jsonb, '{"correct_order":["I","like","playing","chess."]}'::jsonb, 1, 'L52 like-ing')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'sentences', 'fill_blank', 3, '{"instruction":"Fill in the blank.","template":"We''re going to ___ a picnic."}'::jsonb, '{"answer":"have"}'::jsonb, 1, 'L54 plans')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'sentences', 'fill_blank', 4, '{"instruction":"Fill in the -ing form.","template":"I like ___ (swim)."}'::jsonb, '{"answer":"swimming"}'::jsonb, 1, 'L55 like-ing')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'sentences', 'ordering', 5, '{"instruction":"Put the words in order.","tokens":["On","Saturday","I","went","fishing."]}'::jsonb, '{"correct_order":["On","Saturday","I","went","fishing."]}'::jsonb, 1, 'L56 weekend')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'sentences', 'fill_blank', 6, '{"instruction":"Fill in the blank.","template":"She is ___ on time."}'::jsonb, '{"answer":"always"}'::jsonb, 1, 'L57 frequency')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'sentences', 'ordering', 7, '{"instruction":"Put the words in order.","tokens":["I","am","going","to","take","photos."]}'::jsonb, '{"correct_order":["I","am","going","to","take","photos."]}'::jsonb, 1, 'L59 trip')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'sentences', 'fill_blank', 8, '{"instruction":"Fill in the past verb.","template":"The past of “buy” is ___."}'::jsonb, '{"answer":"bought"}'::jsonb, 1, 'L60 review')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'writing', 'translation', 1, '{"instruction":"Translate into English.","source_text":"Kattaroq","direction":"uz2en"}'::jsonb, '{"target_text":"bigger"}'::jsonb, 1, 'L51 comparatives')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'writing', 'fill_blank', 2, '{"instruction":"Fill in the -ing form.","template":"She loves ___ (dance)."}'::jsonb, '{"answer":"dancing"}'::jsonb, 1, 'L52 like-ing')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'writing', 'ordering', 3, '{"instruction":"Put the words in order.","tokens":["Would","you","like","to","come?"]}'::jsonb, '{"correct_order":["Would","you","like","to","come?"]}'::jsonb, 1, 'L53 invitations correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'writing', 'ordering', 4, '{"instruction":"Put the words in order.","tokens":["On","Sunday","I","watched","a","film."]}'::jsonb, '{"correct_order":["On","Sunday","I","watched","a","film."]}'::jsonb, 1, 'L56 past correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'writing', 'fill_blank', 5, '{"instruction":"Fill in the blank.","template":"I ___ (never) eat candy in the morning."}'::jsonb, '{"answer":"never"}'::jsonb, 1, 'L57 frequency')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 6), 'writing', 'fill_blank', 6, '{"instruction":"Fill in the blank.","template":"I''m going to take ___."}'::jsonb, '{"answer":"photos"}'::jsonb, 1, 'L59 trip')
on conflict (test_id, stage, position) do nothing;
