-- Online English Tests: Test 4 frozen content (Lessons 31-40).
-- Generated by scripts/build-online-test1-migration.cjs from
-- src/features/onlineTests/data/test4.json. Do not hand-edit;
-- regenerate instead. Inserts are DO NOTHING on conflict so
-- re-applying never mutates published (frozen) items.

insert into public.online_tests (test_number, title, lesson_from, lesson_to, is_published)
values (4, 'Test 4', 31, 40, true)
on conflict (test_number) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'vocabulary', 'multiple_choice', 1, '{"question":"What does “Tagida” mean in English?","options":["under","in","on","next to"]}'::jsonb, '{"correct_value":"under"}'::jsonb, 1, 'L31 prepositions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'vocabulary', 'multiple_choice', 2, '{"question":"What does “Bozor” mean in English?","options":["market","shop","street","bank"]}'::jsonb, '{"correct_value":"market"}'::jsonb, 1, 'L32 neighborhood')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'vocabulary', 'matching', 3, '{"instruction":"Match each review word with its Uzbek word.","left":["Routine","Furniture","Price","Street"],"right":["Tartib","Mebel","Narx","Ko''cha"]}'::jsonb, '{"pairs":[["Routine","Tartib"],["Furniture","Mebel"],["Price","Narx"],["Street","Ko''cha"]]}'::jsonb, 1, 'L40 review')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'vocabulary', 'multiple_choice', 4, '{"question":"What does “Xarita” mean in English?","options":["map","corner","stop","left"]}'::jsonb, '{"correct_value":"map"}'::jsonb, 1, 'L36 directions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'vocabulary', 'multiple_choice', 5, '{"question":"What does “Ming” mean in English?","options":["thousand","hundred","money","price"]}'::jsonb, '{"correct_value":"thousand"}'::jsonb, 1, 'L39 numbers')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'vocabulary', 'multiple_choice', 6, '{"question":"What does “Ko''cha” mean in English?","options":["street","map","corner","shop"]}'::jsonb, '{"correct_value":"street"}'::jsonb, 1, 'L37 map')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'vocabulary', 'matching', 7, '{"instruction":"Match each furniture word with its Uzbek word.","left":["Shelf","Mirror","Carpet","Wardrobe"],"right":["Tokcha","Oyna","Gilam","Shkaf"]}'::jsonb, '{"pairs":[["Shelf","Tokcha"],["Mirror","Oyna"],["Carpet","Gilam"],["Wardrobe","Shkaf"]]}'::jsonb, 1, 'L33 furniture')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'vocabulary', 'multiple_choice', 8, '{"question":"What does “Mahalla” mean in English?","options":["neighborhood","house","street","park"]}'::jsonb, '{"correct_value":"neighborhood"}'::jsonb, 1, 'L38 town')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'vocabulary', 'multiple_choice', 9, '{"question":"What does “furniture” mean in Uzbek?","options":["Mebel","Mahalla","Narx","Ko''cha"]}'::jsonb, '{"correct_value":"Mebel"}'::jsonb, 1, 'L40 review')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'vocabulary', 'multiple_choice', 10, '{"question":"What does “Burchak” mean in English?","options":["corner","street","map","straight"]}'::jsonb, '{"correct_value":"corner"}'::jsonb, 1, 'L37 map')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'grammar', 'multiple_choice', 1, '{"question":"Where ___ your books?","options":["is","are"]}'::jsonb, '{"correct_value":"are"}'::jsonb, 1, 'L31 where')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'grammar', 'multiple_choice', 2, '{"question":"There ___ two sofas.","options":["is","are"]}'::jsonb, '{"correct_value":"are"}'::jsonb, 1, 'L33 furniture')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'grammar', 'multiple_choice', 3, '{"question":"The hospital is far ___ the school.","options":["from","at"]}'::jsonb, '{"correct_value":"from"}'::jsonb, 1, 'L32 far')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'grammar', 'multiple_choice', 4, '{"question":"Which sentence is correct?","options":["The cat is under of the table.","The cat is under the table.","The cat is under a table."]}'::jsonb, '{"correct_value":"The cat is under the table."}'::jsonb, 1, 'L34 prepositions correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'grammar', 'multiple_choice', 5, '{"question":"There ___ a clock on the wall.","options":["is","are"]}'::jsonb, '{"correct_value":"is"}'::jsonb, 1, 'L35 there-is')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'grammar', 'multiple_choice', 6, '{"question":"Which sentence is correct?","options":["There is two pictures.","There are two pictures.","There are two picture."]}'::jsonb, '{"correct_value":"There are two pictures."}'::jsonb, 1, 'L35 there-are correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'grammar', 'multiple_choice', 7, '{"question":"___ left at the bank.","options":["Turn","Go"]}'::jsonb, '{"correct_value":"Turn"}'::jsonb, 1, 'L36 directions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'grammar', 'multiple_choice', 8, '{"question":"The bank is ___ the corner.","options":["on","at"]}'::jsonb, '{"correct_value":"on"}'::jsonb, 1, 'L38 town')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'grammar', 'multiple_choice', 9, '{"question":"Which sentence is correct?","options":["How much it is?","How much is it?","How much are it?"]}'::jsonb, '{"correct_value":"How much is it?"}'::jsonb, 1, 'L39 prices correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'grammar', 'multiple_choice', 10, '{"question":"Which sentence is correct?","options":["There are a bed.","There is a bed.","There is a beds."]}'::jsonb, '{"correct_value":"There is a bed."}'::jsonb, 1, 'L33 there-is correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'sentences', 'ordering', 1, '{"instruction":"Put the words in order.","tokens":["Where","is","the","lamp?"]}'::jsonb, '{"correct_order":["Where","is","the","lamp?"]}'::jsonb, 1, 'L31 where')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'sentences', 'ordering', 2, '{"instruction":"Put the words in order.","tokens":["There","is","a","park","near","my","house."]}'::jsonb, '{"correct_order":["There","is","a","park","near","my","house."]}'::jsonb, 1, 'L32 neighborhood')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'sentences', 'fill_blank', 3, '{"instruction":"Fill in the blank.","template":"The picture is ___ the wall."}'::jsonb, '{"answer":"on"}'::jsonb, 1, 'L34 prepositions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'sentences', 'fill_blank', 4, '{"instruction":"Fill in the blank.","template":"Go ___ for one block."}'::jsonb, '{"answer":"straight"}'::jsonb, 1, 'L36 directions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'sentences', 'ordering', 5, '{"instruction":"Put the words in order.","tokens":["The","ticket","costs","two","thousand","som."]}'::jsonb, '{"correct_order":["The","ticket","costs","two","thousand","som."]}'::jsonb, 1, 'L39 prices')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'sentences', 'fill_blank', 6, '{"instruction":"Fill in the blank.","template":"There ___ blue curtains on the window."}'::jsonb, '{"answer":"are"}'::jsonb, 1, 'L35 room')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'sentences', 'ordering', 7, '{"instruction":"Put the words in order.","tokens":["The","shop","is","near","the","school."]}'::jsonb, '{"correct_order":["The","shop","is","near","the","school."]}'::jsonb, 1, 'L38 town')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'sentences', 'fill_blank', 8, '{"instruction":"Fill in the blank.","template":"Excuse me, ___ is the bank?"}'::jsonb, '{"answer":"where"}'::jsonb, 1, 'L37 directions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'writing', 'translation', 1, '{"instruction":"Translate into English.","source_text":"Mushuk stul tagida.","direction":"uz2en"}'::jsonb, '{"target_text":"The cat is under the chair."}'::jsonb, 1, 'L31 prepositions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'writing', 'translation', 2, '{"instruction":"Translate into English.","source_text":"Kitob qancha turadi?","direction":"uz2en"}'::jsonb, '{"target_text":"How much is the book?"}'::jsonb, 1, 'L39 prices')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'writing', 'translation', 3, '{"instruction":"Translate into English.","source_text":"Qalam kitob ustida.","direction":"uz2en"}'::jsonb, '{"target_text":"The pencil is on the book."}'::jsonb, 1, 'L34 prepositions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'writing', 'ordering', 4, '{"instruction":"Put the words in order.","tokens":["Turn","left","at","the","shop."]}'::jsonb, '{"correct_order":["Turn","left","at","the","shop."]}'::jsonb, 1, 'L36 directions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'writing', 'translation', 5, '{"instruction":"Translate into English.","source_text":"Devor","direction":"uz2en"}'::jsonb, '{"target_text":"wall"}'::jsonb, 1, 'L35 room')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 4), 'writing', 'translation', 6, '{"instruction":"Translate into English.","source_text":"Tartib","direction":"uz2en"}'::jsonb, '{"target_text":"Routine"}'::jsonb, 1, 'L40 review')
on conflict (test_id, stage, position) do nothing;
