-- Online English Tests: Test 3 frozen content (Lessons 21-30).
-- Generated by scripts/build-online-test1-migration.cjs from
-- src/features/onlineTests/data/test3.json. Do not hand-edit;
-- regenerate instead. Inserts are DO NOTHING on conflict so
-- re-applying never mutates published (frozen) items.

insert into public.online_tests (test_number, title, lesson_from, lesson_to, is_published)
values (3, 'Test 3', 21, 30, true)
on conflict (test_number) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'vocabulary', 'multiple_choice', 1, '{"question":"What does “Band” mean in English?","options":["Busy","Free","Early","Late"]}'::jsonb, '{"correct_value":"Busy"}'::jsonb, 1, 'L28 frequency')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'vocabulary', 'multiple_choice', 2, '{"question":"What does “Yarim” mean in English?","options":["Half past","Quarter past","Quarter to","O''clock"]}'::jsonb, '{"correct_value":"Half past"}'::jsonb, 1, 'L22 time')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'vocabulary', 'multiple_choice', 3, '{"question":"What does “Non” mean in English?","options":["Bread","Rice","Milk","Cheese"]}'::jsonb, '{"correct_value":"Bread"}'::jsonb, 1, 'L23 food')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'vocabulary', 'matching', 4, '{"instruction":"Match each weather word with its Uzbek word.","left":["Sunny","Rainy","Snowy","Windy"],"right":["Quyoshli","Yomg''irli","Qorli","Shamolli"]}'::jsonb, '{"pairs":[["Sunny","Quyoshli"],["Rainy","Yomg''irli"],["Snowy","Qorli"],["Windy","Shamolli"]]}'::jsonb, 1, 'L26 weather')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'vocabulary', 'multiple_choice', 5, '{"question":"What does “Och” mean in English?","options":["Hungry","Thirsty","Delicious","Please"]}'::jsonb, '{"correct_value":"Hungry"}'::jsonb, 1, 'L24 restaurant')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'vocabulary', 'multiple_choice', 6, '{"question":"What does “Arzon” mean in English?","options":["Cheap","Expensive","Price","Dress"]}'::jsonb, '{"correct_value":"Cheap"}'::jsonb, 1, 'L25 clothes')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'vocabulary', 'matching', 7, '{"instruction":"Match each room with its Uzbek word.","left":["Kitchen","Bedroom","Garden","Bathroom"],"right":["Oshxona","Yotoqxona","Bog''","Hammomxona"]}'::jsonb, '{"pairs":[["Kitchen","Oshxona"],["Bedroom","Yotoqxona"],["Garden","Bog''"],["Bathroom","Hammomxona"]]}'::jsonb, 1, 'L29 rooms')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'vocabulary', 'multiple_choice', 8, '{"question":"What does “Odatda” mean in English?","options":["Usually","Sometimes","Always","Never"]}'::jsonb, '{"correct_value":"Usually"}'::jsonb, 1, 'L28 frequency')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'vocabulary', 'multiple_choice', 9, '{"question":"What does “Qarsak chalmoq” mean in English?","options":["Clap","Skip","Stretch","Spin around"]}'::jsonb, '{"correct_value":"Clap"}'::jsonb, 1, 'L27 actions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'vocabulary', 'multiple_choice', 10, '{"question":"What does “mirror” mean in Uzbek?","options":["Oyna","Stol","Shkaf","Gilam"]}'::jsonb, '{"correct_value":"Oyna"}'::jsonb, 1, 'L30 furniture')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'grammar', 'multiple_choice', 1, '{"question":"I ___ up at 7.","options":["wake","wakes"]}'::jsonb, '{"correct_value":"wake"}'::jsonb, 1, 'L21 routine')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'grammar', 'multiple_choice', 2, '{"question":"Which sentence is correct?","options":["Half past three.","It''s half past three.","Is half past three."]}'::jsonb, '{"correct_value":"It''s half past three."}'::jsonb, 1, 'L22 time correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'grammar', 'multiple_choice', 3, '{"question":"I ___ like milk.","options":["don''t","isn''t"]}'::jsonb, '{"correct_value":"don''t"}'::jsonb, 1, 'L23 likes')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'grammar', 'multiple_choice', 4, '{"question":"Which sentence is correct?","options":["I no like milk.","I don''t like milk.","I doesn''t like milk."]}'::jsonb, '{"correct_value":"I don''t like milk."}'::jsonb, 1, 'L23 likes correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'grammar', 'multiple_choice', 5, '{"question":"They ___ stretch.","options":["can","cans"]}'::jsonb, '{"correct_value":"can"}'::jsonb, 1, 'L27 actions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'grammar', 'multiple_choice', 6, '{"question":"___ shoes are new.","options":["This","These"]}'::jsonb, '{"correct_value":"These"}'::jsonb, 1, 'L25 demonstratives')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'grammar', 'multiple_choice', 7, '{"question":"There ___ a kitchen.","options":["is","are"]}'::jsonb, '{"correct_value":"is"}'::jsonb, 1, 'L29 there-is')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'grammar', 'multiple_choice', 8, '{"question":"There ___ two bedrooms.","options":["is","are"]}'::jsonb, '{"correct_value":"are"}'::jsonb, 1, 'L29 there-are')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'grammar', 'multiple_choice', 9, '{"question":"___ sunny today.","options":["It''s","Is"]}'::jsonb, '{"correct_value":"It''s"}'::jsonb, 1, 'L26 weather')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'grammar', 'multiple_choice', 10, '{"question":"Which sentence is correct?","options":["I wake up 7.","I wake up at 7.","I wakes up at 7."]}'::jsonb, '{"correct_value":"I wake up at 7."}'::jsonb, 1, 'L21 routine correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'sentences', 'ordering', 1, '{"instruction":"Put the words in order.","tokens":["I","wake","up","at","7."]}'::jsonb, '{"correct_order":["I","wake","up","at","7."]}'::jsonb, 1, 'L21 routine')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'sentences', 'ordering', 2, '{"instruction":"Put the words in order.","tokens":["What","time","is","it?"]}'::jsonb, '{"correct_order":["What","time","is","it?"]}'::jsonb, 1, 'L22 time')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'sentences', 'fill_blank', 3, '{"instruction":"Fill in the blank.","template":"Can I have rice, ___?"}'::jsonb, '{"answer":"please"}'::jsonb, 1, 'L24 restaurant')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'sentences', 'fill_blank', 4, '{"instruction":"Fill in the blank.","template":"The opposite of “expensive” is ___."}'::jsonb, '{"answer":"cheap"}'::jsonb, 1, 'L25 opposites')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'sentences', 'ordering', 5, '{"instruction":"Put the words in order.","tokens":["I","usually","wake","up","at","7."]}'::jsonb, '{"correct_order":["I","usually","wake","up","at","7."]}'::jsonb, 1, 'L28 frequency')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'sentences', 'fill_blank', 6, '{"instruction":"Fill in the blank.","template":"There ___ two windows."}'::jsonb, '{"answer":"are"}'::jsonb, 1, 'L29 there-are')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'sentences', 'ordering', 7, '{"instruction":"Put the words in order.","tokens":["Touch","your","toes."]}'::jsonb, '{"correct_order":["Touch","your","toes."]}'::jsonb, 1, 'L27 actions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'sentences', 'ordering', 8, '{"instruction":"Put the words in order.","tokens":["Sit","on","the","sofa."]}'::jsonb, '{"correct_order":["Sit","on","the","sofa."]}'::jsonb, 1, 'L30 furniture')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'writing', 'translation', 1, '{"instruction":"Translate into English.","source_text":"Uyg''onmoq","direction":"uz2en"}'::jsonb, '{"target_text":"Wake up"}'::jsonb, 1, 'L21 routine')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'writing', 'translation', 2, '{"instruction":"Translate into English.","source_text":"Ertalab","direction":"uz2en"}'::jsonb, '{"target_text":"Morning"}'::jsonb, 1, 'L22 time')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'writing', 'translation', 3, '{"instruction":"Translate into English.","source_text":"Suv","direction":"uz2en"}'::jsonb, '{"target_text":"Water"}'::jsonb, 1, 'L23 food')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'writing', 'ordering', 4, '{"instruction":"Put the words in order.","tokens":["Can","I","have","water,","please."]}'::jsonb, '{"correct_order":["Can","I","have","water,","please."]}'::jsonb, 1, 'L24 restaurant correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'writing', 'translation', 5, '{"instruction":"Translate into English.","source_text":"Gilam","direction":"uz2en"}'::jsonb, '{"target_text":"carpet"}'::jsonb, 1, 'L30 furniture')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 3), 'writing', 'translation', 6, '{"instruction":"Translate into English.","source_text":"Yoz","direction":"uz2en"}'::jsonb, '{"target_text":"Summer"}'::jsonb, 1, 'L26 seasons')
on conflict (test_id, stage, position) do nothing;
