-- Groups table for student group management
-- This is separate from class_group (used for class sessions/teacher assignments)

create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Unique constraint on name
create unique index if not exists groups_name_unique_idx
  on public.groups (lower(name));

-- Add group_id to students table
alter table public.students
  add column if not exists group_id bigint references public.groups (id);

-- Add group_id to lessons table
alter table public.lessons
  add column if not exists group_id bigint references public.groups (id);

-- Enable RLS on groups
alter table public.groups enable row level security;

-- Policies for groups
-- Everyone signed in can read groups
drop policy if exists groups_read_all on public.groups;
create policy groups_read_all on public.groups
  for select using (auth.uid() is not null);

-- Admin can manage groups
drop policy if exists groups_admin_all on public.groups;
create policy groups_admin_all on public.groups
  for all using (is_admin()) with check (is_admin());

-- Teacher can read groups (for lesson scheduling)
drop policy if exists groups_teacher_read on public.groups;
create policy groups_teacher_read on public.groups
  for select using (is_teacher());

-- Migrate existing group_name values to groups table
insert into public.groups (name, active, created_at)
select distinct trim(group_name), true, now()
from public.students
where group_name is not null and trim(group_name) != ''
on conflict (lower(name)) do nothing;

insert into public.groups (name, active, created_at)
select distinct trim(group_name), true, now()
from public.lessons
where group_name is not null and trim(group_name) != ''
on conflict (lower(name)) do nothing;

-- Update students.group_id based on group_name
update public.students s
set group_id = g.id
from public.groups g
where s.group_name is not null
  and trim(s.group_name) != ''
  and lower(trim(s.group_name)) = lower(g.name)
  and s.group_id is null;

-- Update lessons.group_id based on group_name
update public.lessons l
set group_id = g.id
from public.groups g
where l.group_name is not null
  and trim(l.group_name) != ''
  and lower(trim(l.group_name)) = lower(g.name)
  and l.group_id is null;

-- Expose group_id through students_view so the app can read student
-- group assignments. CREATE OR REPLACE VIEW cannot reorder/replace
-- columns, so drop and recreate (same approach as migration 0081).
drop view if exists public.students_view;

create or replace view public.students_view
with (security_invoker = true) as
select
  id,
  profile_id,
  real_name,
  english_name,
  level,
  phone,
  parent_phone,
  telegram_chat_id,
  join_date,
  payment_deadline,
  case when is_admin() then monthly_fee else null end as monthly_fee,
  status,
  notes,
  group_name,
  group_id,
  points,
  created_at
from public.students;

grant select on public.students_view to authenticated;