-- Online English Tests: Test 5 frozen content (Lessons 41-50).
-- Generated by scripts/build-online-test1-migration.cjs from
-- src/features/onlineTests/data/test5.json. Do not hand-edit;
-- regenerate instead. Inserts are DO NOTHING on conflict so
-- re-applying never mutates published (frozen) items.

insert into public.online_tests (test_number, title, lesson_from, lesson_to, is_published)
values (5, 'Test 5', 41, 50, true)
on conflict (test_number) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'vocabulary', 'multiple_choice', 1, '{"question":"What does “Qoldi” mean in English?","options":["stayed","went out","got up","yesterday"]}'::jsonb, '{"correct_value":"stayed"}'::jsonb, 1, 'L48 yesterday')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'vocabulary', 'multiple_choice', 2, '{"question":"What does “Bordi” mean in English?","options":["went","saw","came","took"]}'::jsonb, '{"correct_value":"went"}'::jsonb, 1, 'L42 irregular verbs')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'vocabulary', 'multiple_choice', 3, '{"question":"What does “Shakar” mean in English?","options":["sugar","rice","milk","cheese"]}'::jsonb, '{"correct_value":"sugar"}'::jsonb, 1, 'L43 food')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'vocabulary', 'matching', 4, '{"instruction":"Match each job with its Uzbek word.","left":["doctor","teacher","nurse","driver"],"right":["Shifokor","O''qituvchi","Hamshira","Haydovchi"]}'::jsonb, '{"pairs":[["doctor","Shifokor"],["teacher","O''qituvchi"],["nurse","Hamshira"],["driver","Haydovchi"]]}'::jsonb, 1, 'L46 jobs')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'vocabulary', 'multiple_choice', 5, '{"question":"What does “Quti” mean in English?","options":["box","bottle","packet","litre"]}'::jsonb, '{"correct_value":"box"}'::jsonb, 1, 'L44 containers')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'vocabulary', 'multiple_choice', 6, '{"question":"What does “Chek” mean in English?","options":["receipt","cashier","discount","bag"]}'::jsonb, '{"correct_value":"receipt"}'::jsonb, 1, 'L45 supermarket')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'vocabulary', 'matching', 7, '{"instruction":"Match each action with its Uzbek word.","left":["reading","running","eating","writing"],"right":["O''qimoqda","Yugurmoqda","Yemoqda","Yozmoqda"]}'::jsonb, '{"pairs":[["reading","O''qimoqda"],["running","Yugurmoqda"],["eating","Yemoqda"],["writing","Yozmoqda"]]}'::jsonb, 1, 'L49 continuous')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'vocabulary', 'multiple_choice', 8, '{"question":"What does “Kecha oqshom” mean in English?","options":["last night","yesterday","last week","stayed"]}'::jsonb, '{"correct_value":"last night"}'::jsonb, 1, 'L48 yesterday')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'vocabulary', 'multiple_choice', 9, '{"question":"What does “Reja” mean in English?","options":["plan","visit","buy","meet"]}'::jsonb, '{"correct_value":"plan"}'::jsonb, 1, 'L50 plans')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'vocabulary', 'multiple_choice', 10, '{"question":"What does “Qaytim” mean in English?","options":["change","discount","receipt","cashier"]}'::jsonb, '{"correct_value":"change"}'::jsonb, 1, 'L47 supermarket')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'grammar', 'multiple_choice', 1, '{"question":"I ___ football yesterday.","options":["played","play"]}'::jsonb, '{"correct_value":"played"}'::jsonb, 1, 'L41 past simple')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'grammar', 'multiple_choice', 2, '{"question":"Which sentence is correct?","options":["I play football yesterday.","I played football yesterday.","I plays football yesterday."]}'::jsonb, '{"correct_value":"I played football yesterday."}'::jsonb, 1, 'L41 past correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'grammar', 'multiple_choice', 3, '{"question":"She ___ her friend at school.","options":["saw","see"]}'::jsonb, '{"correct_value":"saw"}'::jsonb, 1, 'L42 irregular')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'grammar', 'multiple_choice', 4, '{"question":"Which sentence is correct?","options":["I have any bread.","I have some bread.","I has some bread."]}'::jsonb, '{"correct_value":"I have some bread."}'::jsonb, 1, 'L43 some-any correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'grammar', 'multiple_choice', 5, '{"question":"I''d ___ a kilo of apples, please.","options":["like","want"]}'::jsonb, '{"correct_value":"like"}'::jsonb, 1, 'L45 supermarket')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'grammar', 'multiple_choice', 6, '{"question":"Which sentence is correct?","options":["How much apples are there?","How many apples are there?","How many apples is there?"]}'::jsonb, '{"correct_value":"How many apples are there?"}'::jsonb, 1, 'L44 how-many correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'grammar', 'multiple_choice', 7, '{"question":"What ___ your father do?","options":["does","do"]}'::jsonb, '{"correct_value":"does"}'::jsonb, 1, 'L46 jobs')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'grammar', 'multiple_choice', 8, '{"question":"She ___ cooking dinner.","options":["is","are"]}'::jsonb, '{"correct_value":"is"}'::jsonb, 1, 'L49 continuous')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'grammar', 'multiple_choice', 9, '{"question":"I ___ going to study.","options":["am","is"]}'::jsonb, '{"correct_value":"am"}'::jsonb, 1, 'L50 going-to')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'grammar', 'multiple_choice', 10, '{"question":"Which sentence is correct?","options":["I going to study.","I am going to study.","I is going to study."]}'::jsonb, '{"correct_value":"I am going to study."}'::jsonb, 1, 'L50 going-to correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'sentences', 'ordering', 1, '{"instruction":"Put the words in order.","tokens":["I","played","football","yesterday."]}'::jsonb, '{"correct_order":["I","played","football","yesterday."]}'::jsonb, 1, 'L41 past simple')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'sentences', 'ordering', 2, '{"instruction":"Put the words in order.","tokens":["I","went","to","the","market","yesterday."]}'::jsonb, '{"correct_order":["I","went","to","the","market","yesterday."]}'::jsonb, 1, 'L42 irregular')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'sentences', 'fill_blank', 3, '{"instruction":"Fill in the blank.","template":"There aren''t ___ eggs."}'::jsonb, '{"answer":"any"}'::jsonb, 1, 'L43 some-any')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'sentences', 'fill_blank', 4, '{"instruction":"Fill in the blank.","template":"___ I have a bottle of milk?"}'::jsonb, '{"answer":"Can"}'::jsonb, 1, 'L45 supermarket')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'sentences', 'ordering', 5, '{"instruction":"Put the words in order.","tokens":["What","does","your","father","do?"]}'::jsonb, '{"correct_order":["What","does","your","father","do?"]}'::jsonb, 1, 'L46 jobs')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'sentences', 'fill_blank', 6, '{"instruction":"Fill in the past verb.","template":"Last week we ___ (go) to Tashkent."}'::jsonb, '{"answer":"went"}'::jsonb, 1, 'L48 yesterday')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'sentences', 'ordering', 7, '{"instruction":"Put the words in order.","tokens":["I''d","like","a","bag,","please."]}'::jsonb, '{"correct_order":["I''d","like","a","bag,","please."]}'::jsonb, 1, 'L47 supermarket')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'sentences', 'ordering', 8, '{"instruction":"Put the words in order.","tokens":["I","am","going","to","study."]}'::jsonb, '{"correct_order":["I","am","going","to","study."]}'::jsonb, 1, 'L50 going-to')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'writing', 'translation', 1, '{"instruction":"Translate into English.","source_text":"Mana qaytimingiz.","direction":"uz2en"}'::jsonb, '{"target_text":"Here''s your change."}'::jsonb, 1, 'L47 supermarket')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'writing', 'translation', 2, '{"instruction":"Translate into English.","source_text":"Kecha bozorga bordim.","direction":"uz2en"}'::jsonb, '{"target_text":"I went to the market yesterday."}'::jsonb, 1, 'L42 irregular')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'writing', 'translation', 3, '{"instruction":"Translate into English.","source_text":"Nechta tuxum bor?","direction":"uz2en"}'::jsonb, '{"target_text":"How many eggs are there?"}'::jsonb, 1, 'L44 how-many')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'writing', 'ordering', 4, '{"instruction":"Put the words in order to fix the sentence.","tokens":["She","is","cooking","dinner."]}'::jsonb, '{"correct_order":["She","is","cooking","dinner."]}'::jsonb, 1, 'L49 continuous correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'writing', 'translation', 5, '{"instruction":"Translate into English.","source_text":"Shifokor","direction":"uz2en"}'::jsonb, '{"target_text":"doctor"}'::jsonb, 1, 'L46 jobs')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 5), 'writing', 'translation', 6, '{"instruction":"Translate into English.","source_text":"Bir oz","direction":"uz2en"}'::jsonb, '{"target_text":"a little"}'::jsonb, 1, 'L44 quantities')
on conflict (test_id, stage, position) do nothing;
