-- Online English Tests: Test 8 frozen content (Lessons 71-80).
-- Generated by scripts/build-online-test1-migration.cjs from
-- src/features/onlineTests/data/test8.json. Do not hand-edit;
-- regenerate instead. Inserts are DO NOTHING on conflict so
-- re-applying never mutates published (frozen) items.

insert into public.online_tests (test_number, title, lesson_from, lesson_to, is_published)
values (8, 'Test 8', 71, 80, true)
on conflict (test_number) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'vocabulary', 'multiple_choice', 1, '{"question":"What does “Tizza” mean in English?","options":["knee","shoulder","arm","hand"]}'::jsonb, '{"correct_value":"knee"}'::jsonb, 1, 'L71 body')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'vocabulary', 'multiple_choice', 2, '{"question":"What does “Isitma” mean in English?","options":["fever","cough","medicine","headache"]}'::jsonb, '{"correct_value":"fever"}'::jsonb, 1, 'L72 illness')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'vocabulary', 'matching', 3, '{"instruction":"Match each clinic word with its Uzbek word.","left":["patient","receptionist","prescription","pharmacy"],"right":["Bemor","Registrator","Retsept","Dorixona"]}'::jsonb, '{"pairs":[["patient","Bemor"],["receptionist","Registrator"],["prescription","Retsept"],["pharmacy","Dorixona"]]}'::jsonb, 1, 'L73 clinic')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'vocabulary', 'multiple_choice', 4, '{"question":"What does “Tez yordam” mean in English?","options":["ambulance","fire","danger","help"]}'::jsonb, '{"correct_value":"ambulance"}'::jsonb, 1, 'L74 emergencies')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'vocabulary', 'multiple_choice', 5, '{"question":"What does “Orzu” mean in English?","options":["dream","career","scientist","useful"]}'::jsonb, '{"correct_value":"dream"}'::jsonb, 1, 'L77 careers')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'vocabulary', 'multiple_choice', 6, '{"question":"What does “Forma” mean in English?","options":["uniform","duty","meeting","colleague"]}'::jsonb, '{"correct_value":"uniform"}'::jsonb, 1, 'L78 work')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'vocabulary', 'matching', 7, '{"instruction":"Match each work word with its Uzbek word.","left":["salary","experience","skills","employee"],"right":["Maosh","Tajriba","Mahoratlar","Xodim"]}'::jsonb, '{"pairs":[["salary","Maosh"],["experience","Tajriba"],["skills","Mahoratlar"],["employee","Xodim"]]}'::jsonb, 1, 'L79 interview')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'vocabulary', 'multiple_choice', 8, '{"question":"What does “Maslahat” mean in English?","options":["advice","healthy","energy","lifestyle"]}'::jsonb, '{"correct_value":"advice"}'::jsonb, 1, 'L76 health')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'vocabulary', 'multiple_choice', 9, '{"question":"What does “Maqsad” mean in English?","options":["goal","achievement","progress","experience"]}'::jsonb, '{"correct_value":"goal"}'::jsonb, 1, 'L80 review')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'vocabulary', 'multiple_choice', 10, '{"question":"What does “Kutish xonasi” mean in English?","options":["waiting room","patient","nurse","pharmacist"]}'::jsonb, '{"correct_value":"waiting room"}'::jsonb, 1, 'L75 clinic')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'grammar', 'multiple_choice', 1, '{"question":"My head ___.","options":["hurts","hurt"]}'::jsonb, '{"correct_value":"hurts"}'::jsonb, 1, 'L71 body')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'grammar', 'multiple_choice', 2, '{"question":"Which sentence is correct?","options":["My head hurt.","My head hurts.","My head hurting."]}'::jsonb, '{"correct_value":"My head hurts."}'::jsonb, 1, 'L71 body correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'grammar', 'multiple_choice', 3, '{"question":"I have ___ fever.","options":["a","the"]}'::jsonb, '{"correct_value":"a"}'::jsonb, 1, 'L72 illness')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'grammar', 'multiple_choice', 4, '{"question":"Which sentence is correct?","options":["I have headache.","I have a headache.","I have an headache."]}'::jsonb, '{"correct_value":"I have a headache."}'::jsonb, 1, 'L72 illness correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'grammar', 'multiple_choice', 5, '{"question":"You ___ call 103.","options":["must","mustn''t"]}'::jsonb, '{"correct_value":"must"}'::jsonb, 1, 'L74 emergencies')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'grammar', 'multiple_choice', 6, '{"question":"Which sentence is correct?","options":["You must to call.","You must call.","You must calling."]}'::jsonb, '{"correct_value":"You must call."}'::jsonb, 1, 'L74 emergencies correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'grammar', 'multiple_choice', 7, '{"question":"I want ___ be a doctor.","options":["to","-"]}'::jsonb, '{"correct_value":"to"}'::jsonb, 1, 'L77 careers')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'grammar', 'multiple_choice', 8, '{"question":"She ___ wear a uniform.","options":["has to","have to"]}'::jsonb, '{"correct_value":"has to"}'::jsonb, 1, 'L78 work')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'grammar', 'multiple_choice', 9, '{"question":"What ___ are you good at?","options":["skills","skill"]}'::jsonb, '{"correct_value":"skills"}'::jsonb, 1, 'L79 interview')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'grammar', 'multiple_choice', 10, '{"question":"I want to ___ my English.","options":["improve","improvement"]}'::jsonb, '{"correct_value":"improve"}'::jsonb, 1, 'L80 review')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'sentences', 'ordering', 1, '{"instruction":"Put the words in order.","tokens":["My","head","hurts."]}'::jsonb, '{"correct_order":["My","head","hurts."]}'::jsonb, 1, 'L71 body')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'sentences', 'fill_blank', 2, '{"instruction":"Fill in the blank.","template":"Take one ___ twice a day."}'::jsonb, '{"answer":"tablet"}'::jsonb, 1, 'L73 clinic')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'sentences', 'fill_blank', 3, '{"instruction":"Fill in the blank.","template":"You ___ touch the fire."}'::jsonb, '{"answer":"mustn''t"}'::jsonb, 1, 'L74 emergencies')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'sentences', 'ordering', 4, '{"instruction":"Put the words in order.","tokens":["I","want","to","be","a","doctor."]}'::jsonb, '{"correct_order":["I","want","to","be","a","doctor."]}'::jsonb, 1, 'L77 careers')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'sentences', 'ordering', 5, '{"instruction":"Put the words in order.","tokens":["I","have","to","wear","a","uniform."]}'::jsonb, '{"correct_order":["I","have","to","wear","a","uniform."]}'::jsonb, 1, 'L78 work')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'sentences', 'fill_blank', 6, '{"instruction":"Fill in the blank.","template":"I am hard-___."}'::jsonb, '{"answer":"working"}'::jsonb, 1, 'L79 interview')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'sentences', 'fill_blank', 7, '{"instruction":"Fill in the blank.","template":"I eat ___ food."}'::jsonb, '{"answer":"healthy"}'::jsonb, 1, 'L76 health')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'sentences', 'fill_blank', 8, '{"instruction":"Fill in the blank.","template":"Who takes your card first? The ___."}'::jsonb, '{"answer":"receptionist"}'::jsonb, 1, 'L75 clinic')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'writing', 'translation', 1, '{"instruction":"Translate into English.","source_text":"Tizzam og''riyapti.","direction":"uz2en"}'::jsonb, '{"target_text":"My knee hurts."}'::jsonb, 1, 'L71 body')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'writing', 'translation', 2, '{"instruction":"Translate into English.","source_text":"Dori","direction":"uz2en"}'::jsonb, '{"target_text":"medicine"}'::jsonb, 1, 'L72 illness')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'writing', 'translation', 3, '{"instruction":"Translate into English.","source_text":"Yordam","direction":"uz2en"}'::jsonb, '{"target_text":"help"}'::jsonb, 1, 'L74 emergencies')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'writing', 'ordering', 4, '{"instruction":"Put the words in order.","tokens":["I","want","to","become","a","doctor."]}'::jsonb, '{"correct_order":["I","want","to","become","a","doctor."]}'::jsonb, 1, 'L77 careers correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'writing', 'translation', 5, '{"instruction":"Translate into English.","source_text":"Vazifa","direction":"uz2en"}'::jsonb, '{"target_text":"duty"}'::jsonb, 1, 'L78 work')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 8), 'writing', 'translation', 6, '{"instruction":"Translate into English.","source_text":"Yutuq","direction":"uz2en"}'::jsonb, '{"target_text":"achievement"}'::jsonb, 1, 'L80 review')
on conflict (test_id, stage, position) do nothing;
