-- Online English Tests: Test 1 frozen content (Lessons 1-10).
-- Generated by scripts/build-online-test1-migration.cjs from
-- src/features/onlineTests/data/test1.json. Do not hand-edit;
-- regenerate instead. Inserts are DO NOTHING on conflict so
-- re-applying never mutates published (frozen) items.

insert into public.online_tests (test_number, title, lesson_from, lesson_to, is_published)
values (1, 'Test 1', 1, 10, true)
on conflict (test_number) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'vocabulary', 'multiple_choice', 1, '{"question":"What does “Good morning” mean?","options":["Xayrli tong","Xayrli kun","Xayrli kech","Xayr"]}'::jsonb, '{"correct_value":"Xayrli tong"}'::jsonb, 1, 'L1 greetings')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'vocabulary', 'multiple_choice', 2, '{"question":"What does “qizil” mean in English?","options":["red","blue","green","black"]}'::jsonb, '{"correct_value":"red"}'::jsonb, 1, 'L3 colors')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'vocabulary', 'multiple_choice', 3, '{"question":"What does “How old are you?” mean?","options":["Necha yoshdasiz?","Ismingiz nima?","Qalaysiz?","Nechta?"]}'::jsonb, '{"correct_value":"Necha yoshdasiz?"}'::jsonb, 1, 'L2 age')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'vocabulary', 'matching', 4, '{"instruction":"Match each animal with its Uzbek word.","left":["Cat","Dog","Bird","Fish"],"right":["Mushuk","It","Qush","Baliq"]}'::jsonb, '{"pairs":[["Cat","Mushuk"],["Dog","It"],["Bird","Qush"],["Fish","Baliq"]]}'::jsonb, 1, 'L9 animals')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'vocabulary', 'multiple_choice', 5, '{"question":"What does “book” mean?","options":["kitob","qalam","stul","parta"]}'::jsonb, '{"correct_value":"kitob"}'::jsonb, 1, 'L4 classroom')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'vocabulary', 'multiple_choice', 6, '{"question":"What does “yuz” mean in English?","options":["hundred","twenty","thirty","fifty"]}'::jsonb, '{"correct_value":"hundred"}'::jsonb, 1, 'L5 numbers')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'vocabulary', 'matching', 7, '{"instruction":"Match each question word with its Uzbek word.","left":["who","what","where","when"],"right":["kim","nima","qayerda","qachon"]}'::jsonb, '{"pairs":[["who","kim"],["what","nima"],["where","qayerda"],["when","qachon"]]}'::jsonb, 1, 'L6 question words')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'vocabulary', 'multiple_choice', 8, '{"question":"What does “Swim” mean?","options":["Suzmoq","Yugurmoq","Sakramoq","Chiqmoq"]}'::jsonb, '{"correct_value":"Suzmoq"}'::jsonb, 1, 'L10 abilities')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'vocabulary', 'multiple_choice', 9, '{"question":"What does “sariq” mean in English?","options":["yellow","red","blue","green"]}'::jsonb, '{"correct_value":"yellow"}'::jsonb, 1, 'L7 colors games day')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'vocabulary', 'multiple_choice', 10, '{"question":"What does “Nice to meet you” mean?","options":["Tanishganimdan xursandman","Xayrli tong","Yaxshiman, rahmat","Xayr"]}'::jsonb, '{"correct_value":"Tanishganimdan xursandman"}'::jsonb, 1, 'L8 introductions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'grammar', 'multiple_choice', 1, '{"question":"It ___ an elephant.","options":["is","are"]}'::jsonb, '{"correct_value":"is"}'::jsonb, 1, 'L9 be-verb animals')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'grammar', 'multiple_choice', 2, '{"question":"How ___ you?","options":["is","are"]}'::jsonb, '{"correct_value":"are"}'::jsonb, 1, 'L1 be-verb')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'grammar', 'multiple_choice', 3, '{"question":"These ___ red apples.","options":["are","is"]}'::jsonb, '{"correct_value":"are"}'::jsonb, 1, 'L7 plural games day')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'grammar', 'multiple_choice', 4, '{"question":"I ___ swim.","options":["can","is"]}'::jsonb, '{"correct_value":"can"}'::jsonb, 1, 'L10 can')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'grammar', 'multiple_choice', 5, '{"question":"I ___ ten years old.","options":["am","is"]}'::jsonb, '{"correct_value":"am"}'::jsonb, 1, 'L2 be-verb age')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'grammar', 'multiple_choice', 6, '{"question":"Which sentence is correct?","options":["It red.","It is red.","It are red."]}'::jsonb, '{"correct_value":"It is red."}'::jsonb, 1, 'L3 be-verb correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'grammar', 'multiple_choice', 7, '{"question":"Which sentence is correct?","options":["I am twenty years old.","I am twenty year old.","I twenty years old."]}'::jsonb, '{"correct_value":"I am twenty years old."}'::jsonb, 1, 'L5 numbers correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'grammar', 'multiple_choice', 8, '{"question":"I am ___ student.","options":["a","an"]}'::jsonb, '{"correct_value":"a"}'::jsonb, 1, 'L8 articles self-intro')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'grammar', 'multiple_choice', 9, '{"question":"___ your book.","options":["Open","Opens"]}'::jsonb, '{"correct_value":"Open"}'::jsonb, 1, 'L4 imperatives')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'grammar', 'multiple_choice', 10, '{"question":"___ is your birthday?","options":["When","Who"]}'::jsonb, '{"correct_value":"When"}'::jsonb, 1, 'L6 question words')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'sentences', 'ordering', 1, '{"instruction":"Put the words in order.","tokens":["My","name","is","Ali."]}'::jsonb, '{"correct_order":["My","name","is","Ali."]}'::jsonb, 1, 'L1 introductions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'sentences', 'ordering', 2, '{"instruction":"Put the words in order.","tokens":["Nice","to","meet","you."]}'::jsonb, '{"correct_order":["Nice","to","meet","you."]}'::jsonb, 1, 'L8 introductions')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'sentences', 'fill_blank', 3, '{"instruction":"Fill in the blank.","template":"The sky is ___."}'::jsonb, '{"answer":"blue"}'::jsonb, 1, 'L3 colors')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'sentences', 'fill_blank', 4, '{"instruction":"Fill in the blank.","template":"Snow is ___."}'::jsonb, '{"answer":"white"}'::jsonb, 1, 'L3 colors')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'sentences', 'ordering', 5, '{"instruction":"Put the words in order.","tokens":["I","am","ten","years","old."]}'::jsonb, '{"correct_order":["I","am","ten","years","old."]}'::jsonb, 1, 'L2 age')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'sentences', 'fill_blank', 6, '{"instruction":"Fill in the blank with a classroom command.","template":"___ down, please."}'::jsonb, '{"answer":"Sit"}'::jsonb, 1, 'L4 classroom')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'sentences', 'ordering', 7, '{"instruction":"Put the words in order.","tokens":["three","red","apples"]}'::jsonb, '{"correct_order":["three","red","apples"]}'::jsonb, 1, 'L7 games day')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'sentences', 'fill_blank', 8, '{"instruction":"Write the number in words.","template":"21 is ___."}'::jsonb, '{"answer":"twenty-one"}'::jsonb, 1, 'L5 numbers')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'writing', 'translation', 1, '{"instruction":"Translate into Uzbek.","source_text":"Good morning.","direction":"en2uz"}'::jsonb, '{"target_text":"Xayrli tong"}'::jsonb, 1, 'L1 greetings')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'writing', 'translation', 2, '{"instruction":"Translate into English.","source_text":"Necha yoshdasiz?","direction":"uz2en"}'::jsonb, '{"target_text":"How old are you?"}'::jsonb, 1, 'L2 age')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'writing', 'translation', 3, '{"instruction":"Translate into English.","source_text":"Suzmoq","direction":"uz2en"}'::jsonb, '{"target_text":"Swim"}'::jsonb, 1, 'L10 abilities')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'writing', 'ordering', 4, '{"instruction":"Put the words in order to fix the question.","tokens":["What","is","this?"]}'::jsonb, '{"correct_order":["What","is","this?"]}'::jsonb, 1, 'L6 questions correction')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'writing', 'fill_blank', 5, '{"instruction":"Fill in the blank with “a” or “an”.","template":"We say “___ cat”."}'::jsonb, '{"answer":"an"}'::jsonb, 1, 'L9 articles')
on conflict (test_id, stage, position) do nothing;

insert into public.online_test_items (test_id, stage, question_type, position, prompt_data, answer_key, points, source_ref)
values ((select id from public.online_tests where test_number = 1), 'writing', 'translation', 6, '{"instruction":"Translate into English.","source_text":"Fil","direction":"uz2en"}'::jsonb, '{"target_text":"Elephant"}'::jsonb, 1, 'L9 animals')
on conflict (test_id, stage, position) do nothing;
