-- RECONCILIATION FILE — reconstructed from live prod schema (project
-- usqzcsoolkbuxyiiawmx) on 2026-08-16, not original migration source.
-- No true prod timestamp could be recovered for these three tables (they
-- predate this reconciliation effort and were never captured locally),
-- so this uses a descriptive name instead of the PROD_RECONCILED_<ts>_
-- scheme used elsewhere (see docs/migration-reconciliation-2026-08-15.md).
-- This file documents schema that already exists in prod. Applying it
-- is a no-op there (all `create table if not exists` / `create policy`
-- guarded); it exists so local git history matches reality, closing the
-- gap flagged in docs/gamification-system-audit-2026-08-16.md.

create table if not exists public.achievement_definitions (
  id bigint generated by default as identity primary key,
  key text not null unique,
  name text not null,
  description text,
  icon text,
  category text not null default 'achievement'
    check (category in ('achievement','badge','streak','milestone','mission','seasonal')),
  trigger_type text not null
    check (trigger_type in ('immediate_event','threshold','scheduled','streak','manual')),
  rule_config jsonb not null default '{}'::jsonb,
  bonus_points numeric not null default 0,
  rarity text not null default 'common' check (rarity in ('common','rare','epic')),
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.achievement_definitions enable row level security;

drop policy if exists achievement_definitions_admin_all on public.achievement_definitions;
create policy achievement_definitions_admin_all on public.achievement_definitions for all
  using (is_admin()) with check (is_admin());

drop policy if exists achievement_definitions_read_active on public.achievement_definitions;
create policy achievement_definitions_read_active on public.achievement_definitions for select
  using (active);

create table if not exists public.student_achievements (
  student_id bigint not null references public.students(id) on delete cascade,
  achievement_id bigint not null references public.achievement_definitions(id) on delete cascade,
  earned_at timestamptz not null default now(),
  awarded_by uuid references public.profiles(id),
  point_transaction_id bigint references public.point_transactions(id),
  primary key (student_id, achievement_id)
);

alter table public.student_achievements enable row level security;

drop policy if exists student_achievements_admin_all on public.student_achievements;
create policy student_achievements_admin_all on public.student_achievements for all
  using (is_admin()) with check (is_admin());

drop policy if exists student_achievements_self_select on public.student_achievements;
create policy student_achievements_self_select on public.student_achievements for select
  using (public.is_own_student(student_id));

drop policy if exists student_achievements_teacher_select on public.student_achievements;
create policy student_achievements_teacher_select on public.student_achievements for select
  using (
    is_teacher() and exists (
      select 1 from public.students s
      join public.teacher_group_assignments tga
        on tga.teacher_id = auth.uid() and tga.level = s.level
      where s.id = student_achievements.student_id
    )
  );

drop policy if exists student_achievements_teacher_insert on public.student_achievements;
create policy student_achievements_teacher_insert on public.student_achievements for insert
  with check (
    is_teacher() and exists (
      select 1 from public.students s
      join public.teacher_group_assignments tga
        on tga.teacher_id = auth.uid() and tga.level = s.level
      where s.id = student_achievements.student_id
    )
  );

create table if not exists public.student_metric_snapshots (
  student_id bigint not null references public.students(id) on delete cascade,
  metric_key text not null,
  value numeric not null default 0,
  updated_at timestamptz not null default now(),
  primary key (student_id, metric_key)
);

alter table public.student_metric_snapshots enable row level security;

drop policy if exists student_metric_snapshots_self_select on public.student_metric_snapshots;
create policy student_metric_snapshots_self_select on public.student_metric_snapshots for select
  using (public.is_own_student(student_id));

drop policy if exists student_metric_snapshots_admin_teacher_select on public.student_metric_snapshots;
create policy student_metric_snapshots_admin_teacher_select on public.student_metric_snapshots for select
  using (is_admin() or is_teacher());
